# Seed data for The Signature Mr Fix-It archive (author: ABE batch).
# Real, plain-language repair guidance. Titles are unique across the archive.

PROBLEMS = [
    {
        "field": "Electrical",
        "title": "Dead outlet — no power at all",
        "symptoms": ["Outlet delivers no power to a lamp you know works", "The breaker does not look tripped", "Nearby outlets on other walls work fine"],
        "diagnosis": ["Confirm the outlet is really dead with a known-good lamp", "At the panel, flip the suspect breaker fully OFF then back ON", "Press RESET on any GFCI outlet on the same circuit (kitchens, baths, garage, outdoors)", "With the breaker OFF, remove the cover plate and look for loose or scorched wires"],
        "diy_title": "Reset protection devices and reseat the outlet wiring",
        "diy_steps": ["Turn the breaker OFF and confirm the outlet is dead with a non-contact voltage tester", "Remove the cover plate and mounting screws, then pull the outlet gently from the box", "Tighten any loose terminal screws; re-strip and reattach any nicked or burnt wire ends", "Push the outlet back in, reinstall the cover, turn the breaker on, and test with the lamp", "If the outlet is scorched, cracked, or the breaker trips again, stop and call a licensed electrician"],
        "time": "20–30 min",
        "cost": "$0–$15",
        "difficulty": "Moderate",
        "tools": ["Non-contact voltage tester", "Insulated screwdriver set", "Flashlight"],
        "parts": ["Replacement duplex outlet (if scorched or cracked)"],
        "safety": "HIGH",
        "warnings": ["Verify the circuit is DEAD with a tester before touching any wire", "Scorch marks or a burning smell mean stop and call an electrician", "Never work on a live circuit"],
        "mall": "outlet tester",
    },
    {
        "field": "Electrical",
        "title": "Breaker keeps tripping",
        "symptoms": ["Breaker flips to the middle or OFF position repeatedly", "Power dies on several outlets or lights at once", "A burning smell or a warm breaker face"],
        "diagnosis": ["Unplug everything on that circuit and reset the breaker", "Plug devices back in one at a time to find the one that trips it", "Sniff for burning and feel the breaker face for unusual heat", "If it trips with nothing plugged in, the wiring or breaker itself is suspect", "Note whether it is a standard, GFCI, or AFCI breaker — each trips for different reasons"],
        "diy_title": "Find the overload or fault, then reset safely",
        "diy_steps": ["Unplug all devices on the affected circuit", "Stand to the side of the panel, flip the breaker fully OFF, then firmly ON", "Reconnect devices one at a time; the one that trips it is the culprit — repair or replace it", "Move heavy loads (space heaters, hair dryers) to different circuits to stop overloads", "If the breaker trips with nothing connected, feels hot, or smells burnt, leave it OFF and call an electrician"],
        "time": "15–30 min",
        "cost": "$0–$25",
        "difficulty": "Easy",
        "tools": ["Flashlight", "Non-contact voltage tester"],
        "parts": ["Replacement breaker (electrician-installed, if faulty)"],
        "safety": "HIGH",
        "warnings": ["Stand to the side of the panel when resetting in case of arcing", "A hot breaker or burning smell means leave it OFF and call an electrician", "Never hold a breaker in the ON position or bypass it"],
        "mall": "circuit breaker",
    },
    {
        "field": "Electrical",
        "title": "Flickering lights",
        "symptoms": ["One or more lights flicker or dim intermittently", "Flicker happens when a large appliance starts", "Flicker affects lights on multiple circuits"],
        "diagnosis": ["Tighten the bulb — a loose bulb is the most common cause", "Check whether the flicker is one fixture or the whole house", "Try a bulb of the right type for the dimmer to rule out a mismatch", "Whole-house flicker points to a loose service neutral — a utility or electrician issue", "Ask neighbors if their lights flicker too — that points to the utility"],
        "diy_title": "Tighten bulbs and isolate the flicker source",
        "diy_steps": ["Turn the light OFF, let the bulb cool, then tighten it firmly", "Swap in a known-good bulb rated for the dimmer", "If flicker is house-wide, do not open the panel — call the power company or an electrician", "Report utility-side flicker promptly; loose service neutrals are their fix"],
        "time": "10–20 min",
        "cost": "$0–$10",
        "difficulty": "Easy",
        "tools": ["Step ladder", "Replacement bulb"],
        "parts": ["LED bulbs rated for your dimmer (if mismatched)"],
        "safety": "MEDIUM",
        "warnings": ["Turn the light off and let bulbs cool before handling", "Never open the breaker panel yourself — call an electrician for panel work", "Whole-house flicker with dimming can signal a loose neutral: report it promptly"],
        "mall": "dimmable led bulbs",
    },
    {
        "field": "Electrical",
        "title": "GFCI outlet won't reset",
        "symptoms": ["RESET button will not stay in when pressed", "Outlet is dead though the breaker is on", "TEST button does nothing"],
        "diagnosis": ["Unplug everything from the GFCI and its downstream outlets", "Press TEST firmly, then press RESET firmly", "Look for moisture around the outlet — kitchens, baths, and outdoors trip often", "Check the breaker that feeds it and reset if needed", "If it still will not reset with nothing plugged in, the GFCI itself has failed"],
        "diy_title": "Clear loads and moisture, then replace the GFCI if dead",
        "diy_steps": ["Unplug all devices from the GFCI and every outlet it protects", "Dry any visible moisture and wait 30 minutes", "Press TEST, then press RESET until it clicks and holds", "If it holds, plug devices back one at a time to find a faulty appliance", "If it will not reset with nothing connected, turn the breaker OFF and replace the GFCI with an identical one, matching LINE and LOAD wires exactly", "If you are unsure which wires are LINE vs LOAD, stop and call an electrician"],
        "time": "15–40 min",
        "cost": "$12–$25",
        "difficulty": "Moderate",
        "tools": ["Non-contact voltage tester", "Insulated screwdriver set", "Towel"],
        "parts": ["GFCI outlet (same amperage)"],
        "safety": "MEDIUM",
        "warnings": ["Turn the breaker OFF and test dead before replacing", "Wiring LINE and LOAD backwards leaves downstream outlets unprotected"],
        "mall": "gfci outlet",
    },
    {
        "field": "Electrical",
        "title": "Doorbell stopped working",
        "symptoms": ["No chime when the button is pressed", "Button feels loose or stuck", "Chime hums but does not ring"],
        "diagnosis": ["Press the button firmly and listen at the chime for any hum", "Remove the button and touch its two wires together — a ring means the button is bad", "Check the transformer (often near the panel or in a closet) for a low-voltage reading", "Inspect the chime mechanism for stuck plungers or dust"],
        "diy_title": "Test button, transformer, and chime in order",
        "diy_steps": ["Turn OFF the breaker feeding the doorbell transformer", "Unscrew the button and briefly touch its two wires together", "If it rings, replace the button; if not, check the transformer output with a multimeter (should read about 16–24 volts)", "Replace a dead transformer with the same voltage rating", "Clean or replace a humming, stuck chime mechanism", "Restore power and test"],
        "time": "20–40 min",
        "cost": "$5–$25",
        "difficulty": "Moderate",
        "tools": ["Multimeter", "Screwdriver set"],
        "parts": ["Doorbell button", "Doorbell transformer (if dead)"],
        "safety": "MEDIUM",
        "warnings": ["Turn off the breaker — the transformer is fed by 120V mains", "Do not short the transformer's high-voltage primary side"],
        "mall": "doorbell transformer",
    },
    {
        "field": "Electrical",
        "title": "Ceiling fan wobbles",
        "symptoms": ["Fan wobbles visibly at medium or high speed", "Clicking or rattling noise while running", "Fan was recently installed or bumped"],
        "diagnosis": ["Turn the fan off and check every blade screw for tightness", "Measure blade height from the ceiling — all blades must match", "Look for a bent blade or loose downrod pin", "Confirm the mounting box is braced for fan weight, not just a light box"],
        "diy_title": "Tighten, level, and balance the blades",
        "diy_steps": ["Turn the fan OFF at the wall switch and breaker", "Tighten all blade screws, the downrod pin, and the mounting bracket", "Measure each blade tip to the ceiling and gently adjust the blade arm so all match", "Attach the balancing kit's clip to one blade, run the fan, and move the clip until wobble is minimal", "Stick the balance weight at the clip's best spot and remove the clip", "If the box is not fan-rated or the wobble persists, stop and call an electrician"],
        "time": "30–60 min",
        "cost": "$0–$12",
        "difficulty": "Easy",
        "tools": ["Step ladder", "Screwdriver set", "Tape measure"],
        "parts": ["Ceiling fan balancing kit"],
        "safety": "MEDIUM",
        "warnings": ["Lock the power off — a running fan can injure hands", "Use a stable ladder; never stand on a chair"],
        "mall": "fan balancing kit",
    },
    {
        "field": "Electrical",
        "title": "Smoke detector chirping",
        "symptoms": ["Short chirp every 30–60 seconds", "Chirp continues after pressing the hush button", "Detector is over 10 years old"],
        "diagnosis": ["Replace the battery first — low battery is the top cause", "Check the manufacture date on the back; detectors expire after 10 years", "Clean dust from the sensor chamber with a vacuum", "On hardwired units, check that the interconnect wire is seated"],
        "diy_title": "Replace the battery, clean, or retire an old detector",
        "diy_steps": ["Twist the detector off its mounting bracket", "Replace the battery with a fresh one of the correct type and note today's date", "Vacuum the sensor slots gently to remove dust", "Press the test button and confirm a loud alarm", "If chirping continues or the unit is over 10 years old, replace the whole detector"],
        "time": "10–15 min",
        "cost": "$3–$30",
        "difficulty": "Easy",
        "tools": ["Step ladder", "Vacuum with brush attachment"],
        "parts": ["9V or AA batteries", "Replacement smoke detector (if expired)"],
        "safety": "LOW",
        "warnings": ["Test monthly and never leave a home without working detectors"],
        "mall": "smoke detector",
    },
    {
        "field": "Electrical",
        "title": "Outlet sparks when plugging in",
        "symptoms": ["Visible spark when a plug is inserted or removed", "Scorch marks around the slots", "Plug feels loose in the outlet"],
        "diagnosis": ["Note whether sparks are tiny and occasional or large and frequent", "Check for black marks, melting, or a burning smell", "Test whether the plug fits snugly or falls out", "Worn contacts that grip poorly arc more and overheat"],
        "diy_title": "Replace a worn or scorched outlet",
        "diy_steps": ["Turn the breaker OFF and verify dead with a non-contact tester", "Remove the cover and outlet, noting wire positions", "Install a new outlet of the same rating, wrapping wires clockwise around terminal screws", "Tighten terminals firmly and confirm no bare copper is exposed outside the screw", "Reinstall, restore power, and confirm plugs fit snugly with no sparks"],
        "time": "20–30 min",
        "cost": "$3–$12",
        "difficulty": "Moderate",
        "tools": ["Non-contact voltage tester", "Insulated screwdriver set"],
        "parts": ["Replacement duplex outlet"],
        "safety": "HIGH",
        "warnings": ["Verify dead before touching wires", "Large sparks, melting, or burning smell mean stop and call an electrician", "Unplug devices before inserting or removing plugs under heavy load"],
        "mall": "tamper resistant outlet",
    },
    {
        "field": "Electrical",
        "title": "Dimmer switch buzzing",
        "symptoms": ["Audible buzz from the dimmer switch", "Buzz changes with dimmer level", "LED bulbs flicker at low settings"],
        "diagnosis": ["Confirm the bulbs are rated dimmable and match the dimmer's type", "Add up bulb wattage — it must be within the dimmer's rating", "Try one incandescent bulb to isolate a bulb-dimmer mismatch", "Buzz from inside the wall box with correct bulbs means the dimmer is failing"],
        "diy_title": "Match bulbs to the dimmer or replace the dimmer",
        "diy_steps": ["Turn the breaker OFF and verify dead with a tester", "Remove the dimmer and note the wiring (line, load, ground)", "Install an LED-rated dimmer if your bulbs are LED", "Reconnect wires with wire nuts, fold in gently, and mount the dimmer", "Restore power and test across the full dim range", "If buzzing persists with matched parts, stop and call an electrician"],
        "time": "25–45 min",
        "cost": "$15–$35",
        "difficulty": "Moderate",
        "tools": ["Non-contact voltage tester", "Insulated screwdriver set", "Wire strippers"],
        "parts": ["LED-rated dimmer switch"],
        "safety": "HIGH",
        "warnings": ["Verify the circuit is dead before touching wires", "Do not exceed the dimmer's wattage rating", "Aluminum wiring needs special handling — call an electrician"],
        "mall": "led dimmer switch",
    },
    {
        "field": "Electrical",
        "title": "Light switch does nothing",
        "symptoms": ["Flip the switch and the light stays off", "Switch feels loose or crackles", "Breaker is on and the bulb is good"],
        "diagnosis": ["Test the bulb in a working lamp first", "Check the breaker for that room", "Listen for arcing or feel for heat at the switch", "With power off, inspect for loose terminal screws or a cracked switch body"],
        "diy_title": "Replace a failed light switch",
        "diy_steps": ["Turn the breaker OFF and verify dead at the switch with a tester", "Remove the cover plate and switch, photographing the wire layout", "Connect the new switch exactly the same way (note the ground wire)", "Mount, cover, restore power, and test", "If wires are scorched or the box is damaged, stop and call an electrician"],
        "time": "15–25 min",
        "cost": "$3–$10",
        "difficulty": "Moderate",
        "tools": ["Non-contact voltage tester", "Insulated screwdriver set"],
        "parts": ["Single-pole light switch"],
        "safety": "HIGH",
        "warnings": ["Verify dead with a tester before touching wires", "Photograph wiring before disconnecting"],
        "mall": "light switch",
    },
    {
        "field": "Electrical",
        "title": "Bathroom exhaust fan noisy",
        "symptoms": ["Loud rattling, humming, or squealing", "Fan runs but moves little air", "Noise started gradually over months"],
        "diagnosis": ["Turn power off and vacuum dust from the grille and blades", "Check for loose housing screws or a loose grille", "Spin the blower wheel by hand — grinding means worn bearings", "Confirm the damper flap outside is not stuck"],
        "diy_title": "Clean and tighten, then replace the motor or fan",
        "diy_steps": ["Turn OFF the breaker for the bathroom circuit", "Remove the grille and vacuum dust from the housing and blower", "Tighten all housing and mounting screws", "If noise persists, replace the motor assembly or the whole fan unit with the same size", "Reconnect wiring exactly as before, restore power, and test"],
        "time": "30–60 min",
        "cost": "$0–$60",
        "difficulty": "Moderate",
        "tools": ["Step ladder", "Screwdriver set", "Vacuum"],
        "parts": ["Replacement fan motor or exhaust fan unit"],
        "safety": "MEDIUM",
        "warnings": ["Turn the breaker off before opening the housing", "Support the fan body so it does not fall while you work"],
        "mall": "bathroom exhaust fan",
    },
    {
        "field": "Electrical",
        "title": "Landscape lights out",
        "symptoms": ["All or some yard lights are dark", "Transformer hums but lights stay off", "Lights flicker or are very dim"],
        "diagnosis": ["Check the transformer is plugged in and its timer settings", "Test transformer output with a multimeter (usually 12V)", "Walk the wire run looking for cuts from edging tools or rodents", "Open wire connectors and look for corrosion"],
        "diy_title": "Check power, then find the wire break",
        "diy_steps": ["Confirm the transformer has power and the timer is set correctly", "Test for about 12 volts at the transformer terminals", "Inspect the low-voltage cable for cuts and repair with waterproof wire connectors", "Clean corroded connections and re-seat bulbs", "If the transformer outputs nothing with good input power, replace it"],
        "time": "30–60 min",
        "cost": "$0–$40",
        "difficulty": "Easy",
        "tools": ["Multimeter", "Wire strippers"],
        "parts": ["Waterproof wire connectors", "Replacement bulbs", "Transformer (if dead)"],
        "safety": "LOW",
        "warnings": ["Unplug the transformer before handling wires", "Bury repaired cable a few inches deep to protect it"],
        "mall": "low voltage transformer",
    },
    {
        "field": "Electrical",
        "title": "Outlet cover cracked",
        "symptoms": ["Cover plate is cracked or broken", "Plugs still work fine", "Gap exposes the outlet body"],
        "diagnosis": ["Confirm only the cover is damaged, not the outlet itself", "Check that the outlet body is not cracked or loose", "Note the cover style (duplex, GFCI, toggle) to buy the right one"],
        "diy_title": "Swap the cover plate without touching wiring",
        "diy_steps": ["For extra safety, turn the breaker OFF (or work carefully with it on)", "Unscrew the center screw and remove the broken cover", "Fit the new cover plate over the outlet and tighten the screw gently", "Restore power and test the outlet"],
        "time": "5–10 min",
        "cost": "$1–$5",
        "difficulty": "Easy",
        "tools": ["Screwdriver", "Flashlight"],
        "parts": ["Outlet cover plate (matching style)"],
        "safety": "LOW",
        "warnings": ["Do not touch the outlet's terminal screws or wires", "If the outlet body itself is cracked, replace the outlet with the power off"],
        "mall": "outlet cover plate",
    },
    {
        "field": "Electrical",
        "title": "Light fixture humming",
        "symptoms": ["Steady hum or buzz from a ceiling fixture", "Hum changes when dimmed", "Older fluorescent fixture with flicker"],
        "diagnosis": ["Tighten the bulbs and any loose trim or glass", "Check for a dimmer mismatch with LED or CFL bulbs", "On fluorescent fixtures, a failing ballast hums and flickers", "Hum from the switch box instead points to the dimmer"],
        "diy_title": "Tighten parts, then fix the dimmer or ballast",
        "diy_steps": ["Turn the light OFF and tighten bulbs and trim", "If on a dimmer, confirm bulbs are dimmer-rated or swap the dimmer for an LED-rated one", "For a humming fluorescent ballast, turn the breaker OFF and replace the ballast with an identical rating — or upgrade to a ballast-bypass LED retrofit", "Restore power and confirm silence"],
        "time": "15–45 min",
        "cost": "$0–$30",
        "difficulty": "Moderate",
        "tools": ["Step ladder", "Screwdriver set", "Non-contact voltage tester"],
        "parts": ["LED-rated dimmer", "Replacement ballast or LED retrofit kit"],
        "safety": "HIGH",
        "warnings": ["Turn the breaker OFF before touching ballast wiring", "Older ballasts may contain hazardous materials — do not break them open"],
        "mall": "led retrofit kit",
    },
    {
        "field": "Electrical",
        "title": "Extension cord feels hot",
        "symptoms": ["Cord is warm or hot to the touch", "Plastic smells hot or looks melted", "Connected device runs weakly or cuts out"],
        "diagnosis": ["Unplug it immediately and let it cool", "Check the wattage of the device against the cord's rating", "Look for coiled cord (coils trap heat), damage, or undersized gauge", "Feel the plug ends — heat there means poor contact"],
        "diy_title": "Retire the cord and size the replacement correctly",
        "diy_steps": ["Unplug the cord and the device immediately", "Do not use the hot cord again if insulation is soft, melted, or discolored", "Buy a cord rated above the device's wattage with the shortest practical length", "Use 12-gauge for heavy loads (heaters, saws); fully uncoil cords in use", "Never plug one extension cord into another"],
        "time": "10–15 min",
        "cost": "$15–$40",
        "difficulty": "Easy",
        "tools": ["Tape measure", "Flashlight"],
        "parts": ["Heavy-duty extension cord (correct gauge)"],
        "safety": "MEDIUM",
        "warnings": ["A hot cord is a fire risk — unplug it right away", "Never run cords under rugs or through doorways", "Discard any cord with melted or cracked insulation"],
        "mall": "heavy duty extension cord",
    },
    {
        "field": "Electrical",
        "title": "Three-way switch wired wrong",
        "symptoms": ["Two switches control one light but behave oddly", "Light only works when one switch is in a certain position", "A switch position does nothing"],
        "diagnosis": ["Flip both switches through all four combinations and note the pattern", "Turn power off and identify the common wire (usually on the dark-colored screw)", "Check that travelers land on the two brass screws at both switches", "Look for a traveler and common swapped at one switch"],
        "diy_title": "Identify the common wire and re-land the travelers",
        "diy_steps": ["Turn the breaker OFF and verify dead at both switches with a tester", "At each switch, find the common wire on the dark screw and the two travelers on the brass screws", "Move any miswired traveler back to a brass screw and the common to the dark screw", "Restore power and test all four switch combinations", "If the wiring does not match a standard three-way layout, stop and call an electrician"],
        "time": "30–60 min",
        "cost": "$0–$10",
        "difficulty": "Hard",
        "tools": ["Non-contact voltage tester", "Insulated screwdriver set", "Masking tape and marker"],
        "parts": ["Three-way switch (if faulty)"],
        "safety": "HIGH",
        "warnings": ["Verify dead at BOTH switches — three-ways can be fed from either end", "Label every wire before disconnecting", "If you find unfamiliar wiring, stop and call an electrician"],
        "mall": "three way switch",
    },
    {
        "field": "Appliances",
        "title": "Fridge not cooling",
        "symptoms": ["Fridge section feels warm though the light is on", "Freezer still cold but fridge warming", "Compressor runs constantly or never runs"],
        "diagnosis": ["Check the thermostat setting and that vents inside are not blocked by food", "Pull the fridge out and vacuum dust from the condenser coils", "Listen: is the compressor humming and is the evaporator fan spinning", "Inspect door gaskets for tears or gaps", "Feel the compressor — burning hot with no cooling suggests a failed start relay"],
        "diy_title": "Restore airflow and cooling basics",
        "diy_steps": ["Set the fridge to 37°F and freezer to 0°F; clear blocked interior vents", "Unplug the fridge and vacuum the condenser coils (underneath or behind)", "Check the door seals with the dollar-bill test and clean or replace bad gaskets", "If the compressor will not start, unplug and swap the start relay with an identical part", "If the sealed refrigerant system is the problem (oily residue, hissing), stop — that repair is for a licensed technician"],
        "time": "30–60 min",
        "cost": "$0–$40",
        "difficulty": "Moderate",
        "tools": ["Vacuum with brush attachment", "Screwdriver set", "Multimeter (optional)"],
        "parts": ["Start relay (if compressor won't start)", "Door gasket (if torn)"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before touching the compressor or relay", "Capacitors on some models hold a charge — do not probe them", "Never puncture refrigerant lines"],
        "mall": "coil cleaning brush",
    },
    {
        "field": "Appliances",
        "title": "Washer won't spin",
        "symptoms": ["Washer fills and agitates but never spins", "Clothes come out soaking wet", "Lid lock light blinks or never engages"],
        "diagnosis": ["Open and close the lid firmly — a bad lid switch or lock stops the spin", "Redistribute the load; a heavy unbalanced load aborts spin", "Check the drain hose for kinks and the pump filter for clogs", "On older top-loaders, inspect the drive belt underneath"],
        "diy_title": "Fix the lid switch, balance, and drain path",
        "diy_steps": ["Unplug the washer", "Redistribute or reduce the load and close the lid firmly", "Clear kinks from the drain hose and clean the pump filter (have towels ready)", "Test the lid switch with a multimeter; replace it if it shows no continuity when closed", "On belt-drive models, replace a loose or broken drive belt", "If the motor hums but nothing moves after these checks, call a technician"],
        "time": "30–60 min",
        "cost": "$0–$25",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Pliers", "Multimeter", "Towels and bucket"],
        "parts": ["Lid switch or lock assembly", "Drive belt (belt-drive models)"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before reaching into the machine", "Washers are heavy — get help when tilting", "Keep hands clear of the drum when testing"],
        "mall": "washing machine lid switch",
    },
    {
        "field": "Appliances",
        "title": "Dryer no heat",
        "symptoms": ["Dryer tumbles but clothes stay cold and damp", "Takes multiple cycles to dry", "No heat on any setting"],
        "diagnosis": ["Confirm it is really no-heat, not just slow drying", "Electric dryers: check both halves of the 240V breaker — one tripped half kills heat only", "Clean the lint filter and the full vent run to outside", "Test the thermal fuse and heating element for continuity", "Gas dryers: watch the igniter — no glow means igniter or flame sensor"],
        "diy_title": "Restore power, airflow, and the heat source",
        "diy_steps": ["Unplug the dryer (and shut gas off for gas models)", "Flip the double-pole breaker fully OFF then ON", "Clean the lint filter and vacuum the entire vent duct to the outside", "Remove the back panel and test the thermal fuse — replace if it shows no continuity", "Test the heating element; replace if broken (electric) or replace a dead igniter (gas)", "Reassemble, restore power/gas, and run a test load"],
        "time": "45–90 min",
        "cost": "$0–$40",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Multimeter", "Vacuum"],
        "parts": ["Thermal fuse", "Heating element or igniter"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before opening the cabinet; shut off gas for gas models", "A clogged vent is a fire hazard — clean it fully", "If you smell gas, leave and call the gas company"],
        "mall": "dryer thermal fuse",
    },
    {
        "field": "Appliances",
        "title": "Dishwasher not cleaning dishes",
        "symptoms": ["Dishes come out spotty or gritty", "Film or residue on glasses", "Spray arms barely move"],
        "diagnosis": ["Pull out and rinse the filter at the tub bottom — a clogged filter is the top cause", "Spin the spray arms by hand and poke clear clogged holes", "Run hot water at the sink first so the fill starts hot", "Check that tall items are not blocking the spray arms", "Confirm you are using fresh detergent, not old clumps"],
        "diy_title": "Clean the filter and spray arms, fix the hot fill",
        "diy_steps": ["Remove the bottom rack and twist out the filter; scrub it clean", "Remove spray arms and clear holes with a toothpick; rinse", "Run the kitchen faucet until hot before starting the dishwasher", "Reload so nothing blocks the spinning arms", "Run an empty hot cycle with a dishwasher cleaner", "If the water never gets hot, the heating element or thermostat needs a technician"],
        "time": "20–40 min",
        "cost": "$0–$10",
        "difficulty": "Easy",
        "tools": ["Toothpick or small brush", "Towel"],
        "parts": ["Dishwasher cleaner", "Fresh detergent"],
        "safety": "LOW",
        "warnings": ["Let the heating element cool before reaching into the tub"],
        "mall": "dishwasher cleaner",
    },
    {
        "field": "Appliances",
        "title": "Oven not heating",
        "symptoms": ["Oven stays cold on bake though the display works", "Bake element has a visible break or blister", "Gas oven: no glow from the igniter"],
        "diagnosis": ["Confirm the clock/timer is not in a delayed-start mode", "Electric: look at the bake element for breaks, blisters, or bright spots", "Gas: watch through the oven floor — a healthy igniter glows bright orange", "Test the element or igniter for continuity with a multimeter"],
        "diy_title": "Replace the failed bake element or igniter",
        "diy_steps": ["Cut power at the breaker (and shut gas off for gas models)", "Remove the element's mounting screws or the oven floor to reach the igniter", "Disconnect wires, noting positions, and install the identical replacement", "Reassemble, restore power/gas, and preheat to test", "If a new element still does not heat, the control board needs a technician"],
        "time": "30–60 min",
        "cost": "$20–$60",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Multimeter", "Work gloves"],
        "parts": ["Bake element (electric) or igniter (gas)"],
        "safety": "MEDIUM",
        "warnings": ["Breaker OFF before touching element terminals; gas OFF for gas ovens", "Elements are fragile — handle by the ends", "If you smell gas, stop and call the gas company"],
        "mall": "oven bake element",
    },
    {
        "field": "Appliances",
        "title": "Microwave not heating food",
        "symptoms": ["Microwave runs and the turntable spins but food stays cold", "Slight burning smell from inside", "Unit is over 8–10 years old"],
        "diagnosis": ["Confirm the door latches firmly on both sides — a bad interlock cuts the magnetron", "Listen for the deep hum of the magnetron engaging", "Check whether the unit trips the breaker under load", "Everything past the door switches involves lethal high voltage"],
        "diy_title": "Check the door interlock, then call a professional",
        "diy_steps": ["Unplug the microwave", "Inspect and clean the door latches and the door seal", "Replace a visibly broken door switch only if you can do so without touching the capacitor or transformer", "If the magnetron, capacitor, diode, or transformer is suspect, stop — the capacitor can hold a lethal charge even unplugged", "Have a qualified technician repair it, or replace the microwave"],
        "time": "15–30 min",
        "cost": "$0 (pro repair $100+)",
        "difficulty": "Hard",
        "tools": ["Screwdriver set", "Flashlight"],
        "parts": ["None DIY — technician parts only"],
        "safety": "HIGH",
        "warnings": ["The high-voltage capacitor can kill even with the unit unplugged", "Never remove the outer cover unless you are trained on microwave high voltage", "Do not run the microwave empty"],
        "mall": "countertop microwave",
    },
    {
        "field": "Appliances",
        "title": "Freezer icing up",
        "symptoms": ["Thick frost coats the walls and food", "Frost builds up within weeks of defrosting", "Door is hard to close or pops open"],
        "diagnosis": ["Inspect the door gasket for tears, gaps, or food debris", "Check that the door closes fully and nothing blocks it", "Listen for the evaporator fan running with the door switch pressed", "Frequent frost with a good seal points to a failed defrost heater, thermostat, or timer"],
        "diy_title": "Fix the seal and defrost fully",
        "diy_steps": ["Move food to coolers and unplug the freezer", "Let it defrost fully with towels in place — never chip ice with sharp tools", "Clean the door gasket and the sealing surface; replace a torn gasket", "Vacuum the condenser coils and confirm the unit is level", "Restart and monitor — if frost returns fast, the defrost system needs a technician"],
        "time": "2–4 hours (mostly waiting)",
        "cost": "$0–$30",
        "difficulty": "Easy",
        "tools": ["Towels", "Cooler", "Vacuum"],
        "parts": ["Door gasket (if torn)"],
        "safety": "MEDIUM",
        "warnings": ["Never chip ice with knives or screwdrivers — puncturing a refrigerant line is dangerous", "Unplug before cleaning near electrical parts", "Keep food safely cold during the defrost"],
        "mall": "freezer thermometer",
    },
    {
        "field": "Appliances",
        "title": "Washer shaking violently",
        "symptoms": ["Washer bangs or walks across the floor on spin", "Loud thumping that shakes the room", "Machine is new or was recently moved"],
        "diagnosis": ["Check the machine is level front-to-back and side-to-side", "On new front-loaders, confirm the shipping bolts were removed", "Run it empty — shaking empty means suspension, shaking only with clothes means balance", "Push down on the drum; weak bounce-back means worn suspension rods or springs"],
        "diy_title": "Level it, remove shipping bolts, fix the load",
        "diy_steps": ["Unplug the washer", "Remove any shipping bolts from the back (new front-loaders)", "Adjust the leveling feet until the machine is level and rock-solid", "Wash similar-weight items together and do not overload", "Replace worn suspension rods or springs if the drum sags or bounces freely", "If the inner tub itself is loose on the shaft, call a technician"],
        "time": "20–45 min",
        "cost": "$0–$50",
        "difficulty": "Moderate",
        "tools": ["Level", "Wrench", "Screwdriver set"],
        "parts": ["Suspension rods or springs (if worn)", "Anti-vibration pads (optional)"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before tipping or opening the machine", "Washers are heavy — get help when moving", "Running it violently unbalanced can break the machine"],
        "mall": "washer suspension rods",
    },
    {
        "field": "Appliances",
        "title": "Dryer squeaking",
        "symptoms": ["High-pitched squeak or squeal while tumbling", "Noise is rhythmic with drum rotation", "Squeak started gradually"],
        "diagnosis": ["Unplug and spin the drum by hand to locate the noise", "Worn drum support rollers are the most common cause", "Check the idler pulley and the belt for glazing or cracks", "On some models, worn front drum glides squeal against the drum"],
        "diy_title": "Replace the worn rollers, glides, or belt",
        "diy_steps": ["Unplug the dryer", "Remove the front panel and lift out the drum (note the belt routing)", "Replace drum support rollers and the idler pulley as a set", "Replace worn front glides and a glazed or cracked belt", "Reassemble, restore power, and run empty to confirm quiet operation"],
        "time": "60–90 min",
        "cost": "$15–$40",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Putty knife", "Work gloves"],
        "parts": ["Drum roller kit", "Drive belt (if worn)"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before opening the cabinet", "Drum edges can be sharp — wear gloves", "Photograph belt routing before removal"],
        "mall": "dryer repair kit",
    },
    {
        "field": "Appliances",
        "title": "Fridge leaking water",
        "symptoms": ["Puddle under or inside the fridge", "Water drips from the freezer into the fridge section", "Ice sheet on the freezer floor"],
        "diagnosis": ["Check the defrost drain at the back of the fridge section for clogs", "Inspect the ice-maker water line and its connections", "Confirm the fridge is level so water flows to the drain", "Look at the drain pan underneath for cracks or overflow"],
        "diy_title": "Clear the defrost drain and check water lines",
        "diy_steps": ["Unplug the fridge", "Find the defrost drain hole and flush it with warm water using a turkey baster", "Clear the drain tube at the back with a soft brush or pipe cleaner", "Tighten any dripping ice-maker line fittings and check the line for cracks", "Level the fridge slightly tilted back so the doors close on their own", "Plug back in and watch for a day"],
        "time": "20–40 min",
        "cost": "$0–$15",
        "difficulty": "Easy",
        "tools": ["Turkey baster", "Towels", "Level"],
        "parts": ["Ice-maker water line (if cracked)"],
        "safety": "LOW",
        "warnings": ["Unplug before reaching behind the unit", "Do not overtighten plastic water fittings"],
        "mall": "turkey baster",
    },
    {
        "field": "Appliances",
        "title": "Gas burner won't light",
        "symptoms": ["Burner clicks but never lights", "No clicking sound at all", "One burner dead while others work"],
        "diagnosis": ["Check that the burner cap sits flat and aligned", "Look for clogged burner ports and food debris", "Confirm the igniter sparks — no spark means igniter or spark module", "Verify other burners light, which rules out the gas supply"],
        "diy_title": "Clean and reseat the burner, then test the igniter",
        "diy_steps": ["Turn all burners OFF", "Remove the cap and grate; scrub the burner head and clear ports with a pin", "Reseat the cap perfectly flat and aligned", "Try lighting — if it clicks but will not light, you may light it manually with a long lighter as a temporary measure", "Replace a dead igniter or spark module with the power disconnected", "If you smell gas and the burner will not light, stop: ventilate, do not flip switches, and call the gas company"],
        "time": "15–30 min",
        "cost": "$0–$30",
        "difficulty": "Easy",
        "tools": ["Pin or needle", "Brush", "Screwdriver set"],
        "parts": ["Burner igniter or spark module (if dead)"],
        "safety": "HIGH",
        "warnings": ["If you smell gas, ventilate and leave — do not operate electrical switches", "Never let unburned gas accumulate while clicking repeatedly", "Disconnect power before replacing igniters"],
        "mall": "gas range igniter",
    },
    {
        "field": "Appliances",
        "title": "Range hood dead",
        "symptoms": ["Fan and light both dead", "Fan hums but blades do not spin", "Hood trips the breaker"],
        "diagnosis": ["Check the breaker and any GFCI feeding the hood", "Test the wall switch or hood buttons", "With power off, spin the fan by hand — seized means a dead motor", "Inspect the grease filter; a saturated filter can overheat and trip thermal protection"],
        "diy_title": "Restore power, clean, or replace the motor",
        "diy_steps": ["Turn OFF the breaker feeding the hood", "Remove and degrease the filter (soak in hot soapy water)", "Test the switch for continuity and replace if dead", "If the motor is seized, replace it with an identical motor", "Reconnect wiring exactly as before, restore power, and test fan and light"],
        "time": "30–60 min",
        "cost": "$0–$80",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Multimeter", "Degreaser"],
        "parts": ["Range hood filter", "Fan motor (if seized)"],
        "safety": "MEDIUM",
        "warnings": ["Breaker OFF and verify dead before opening the hood", "Grease buildup is a fire hazard — clean filters monthly"],
        "mall": "range hood filter",
    },
    {
        "field": "Appliances",
        "title": "Ice maker dead",
        "symptoms": ["No ice for days though the freezer is cold", "Ice cubes are tiny or hollow", "Water leaks at the back of the fridge"],
        "diagnosis": ["Confirm the freezer is at 0°F — too warm stops ice production", "Check that the ice-maker arm or switch is in the ON position", "Verify the water supply valve behind the fridge is fully open", "Look for a frozen fill tube or jammed cubes blocking the ejector"],
        "diy_title": "Restore water supply and clear jams",
        "diy_steps": ["Turn the ice maker OFF and remove any jammed cubes", "Confirm the saddle or supply valve behind the fridge is fully open", "Thaw a frozen fill tube with a hair dryer on low", "Check the inlet valve filter screen for sediment and clean it", "Turn the ice maker back on and wait 24 hours for the first full batch", "If the inlet valve will not open electrically, replace it"],
        "time": "20–40 min",
        "cost": "$0–$40",
        "difficulty": "Easy",
        "tools": ["Hair dryer", "Wrench", "Towels"],
        "parts": ["Water inlet valve (if dead)"],
        "safety": "LOW",
        "warnings": ["Unplug the fridge before replacing the inlet valve", "Place a shutoff valve within easy reach of the water line"],
        "mall": "ice maker kit",
    },
    {
        "field": "Appliances",
        "title": "Dishwasher leaking onto floor",
        "symptoms": ["Water pools in front of the dishwasher", "Leak only during certain cycles", "Suds overflowing the door"],
        "diagnosis": ["Check for over-sudsing — regular dish soap in a dishwasher foams over", "Inspect the door gasket for tears, food, or warping", "Look under the unit for drips from hose clamps or the pump", "Confirm the float switch moves freely and is not stuck"],
        "diy_title": "Stop the suds, seal the door, tighten connections",
        "diy_steps": ["Run a cancel/drain cycle and mop up the water", "If suds are the cause, run an empty rinse and switch to proper dishwasher detergent", "Clean the door gasket and replace it if torn or warped", "Turn off power and water, then tighten hose clamps underneath", "Free a stuck float switch so it can shut off the fill", "Run a test cycle and watch underneath with a flashlight"],
        "time": "25–50 min",
        "cost": "$0–$20",
        "difficulty": "Easy",
        "tools": ["Towels", "Flashlight", "Screwdriver set"],
        "parts": ["Door gasket (if torn)", "Dishwasher detergent"],
        "safety": "LOW",
        "warnings": ["Turn off power and water before working underneath", "Never use regular dish soap in a dishwasher"],
        "mall": "dishwasher door gasket",
    },
    {
        "field": "Appliances",
        "title": "Washer won't drain",
        "symptoms": ["Water stands in the tub after the cycle", "Drain cycle hums but water stays", "Error code for drain failure"],
        "diagnosis": ["Check the drain hose for kinks or clogs where it meets the standpipe", "On front-loaders, open the pump filter access and clear debris", "Listen during drain — silence suggests a dead pump, humming suggests a jam", "Confirm the standpipe is not sealed airtight around the hose"],
        "diy_title": "Clear the hose, filter, and pump",
        "diy_steps": ["Unplug the washer and bail out standing water", "Straighten kinks and detach the drain hose to flush out clogs", "Open the pump filter (towels ready) and remove coins, lint, and debris", "Check the pump impeller spins freely; replace the pump if it is dead", "Reattach everything, plug in, and run a drain-and-spin test"],
        "time": "30–60 min",
        "cost": "$0–$40",
        "difficulty": "Moderate",
        "tools": ["Bucket and towels", "Pliers", "Screwdriver set"],
        "parts": ["Drain pump (if dead)", "Drain hose (if split)"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before opening the pump filter", "Standing washer water can be dirty — wear gloves", "Do not seal the hose airtight into the standpipe"],
        "mall": "washing machine pump",
    },
    {
        "field": "Appliances",
        "title": "Dryer takes too long to dry",
        "symptoms": ["Clothes still damp after a full cycle", "Dryer exterior feels very hot", "Laundry room gets humid during drying"],
        "diagnosis": ["Clean the lint filter — then check the vent run all the way outside", "Go outside and confirm strong airflow from the vent hood while running", "Feel for crushed or overly long flexible duct behind the dryer", "A vent clogged with lint is both the likely cause and a fire hazard"],
        "diy_title": "Clean the full vent path to restore airflow",
        "diy_steps": ["Unplug the dryer and pull it from the wall", "Vacuum the lint filter housing and the duct behind the dryer", "Disconnect the vent and brush/vacuum the entire run to the outside hood", "Replace crushed vinyl duct with smooth rigid or semi-rigid metal duct", "Clean the outside vent hood flap so it opens freely", "Reconnect, push back, and time a test load"],
        "time": "45–75 min",
        "cost": "$0–$30",
        "difficulty": "Moderate",
        "tools": ["Vacuum", "Vent brush kit", "Screwdriver set"],
        "parts": ["Metal vent duct (if replacing vinyl)"],
        "safety": "MEDIUM",
        "warnings": ["Unplug before disconnecting the vent", "Lint-clogged vents cause thousands of fires — clean yearly", "Never use vinyl duct for a dryer vent"],
        "mall": "dryer vent cleaning kit",
    },
    {
        "field": "Heating & Cooling",
        "title": "AC blowing warm air",
        "symptoms": ["Vents blow room-temperature or warm air", "Thermostat set to cool but house will not cool", "Ice on the indoor coil or refrigerant lines"],
        "diagnosis": ["Confirm the thermostat is on COOL and the setpoint is below room temp", "Check the air filter — a clogged filter can freeze the coil", "Verify the outdoor unit is running and clear of debris", "Look for ice on the indoor coil or the larger copper line", "If iced, turn cooling OFF and run the fan to thaw before further checks"],
        "diy_title": "Restore settings and airflow, then thaw",
        "diy_steps": ["Set the thermostat to COOL, AUTO fan, and a setpoint below room temperature", "Replace a dirty air filter", "Clear grass and debris two feet around the outdoor unit and gently rinse its coils", "If iced up, switch to FAN ONLY for several hours to thaw completely", "Restart cooling — if warm air returns or ice reforms, stop: low refrigerant needs a licensed technician"],
        "time": "30–60 min",
        "cost": "$0–$20",
        "difficulty": "Easy",
        "tools": ["Thermometer", "Garden hose"],
        "parts": ["HVAC air filter"],
        "safety": "MEDIUM",
        "warnings": ["Turn power off at the disconnect before rinsing the outdoor unit", "Never add refrigerant yourself — it requires a license", "Do not run a frozen system; thaw it first"],
        "mall": "hvac air filter",
    },
    {
        "field": "Heating & Cooling",
        "title": "Furnace won't turn on",
        "symptoms": ["No heat and no sound from the furnace", "Thermostat calls for heat but nothing happens", "Furnace worked yesterday"],
        "diagnosis": ["Check the thermostat is on HEAT with a setpoint above room temp", "Look for the furnace power switch (often a wall switch near the unit) and the breaker", "Replace a dirty filter — some furnaces lock out on overheating", "Check the blinking error code on the control board through the sight glass", "For gas: confirm the gas valve is open and the pilot or igniter is working"],
        "diy_title": "Check power, filter, and thermostat basics",
        "diy_steps": ["Set the thermostat to HEAT and raise the setpoint", "Confirm the furnace switch is ON and reset the breaker", "Replace a clogged air filter", "Read the error-code blink pattern and look it up in the furnace manual", "For standing-pilot models, relight the pilot per the label instructions", "If the inducer or blower never starts, or gas is involved beyond the pilot, call a technician"],
        "time": "20–40 min",
        "cost": "$0–$20",
        "difficulty": "Easy",
        "tools": ["Flashlight", "Thermometer"],
        "parts": ["Furnace air filter"],
        "safety": "HIGH",
        "warnings": ["If you smell gas, leave the house and call the gas company", "Do not bypass safety switches or the error-code lockout", "Carbon monoxide detectors must be working before heating season"],
        "mall": "furnace air filter",
    },
    {
        "field": "Heating & Cooling",
        "title": "Thermostat dead",
        "symptoms": ["Thermostat screen is blank", "No response to button presses", "System will not start from the thermostat"],
        "diagnosis": ["Replace the batteries — the most common cause", "Check the breaker for the furnace/air handler", "Look for a tripped float switch on the condensate drain (cuts power to the thermostat)", "Inspect for loose wires at the thermostat base"],
        "diy_title": "Replace batteries and restore low-voltage power",
        "diy_steps": ["Slide off the thermostat face and install fresh batteries", "Reset the HVAC breaker fully OFF then ON", "Check the condensate drain float switch — clear the drain and reset it", "Tighten any loose low-voltage wires at the thermostat base", "If the screen stays dead with good batteries and power, replace the thermostat"],
        "time": "10–25 min",
        "cost": "$2–$60",
        "difficulty": "Easy",
        "tools": ["Screwdriver set", "Multimeter (optional)"],
        "parts": ["AA or AAA batteries", "Thermostat (if dead)"],
        "safety": "LOW",
        "warnings": ["Turn off HVAC power before touching wires", "Photograph wire labels before disconnecting"],
        "mall": "programmable thermostat",
    },
    {
        "field": "Heating & Cooling",
        "title": "AC leaking water inside",
        "symptoms": ["Water drips from the indoor unit or ceiling vent", "Puddle near the air handler", "Musty smell when the AC runs"],
        "diagnosis": ["Check the condensate drain line for clogs — the top cause", "Look at the drain pan for cracks or overflow", "A frozen coil from a dirty filter melts and overwhelms the drain", "Confirm the drain line slopes downward to its exit"],
        "diy_title": "Clear the condensate drain",
        "diy_steps": ["Turn the AC OFF at the thermostat", "Find the drain line exit outside and attach a wet/dry vacuum for two minutes", "Pour a cup of white vinegar into the drain access tee to kill algae", "Replace a cracked drain pan", "Replace a dirty filter and let any ice thaw fully before restarting", "If leaking continues with a clear drain, call a technician"],
        "time": "20–40 min",
        "cost": "$0–$10",
        "difficulty": "Easy",
        "tools": ["Wet/dry vacuum", "Towels", "Funnel"],
        "parts": ["White vinegar"],
        "safety": "LOW",
        "warnings": ["Turn the system off before working on the drain", "Water near electrical components — dry the area first"],
        "mall": "wet dry vacuum",
    },
    {
        "field": "Heating & Cooling",
        "title": "Furnace short cycling",
        "symptoms": ["Furnace starts then shuts off within minutes", "House never reaches the set temperature", "Burners light then drop out repeatedly"],
        "diagnosis": ["Replace a dirty filter — restricted airflow overheats the furnace and trips the limit", "Check that supply vents are open and returns are unblocked", "Read the error-code blink pattern on the control board", "A dirty flame sensor causes the burners to light then shut off", "Oversized furnaces or a bad thermostat location also cause short cycling"],
        "diy_title": "Restore airflow and clean the flame sensor",
        "diy_steps": ["Turn power OFF at the furnace switch", "Replace the air filter and open all supply vents", "Remove the flame sensor, clean it gently with fine steel wool, and reinstall", "Restore power and observe a full heating cycle", "If short cycling continues or the error code points to the limit switch or gas valve, call a technician"],
        "time": "30–50 min",
        "cost": "$0–$15",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Fine steel wool"],
        "parts": ["Furnace air filter", "Flame sensor (if cleaning fails)"],
        "safety": "HIGH",
        "warnings": ["Turn power off before opening the furnace", "Do not bypass the high-limit switch — it prevents overheating", "If you smell gas, leave and call the gas company"],
        "mall": "furnace flame sensor",
    },
    {
        "field": "Heating & Cooling",
        "title": "Weak airflow from vents",
        "symptoms": ["Barely any air comes from one or more vents", "Some rooms never get comfortable", "System runs constantly"],
        "diagnosis": ["Check the air filter first", "Walk room to room confirming supply vents and dampers are open", "Feel for air leaking from disconnected ducts in the attic or basement", "Check that return grilles are not blocked by furniture", "Look for crushed flexible duct"],
        "diy_title": "Open the path and seal duct leaks",
        "diy_steps": ["Replace a dirty air filter", "Open all supply vents and dampers; move furniture off return grilles", "Inspect accessible ducts and seal disconnected joints with mastic or foil tape", "Straighten crushed flexible duct runs", "If airflow is still weak everywhere, the blower or duct design needs a technician"],
        "time": "30–60 min",
        "cost": "$0–$25",
        "difficulty": "Easy",
        "tools": ["Flashlight", "Foil tape"],
        "parts": ["HVAC air filter", "Duct mastic or foil tape"],
        "safety": "LOW",
        "warnings": ["Use a stable ladder in attics; watch for exposed nails", "Turn the system off before reaching into ducts"],
        "mall": "foil tape",
    },
    {
        "field": "Heating & Cooling",
        "title": "Heat pump icing up",
        "symptoms": ["Thick ice coats the outdoor unit in winter", "Ice does not clear after the defrost cycle", "Heating output drops"],
        "diagnosis": ["A thin frost that clears in defrost mode is normal — thick persistent ice is not", "Check that the outdoor unit has airflow clearance and the filter is clean", "Confirm the unit actually enters defrost (steam and dripping water are normal signs)", "Ice only on part of the coil suggests low refrigerant or a bad defrost control"],
        "diy_title": "Restore airflow and verify the defrost cycle",
        "diy_steps": ["Clear snow, ice, and debris from around the outdoor unit", "Replace a dirty indoor air filter", "Run the system and watch for a defrost cycle within 90 minutes of icing", "Gently rinse light ice with water — never chip it off the coil", "If ice persists or only part of the coil frosts, call a technician — do not add refrigerant yourself"],
        "time": "20–40 min",
        "cost": "$0–$15",
        "difficulty": "Easy",
        "tools": ["Garden hose", "Broom"],
        "parts": ["HVAC air filter"],
        "safety": "MEDIUM",
        "warnings": ["Turn power off at the disconnect before clearing ice by hand", "Never chip ice off coils — fins and refrigerant lines damage easily", "Refrigerant work requires a licensed technician"],
        "mall": "coil cleaner spray",
    },
    {
        "field": "Heating & Cooling",
        "title": "Noisy AC outdoor unit",
        "symptoms": ["Rattling, buzzing, or squealing from the condenser", "Noise started suddenly", "Unit still cools"],
        "diagnosis": ["Turn power off and check for loose top grille or side panel screws", "Look for sticks, leaves, or debris inside the unit", "A buzzing contactor or failing capacitor can hum loudly", "Squealing on startup points to the fan motor bearings"],
        "diy_title": "Tighten panels and clear debris",
        "diy_steps": ["Turn power OFF at the outdoor disconnect", "Remove the top grille and clear all debris from inside", "Tighten every panel and grille screw", "Straighten bent fan blades gently if accessible", "Restore power — if buzzing, humming, or squealing persists, the contactor, capacitor, or fan motor needs a technician"],
        "time": "20–35 min",
        "cost": "$0",
        "difficulty": "Easy",
        "tools": ["Screwdriver set", "Work gloves"],
        "parts": ["None DIY"],
        "safety": "MEDIUM",
        "warnings": ["Lock the disconnect OFF before reaching inside", "Capacitors can hold a charge — do not touch them", "Keep hands clear when power is restored for testing"],
        "mall": "condenser coil cleaner",
    },
    {
        "field": "Heating & Cooling",
        "title": "Pilot light won't stay lit",
        "symptoms": ["Pilot lights but goes out when the button is released", "Pilot will not light at all", "Furnace or water heater will not fire"],
        "diagnosis": ["A weak or wavering pilot flame suggests a dirty pilot orifice", "If it dies on release, the thermocouple is the prime suspect", "Check for drafts blowing the pilot out", "Confirm the gas valve is fully open"],
        "diy_title": "Clean the pilot and thermocouple",
        "diy_steps": ["Turn the gas valve to OFF and wait five minutes", "Relight the pilot exactly per the label instructions", "If it will not stay lit, turn gas OFF and clean the thermocouple tip with fine steel wool", "Confirm the thermocouple tip sits fully in the pilot flame", "Replace the thermocouple if cleaning fails — they are inexpensive and universal", "If you smell gas at any point, stop, ventilate, and call the gas company"],
        "time": "20–40 min",
        "cost": "$0–$12",
        "difficulty": "Moderate",
        "tools": ["Fine steel wool", "Wrench", "Long lighter"],
        "parts": ["Universal thermocouple"],
        "safety": "HIGH",
        "warnings": ["Wait five full minutes for gas to clear before relighting", "If you smell gas, do not light anything — leave and call the gas company", "Never bypass the thermocouple safety"],
        "mall": "universal thermocouple",
    },
    {
        "field": "Heating & Cooling",
        "title": "Clogged condensate drain",
        "symptoms": ["Water backing up at the indoor unit", "AC shuts off unexpectedly (float switch tripped)", "Algae or slime visible at the drain"],
        "diagnosis": ["Find the drain line exit outside — no drip while running means a clog", "Check the float switch; a tripped switch confirms backup", "Look for sagging line sections that trap water", "Locate the access tee near the air handler for cleaning"],
        "diy_title": "Vacuum and flush the drain line",
        "diy_steps": ["Turn the AC OFF", "Attach a wet/dry vacuum to the outside drain exit for two minutes", "Pour a cup of white vinegar into the access tee", "Reset the float switch", "Restart and confirm steady dripping outside while cooling", "Add drain tablets monthly in cooling season to prevent regrowth"],
        "time": "15–30 min",
        "cost": "$0–$10",
        "difficulty": "Easy",
        "tools": ["Wet/dry vacuum", "Funnel"],
        "parts": ["White vinegar", "Condensate drain tablets"],
        "safety": "LOW",
        "warnings": ["Turn the system off before servicing the drain", "Do not use bleach — it can damage the drain pan and harm plants at the exit"],
        "mall": "condensate drain tablets",
    },
    {
        "field": "Heating & Cooling",
        "title": "Rooms unevenly heated or cooled",
        "symptoms": ["Some rooms are much hotter or colder than others", "Upstairs is always warmer than downstairs", "One room never gets comfortable"],
        "diagnosis": ["Check that vents in problem rooms are fully open and unblocked", "Feel for air leaks around windows and doors in those rooms", "Look for closed balancing dampers in the ductwork", "Note sun exposure — south and west rooms gain more heat", "Check attic insulation depth over cold rooms"],
        "diy_title": "Balance vents and seal the easy leaks",
        "diy_steps": ["Open all supply vents and confirm dampers in the ducts are open", "Partially close vents in the most comfortable rooms to push air to problem rooms", "Seal window and door leaks in uncomfortable rooms with weatherstripping", "Add vent deflectors to direct air where it is needed", "If imbalance persists, have a technician measure airflow and check duct sizing"],
        "time": "30–60 min",
        "cost": "$0–$30",
        "difficulty": "Easy",
        "tools": ["Screwdriver set", "Thermometer"],
        "parts": ["Vent deflectors", "Weatherstripping"],
        "safety": "LOW",
        "warnings": ["Never fully close more than a few vents — restricted airflow strains the system"],
        "mall": "vent deflectors",
    },
    {
        "field": "Heating & Cooling",
        "title": "AC won't stop running",
        "symptoms": ["AC runs for hours without cycling off", "House reaches setpoint but the unit keeps going", "Electric bill spikes"],
        "diagnosis": ["Check the thermostat fan setting — ON runs the blower constantly; use AUTO", "Confirm the setpoint is realistic for the outdoor heat", "A dirty filter or coil reduces capacity so the unit never catches up", "Low refrigerant or an aging unit also causes marathon run times"],
        "diy_title": "Fix the fan setting and restore capacity",
        "diy_steps": ["Set the thermostat fan to AUTO, not ON", "Replace a dirty air filter", "Clear debris from the outdoor unit and gently rinse its coils", "Close blinds on sun-facing windows to cut the heat load", "If it still never cycles off on a mild day, low refrigerant or sizing is likely — call a technician"],
        "time": "15–30 min",
        "cost": "$0–$15",
        "difficulty": "Easy",
        "tools": ["Garden hose", "Thermometer"],
        "parts": ["HVAC air filter"],
        "safety": "LOW",
        "warnings": ["Turn power off at the disconnect before rinsing the outdoor unit"],
        "mall": "smart thermostat",
    },
    {
        "field": "Heating & Cooling",
        "title": "Furnace blowing cold air",
        "symptoms": ["Vents blow cold or lukewarm air in heating mode", "Furnace runs but the house cools down", "Burners never seem to light"],
        "diagnosis": ["Confirm the thermostat is on HEAT with fan on AUTO", "Check the filter and that the pilot or igniter is working", "A tripped high-limit from a clogged filter can leave the blower running cold", "Watch through the sight glass — no flame with the blower running is the key clue", "A cracked heat exchanger can also cause this and leaks carbon monoxide"],
        "diy_title": "Restore the flame, then check for danger signs",
        "diy_steps": ["Set the thermostat to HEAT, fan AUTO, and replace a dirty filter", "Reset the furnace power once and watch for the burners to light", "Clean the flame sensor if burners light then drop out", "Install fresh batteries in carbon monoxide detectors and confirm they work", "If burners never light, you smell odd odors, or CO alarms sound, shut it down and call a technician immediately"],
        "time": "20–40 min",
        "cost": "$0–$15",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Fine steel wool"],
        "parts": ["Furnace air filter"],
        "safety": "HIGH",
        "warnings": ["Working CO detectors are mandatory — test them now", "A cracked heat exchanger leaks carbon monoxide: soot, odd smells, or alarms mean shut down and call a pro", "If you smell gas, leave and call the gas company"],
        "mall": "carbon monoxide detector",
    },
    {
        "field": "Heating & Cooling",
        "title": "Flame sensor dirty",
        "symptoms": ["Burners light then shut off after a few seconds", "Furnace tries to start repeatedly", "Error code for flame failure"],
        "diagnosis": ["Burners lighting then dropping out is the classic dirty-flame-sensor pattern", "Read the error-code blink pattern to confirm flame failure", "Rule out a clogged filter causing limit trips instead", "Inspect the sensor rod for white or gray oxidation coating"],
        "diy_title": "Clean the flame sensor rod",
        "diy_steps": ["Turn power OFF at the furnace switch and shut the gas valve", "Remove the single screw holding the flame sensor and slide it out", "Clean the rod gently with fine steel wool until the metal shines — do not use sandpaper", "Reinstall, restore gas and power, and watch a full heating cycle", "If burners still drop out, replace the sensor with an identical part"],
        "time": "20–30 min",
        "cost": "$0–$20",
        "difficulty": "Moderate",
        "tools": ["Screwdriver set", "Fine steel wool"],
        "parts": ["Flame sensor (if cleaning fails)"],
        "safety": "HIGH",
        "warnings": ["Turn off power and gas before removing the sensor", "Never bypass the flame sensor — it proves the burners actually lit", "If you smell gas, leave and call the gas company"],
        "mall": "furnace flame sensor",
    },
    {
        "field": "Automotive",
        "title": "Car won't start — rapid clicking",
        "symptoms": ["Fast clicking when you turn the key or push start", "Dashboard lights flicker or go dim", "Radio and lights work weakly or not at all"],
        "diagnosis": ["Rapid clicking almost always means a weak battery", "Check terminals for white or green corrosion", "Try the headlights — dim or dead confirms low voltage", "If a jump start works, the battery or charging system is the issue"],
        "diy_title": "Clean the terminals and jump-start safely",
        "diy_steps": ["Put the car in park, turn everything off, and set the parking brake", "Clean corrosion from terminals with a wire brush", "Connect jumper cables: red to dead positive, red to good positive, black to good negative, black to bare metal on the dead car", "Start the good car, wait two minutes, then start the dead car", "Remove cables in reverse order and drive at least 20 minutes to recharge", "Have the battery and alternator tested — replace a battery older than 4–5 years"],
        "time": "15–30 min",
        "cost": "$0–$200",
        "difficulty": "Easy",
        "tools": ["Jumper cables or jump starter", "Wire brush", "Wrench"],
        "parts": ["Car battery (if it fails testing)"],
        "safety": "MEDIUM",
        "warnings": ["Batteries can emit explosive hydrogen — no sparks or flames nearby", "Connect cables in the exact order given", "Battery acid burns skin and eyes — wear protection"],
        "mall": "portable jump starter",
    },
    {
        "field": "Automotive",
        "title": "Dead battery — slow crank or no crank",
        "symptoms": ["Engine cranks very slowly or not at all", "Single click or silence when starting", "Interior lights are dim or out"],
        "diagnosis": ["Check battery age — most last 3–5 years", "Test voltage: below 12.4V resting means recharge or replace", "With the engine running, 13.5–14.5V means the alternator charges", "Look for parasitic drains like a trunk light stuck on"],
        "diy_title": "Recharge or replace the battery",
        "diy_steps": ["Turn everything off and disconnect the negative cable first", "Remove the hold-down and lift the battery out (they are heavy)", "Clean the tray and cable ends", "Install the new battery: positive cable first, then negative", "Secure the hold-down and confirm the car starts", "Return the old battery to a parts store for recycling"],
        "time": "20–40 min",
        "cost": "$100–$250",
        "difficulty": "Easy",
        "tools": ["Wrench set", "Battery terminal cleaner"],
        "parts": ["Correct group-size car battery"],
        "safety": "MEDIUM",
        "warnings": ["Disconnect negative first, reconnect it last", "Batteries are heavy — lift with your legs", "Never short the terminals with tools"],
        "mall": "car battery",
    },
    {
        "field": "Automotive",
        "title": "Flat tire",
        "symptoms": ["Tire is visibly flat or the TPMS warns", "Thumping noise while driving", "Car pulls toward the flat side"],
        "diagnosis": ["Pull fully off the road onto level, solid ground", "Check the spare's pressure before you need it", "Look for the puncture — a nail in the tread may be repairable later", "Sidewall damage means the tire is done"],
        "diy_title": "Swap on the spare safely",
        "diy_steps": ["Park on level ground, set the parking brake, and chock a wheel", "Loosen the lug nuts slightly before jacking", "Jack at the marked jack point until the tire clears the ground", "Remove lugs, mount the spare, and hand-tighten lugs in a star pattern", "Lower the car and tighten lugs firmly in the star pattern", "Drive gently to a shop — most spares are limited to 50 mph", "Torque the lugs to spec as soon as possible"],
        "time": "20–40 min",
        "cost": "$0",
        "difficulty": "Moderate",
        "tools": ["Jack", "Lug wrench", "Owner's manual", "Wheel chock"],
        "parts": ["None — spare tire"],
        "safety": "MEDIUM",
        "warnings": ["Never get under a car supported only by a jack", "Tighten lugs in a star pattern, not in a circle", "Respect the spare's speed and distance limits"],
        "mall": "torque wrench",
    },
    {
        "field": "Automotive",
        "title": "Squeaky brakes",
        "symptoms": ["High-pitched squeal when braking", "Squeal stops when you press harder", "Noise is worse in the morning"],
        "diagnosis": ["Light morning squeal that fades is usually harmless surface rust", "Constant squeal signals the wear indicators touching the rotor", "Check pad thickness through the wheel — less than 3mm means replace soon", "Look for a glazed rotor surface or debris caught in the caliper"],
        "diy_title": "Inspect pads and replace when worn",
        "diy_steps": ["Park on level ground, chock wheels, and loosen lugs", "Lift with a jack and secure on jack stands", "Remove the wheel and measure pad thickness", "Replace pads (and rotors if scored), cleaning and lubricating caliper slides", "Pump the brake pedal before driving to seat the pads", "Bed new pads with several moderate stops from 35 mph"],
        "time": "60–120 min per axle",
        "cost": "$30–$100",
        "difficulty": "Moderate",
        "tools": ["Jack and jack stands", "Lug wrench", "C-clamp or caliper tool", "Brake cleaner"],
        "parts": ["Brake pads", "Rotors (if scored)"],
        "safety": "MEDIUM",
        "warnings": ["Support the car on jack stands — never trust a jack alone", "Avoid breathing brake dust", "Pump the brakes before driving or the pedal will go to the floor"],
        "mall": "brake pads",
    },
    {
        "field": "Automotive",
        "title": "Check engine light on",
        "symptoms": ["Steady check-engine light on the dash", "Flashing check-engine light", "Car runs normally despite the light"],
        "diagnosis": ["A flashing light means active misfire — reduce speed and get service promptly", "Tighten the gas cap — a loose cap is a classic cause", "Read the code with an OBD2 scanner (many parts stores read them free)", "Note the exact code before clearing anything"],
        "diy_title": "Read the code and fix the simple causes",
        "diy_steps": ["Tighten the gas cap until it clicks and drive a few trips to see if the light clears", "Plug in an OBD2 scanner and record the code", "Look up the code — common DIY fixes include gas cap, air filter, and spark plugs", "Fix the indicated simple cause and clear the code", "If the light returns or flashes, get professional diagnosis — driving on a flashing light damages the catalytic converter"],
        "time": "10–30 min",
        "cost": "$0–$30",
        "difficulty": "Easy",
        "tools": ["OBD2 scanner", "Owner's manual"],
        "parts": ["Gas cap (if faulty)"],
        "safety": "LOW",
        "warnings": ["A flashing check-engine light means pull over safely and get service", "Do not ignore codes related to overheating or oil pressure"],
        "mall": "obd2 code reader",
    },
    {
        "field": "Automotive",
        "title": "Engine overheating",
        "symptoms": ["Temperature gauge in the red", "Steam from under the hood", "Warning light or message for coolant temperature"],
        "diagnosis": ["Pull over immediately and shut the engine off", "Never open the radiator cap while hot", "Once fully cool, check the coolant level in the reservoir", "Look for visible leaks, a broken belt, or a fan that never runs"],
        "diy_title": "Cool down safely and find the leak",
        "diy_steps": ["Pull over, shut off the engine, and pop the hood to vent heat — do not touch anything", "Wait at least 30–45 minutes until the engine is cool to the touch", "Check the coolant reservoir and radiator (cap off only when cool); top up with the correct coolant", "Look for leaks, split hoses, or a stuck thermostat", "Drive only short distances to a shop, watching the gauge — or call a tow", "If overheating repeats, the thermostat, water pump, or head gasket needs a pro"],
        "time": "45–90 min",
        "cost": "$15–$40",
        "difficulty": "Moderate",
        "tools": ["Correct engine coolant", "Funnel", "Rags"],
        "parts": ["Coolant", "Thermostat or hose (if failed)"],
        "safety": "HIGH",
        "warnings": ["NEVER open a hot radiator cap — scalding steam causes severe burns", "Driving while overheated can destroy the engine", "Keep coolant away from pets — it is poisonous"],
        "mall": "engine coolant",
    },
    {
        "field": "Automotive",
        "title": "Headlight out",
        "symptoms": ["One headlight dark while the other works", "High beams work but low beams do not (or reverse)", "Dashboard bulb-out warning"],
        "diagnosis": ["Swap bulbs side to side to confirm the bulb is the problem", "Check the headlight fuse if both sides are out", "Look for moisture inside the lens or a melted connector", "Confirm the bulb type in the owner's manual before buying"],
        "diy_title": "Replace the headlight bulb",
        "diy_steps": ["Turn the lights off and let the bulb cool", "Open the hood and reach or remove the cover behind the headlight", "Unplug the connector and release the bulb retainer", "Install the new bulb without touching the glass — skin oil shortens halogen life", "Reconnect, test both beams, and check headlight aim"],
        "time": "10–25 min",
        "cost": "$10–$30",
        "difficulty": "Easy",
        "tools": ["Gloves", "Screwdriver set (some models)"],
        "parts": ["Correct headlight bulb"],
        "safety": "LOW",
        "warnings": ["Do not touch halogen bulb glass with bare fingers", "Let bulbs cool before handling"],
        "mall": "headlight bulb",
    },
    {
        "field": "Automotive",
        "title": "Wipers streaking",
        "symptoms": ["Streaks or unwiped bands across the windshield", "Chattering or skipping blades", "Blades are cracked or torn"],
        "diagnosis": ["Lift the blades and feel the rubber edge for nicks or hardening", "Clean the blades and windshield — grime causes many streaks", "Check that the wiper arm presses the blade flat to the glass", "Note the blade lengths — they often differ side to side"],
        "diy_title": "Clean or replace the wiper blades",
        "diy_steps": ["Lift the wiper arms and wipe the rubber edge with a damp cloth", "Clean the windshield thoroughly with glass cleaner", "If streaks persist, unhook the old blades and note their lengths", "Clip on the new blades until they click", "Test with washer fluid and confirm full, quiet sweeps"],
        "time": "10–15 min",
        "cost": "$10–$30",
        "difficulty": "Easy",
        "tools": ["Glass cleaner", "Cloth"],
        "parts": ["Wiper blades (correct lengths)"],
        "safety": "LOW",
        "warnings": ["Do not let a bare wiper arm snap back onto the glass — it can crack the windshield"],
        "mall": "windshield wiper blades",
    },
    {
        "field": "Automotive",
        "title": "Car AC not cold",
        "symptoms": ["Vents blow warm or only slightly cool air", "AC was cold last summer", "Compressor clutch never engages"],
        "diagnosis": ["With AC on max, watch the compressor clutch — no engagement suggests electrical or low pressure", "Check the cabin air filter — a clogged filter kills airflow", "Look for debris blocking the condenser in front of the radiator", "Refrigerant level requires gauges and a license to service"],
        "diy_title": "Restore airflow and check the basics",
        "diy_steps": ["Replace a dirty cabin air filter", "Clear leaves and debris from the condenser", "Confirm the compressor clutch engages with AC on max", "Check the AC fuse and relay if the clutch never engages", "If pressures are the issue, stop — refrigerant service requires a licensed technician"],
        "time": "20–40 min",
        "cost": "$10–$30",
        "difficulty": "Easy",
        "tools": ["Screwdriver set", "Flashlight"],
        "parts": ["Cabin air filter"],
        "safety": "MEDIUM",
        "warnings": ["Never vent refrigerant to the air — it is illegal and harmful", "Keep hands clear of the running engine and fans", "Refrigerant cans with sealant can damage the system"],
        "mall": "cabin air filter",
    },
    {
        "field": "Automotive",
        "title": "Key fob dead",
        "symptoms": ["Buttons do nothing; car will not unlock remotely", "Push-button start says key not detected", "Fob worked yesterday"],
        "diagnosis": ["Replace the coin battery first — the overwhelmingly common cause", "Check the battery orientation when installing", "Try the mechanical key hidden inside the fob", "Hold the dead fob against the start button — most cars have a backup reader"],
        "diy_title": "Replace the coin battery",
        "diy_steps": ["Slide out the mechanical key and pry the fob open at the seam", "Note the battery type (often CR2032) and orientation", "Install the fresh battery positive-side up", "Snap the fob closed and test every button", "If it still fails, the fob may need dealer reprogramming"],
        "time": "5–10 min",
        "cost": "$3–$8",
        "difficulty": "Easy",
        "tools": ["Small flat screwdriver", "Coin"],
        "parts": ["CR2032 battery (or as marked)"],
        "safety": "LOW",
        "warnings": ["Keep coin batteries away from children and pets"],
        "mall": "cr2032 battery",
    },
    {
        "field": "Automotive",
        "title": "Car pulling to one side",
        "symptoms": ["Car drifts left or right on a straight road", "Steering wheel off-center", "Uneven tire wear"],
        "diagnosis": ["Check all tire pressures cold against the door-jamb sticker", "Look for uneven wear patterns — feathering or one-sided wear", "Test on a flat road — road crown can mimic a pull", "Rotate tires and see if the pull changes direction (tire-caused)"],
        "diy_title": "Fix pressure and wear, then align if needed",
        "diy_steps": ["Inflate all tires (including the spare) to the door-jamb spec when cold", "Inspect tread for uneven wear and rotate tires if due", "Test drive on a flat, straight road", "If the pull persists with good tires and pressure, get a professional alignment", "Ask the shop for a before/after printout of the alignment angles"],
        "time": "15–30 min",
        "cost": "$0–$120",
        "difficulty": "Easy",
        "tools": ["Tire pressure gauge", "Air compressor"],
        "parts": ["None DIY"],
        "safety": "LOW",
        "warnings": ["Check pressure when tires are cold for accurate readings", "Severe pulling can be a stuck brake caliper — feel for a hot wheel after driving"],
        "mall": "tire pressure gauge",
    },
    {
        "field": "Automotive",
        "title": "Grinding when shifting gears",
        "symptoms": ["Grinding noise shifting into one or more gears", "Hard to get into gear at a stop", "Clutch pedal feels different than usual"],
        "diagnosis": ["Check clutch fluid level if the car has a hydraulic clutch", "Note whether grinding happens in all gears or just one (one gear suggests worn synchros)", "Test with the engine off — smooth shifting parked points to clutch drag", "Look for a misadjusted clutch cable on older cars"],
        "diy_title": "Check fluids and adjustment, then see a specialist",
        "diy_steps": ["Check and top up clutch/brake fluid to the marked line", "Adjust a cable clutch per the manual if equipped", "Avoid forcing gears — double-clutch gently as a temporary measure", "If grinding persists, stop DIY here: synchros and clutches need a transmission specialist", "Get a diagnosis before driving far — grinding wears expensive parts fast"],
        "time": "15–30 min",
        "cost": "$0–$15",
        "difficulty": "Moderate",
        "tools": ["Owner's manual", "Flashlight"],
        "parts": ["Clutch/brake fluid (if low)"],
        "safety": "MEDIUM",
        "warnings": ["Do not keep driving on grinding gears — damage multiplies fast", "Transmission work is heavy and complex; leave internals to a pro"],
        "mall": "manual transmission fluid",
    },
    {
        "field": "Automotive",
        "title": "Washer fluid not spraying",
        "symptoms": ["No spray when you pull the stalk", "Weak dribble from one nozzle", "Pump makes no sound"],
        "diagnosis": ["Check the reservoir level first", "Listen for the pump humming — silence suggests fuse or dead pump", "Clear clogged nozzles with a pin", "Trace the hose for disconnections or kinks"],
        "diy_title": "Refill, unclog, and reconnect",
        "diy_steps": ["Fill the reservoir with proper washer fluid", "Clear each nozzle with a pin and wipe away wax buildup", "Check the washer fuse and replace if blown", "Reconnect any loose hose under the hood", "Listen for the pump — if it hums but nothing sprays, the line is still blocked; if silent with a good fuse, replace the pump"],
        "time": "10–25 min",
        "cost": "$3–$25",
        "difficulty": "Easy",
        "tools": ["Pin or needle", "Funnel"],
        "parts": ["Windshield washer fluid", "Washer pump (if dead)"],
        "safety": "LOW",
        "warnings": ["Do not use plain water in freezing weather — it can crack the reservoir"],
        "mall": "windshield washer fluid",
    },
    {
        "field": "Automotive",
        "title": "Tail light out",
        "symptoms": ["One tail light dark; brake light on that side may still work", "Dashboard warning for a bulb", "Ticket risk at night"],
        "diagnosis": ["Have someone watch while you test tail, brake, and turn signals", "Access the bulb through the trunk or by removing the lens", "Check the fuse if multiple lights are out", "Look for corroded sockets"],
        "diy_title": "Replace the tail light bulb",
        "diy_steps": ["Turn the lights off", "Access the bulb housing from inside the trunk or by removing the lens screws", "Twist out the bulb holder and pull the old bulb", "Install the identical new bulb and test all functions", "Clean light corrosion from the socket with electrical contact cleaner"],
        "time": "10–20 min",
        "cost": "$3–$10",
        "difficulty": "Easy",
        "tools": ["Screwdriver set", "Work gloves"],
        "parts": ["Correct tail light bulb"],
        "safety": "LOW",
        "warnings": ["Replace promptly — driving without tail lights is illegal and dangerous"],
        "mall": "tail light bulb",
    },
    {
        "field": "Automotive",
        "title": "Squealing belt",
        "symptoms": ["Loud squeal on startup or acceleration", "Squeal worse in damp weather", "Belt looks cracked or shiny"],
        "diagnosis": ["Inspect the serpentine belt for cracks, fraying, or glazing", "Check tension — a worn automatic tensioner lets the belt slip", "Look for coolant or oil contamination on the belt", "Spray a little water on the belt while running — if the squeal changes, the belt is the culprit"],
        "diy_title": "Replace the worn serpentine belt",
        "diy_steps": ["With the engine OFF, photograph the belt routing diagram", "Release the tensioner with a wrench and slip the old belt off", "Compare old and new belts for exact length and rib count", "Route the new belt per the diagram, leaving the tensioner pulley for last", "Release the tensioner, confirm the belt sits centered on every pulley", "Start the engine and confirm the squeal is gone"],
        "time": "20–45 min",
        "cost": "$15–$40",
        "difficulty": "Moderate",
        "tools": ["Wrench or breaker bar", "Work gloves"],
        "parts": ["Serpentine belt (exact fit)"],
        "safety": "MEDIUM",
        "warnings": ["Work only with the engine OFF and cool", "Keep hands, hair, and clothing clear of pulleys", "A wrongly routed belt can destroy accessories"],
        "mall": "serpentine belt",
    },
    {
        "field": "Automotive",
        "title": "TPMS light on",
        "symptoms": ["Tire pressure warning light stays on", "Light blinks then stays solid", "Tires look fine visually"],
        "diagnosis": ["Check all four tires plus the spare with a gauge when cold", "A blinking-then-solid light usually means a dead sensor battery", "Compare readings to the door-jamb sticker, not the tire sidewall", "Look for a nail causing a slow leak"],
        "diy_title": "Inflate to spec and reset the system",
        "diy_steps": ["Check every tire (and the spare) cold with a gauge", "Inflate to the door-jamb specification", "Drive for 10 minutes so the sensors update", "Use the car's TPMS reset procedure (button or menu) if the light stays on", "If one tire keeps losing air, get the puncture repaired", "A persistent blinking light means a dead sensor — a tire shop replaces it"],
        "time": "10–20 min",
        "cost": "$0–$60",
        "difficulty": "Easy",
        "tools": ["Tire pressure gauge", "Air compressor"],
        "parts": ["None DIY (sensor replacement is a shop job)"],
        "safety": "LOW",
        "warnings": ["Underinflated tires overheat and can blow out", "Do not ignore a rapid pressure loss — pull over safely"],
        "mall": "tire inflator",
    },
]
