# The Signature Mr Fix-It — seed data, batch CEE
# Fields: Home Repair (18), Small Engines & Tools (12), Lawn & Outdoor (12)

PROBLEMS = [
    {
        "field": "Home Repair",
        "title": "Hole in drywall from a doorknob",
        "symptoms": ["Round hole punched through drywall", "Doorknob hits the wall when the door opens fully"],
        "diagnosis": ["Measure the hole diameter", "Check whether it is a clean punch or crumbled edges", "Decide: patch kit for holes under 15 cm, or cut-and-replace for larger damage"],
        "diy_title": "Patch the hole with a self-adhesive mesh patch",
        "diy_steps": ["Stick a self-adhesive mesh patch centered over the hole", "Spread joint compound over the patch with a putty knife, feathering the edges", "Let dry fully, sand smooth, apply a second thin coat if needed", "Prime and paint to match the wall", "Install a door stop so it never happens again"],
        "time": "45–60 min plus drying",
        "cost": "$8–$20",
        "difficulty": "Easy",
        "tools": ["Putty knife", "Sandpaper (120 grit)", "Paintbrush"],
        "parts": ["Self-adhesive drywall patch", "Joint compound", "Primer and touch-up paint", "Hinge-pin door stop"],
        "safety": "LOW",
        "warnings": ["Wear a dust mask when sanding joint compound"],
        "mall": "drywall repair kit",
    },
    {
        "field": "Home Repair",
        "title": "Squeaky door hinge",
        "symptoms": ["Door squeaks every time it moves", "Dark grimy buildup around the hinge knuckle", "Hinge pin feels stiff or gritty"],
        "diagnosis": ["Move the door slowly to identify which hinge squeaks", "Check for rust or dried grime on the hinge pin", "Confirm the hinge is not bent or pulling out of the jamb"],
        "diy_title": "Clean and lubricate the hinge pin",
        "diy_steps": ["Close the door and tap the hinge pin up from below with a hammer and nail set", "Wipe the pin clean and scrub off rust with steel wool", "Coat the pin lightly with machine oil or silicone spray, wiping off the excess", "Tap the pin back down into the hinge", "Swing the door back and forth to work the oil in"],
        "time": "15–25 min",
        "cost": "$3–$10",
        "difficulty": "Easy",
        "tools": ["Hammer", "Nail set", "Steel wool", "Clean rag"],
        "parts": ["Light machine oil or silicone spray"],
        "safety": "LOW",
        "warnings": ["Keep fingers clear of the hinge knuckle when tapping the pin back in"],
        "mall": "door hinge lubricant",
    },
    {
        "field": "Home Repair",
        "title": "Interior door that will not latch",
        "symptoms": ["Door closes but will not catch in the frame", "Latch bolt visibly misses the strike plate", "Door pops back open after closing"],
        "diagnosis": ["Close the door slowly and watch where the latch meets the strike plate", "Mark the contact point with painter's tape or lipstick on the bolt", "Check the hinges for sag — loose top-hinge screws let the door drop"],
        "diy_title": "Reposition the strike plate to meet the latch",
        "diy_steps": ["Unscrew the strike plate and see how far the latch misses by", "If the miss is small, chisel the mortise slightly in the right direction and reinstall", "If the miss is large, fill the old screw holes with glue and toothpicks, let dry, then drill new pilot holes in the correct spot", "Reattach the strike plate flush with the jamb", "If the door sags, tighten the top hinge and replace one short screw per hinge with a 3-inch screw into the framing"],
        "time": "30–60 min",
        "cost": "$2–$8",
        "difficulty": "Moderate",
        "tools": ["Screwdriver", "Wood chisel", "Hammer", "Utility knife"],
        "parts": ["Wooden toothpicks", "Wood glue", "3-inch hinge screws"],
        "safety": "MEDIUM",
        "warnings": ["Chisel away from your body, never toward your hand", "Wear safety glasses — wood chips fly when chiseling"],
        "mall": "door strike plate",
    },
    {
        "field": "Home Repair",
        "title": "Window stuck shut from paint",
        "symptoms": ["Window will not budge up or down", "Paint bridges the seam between sash and frame", "Window was painted years ago and never opened since"],
        "diagnosis": ["Confirm the sash is held by paint, not swelling or warping", "Trace the painted-over seams on all four sides, inside and out", "Check whether both sashes are sealed or just one"],
        "diy_title": "Cut the paint seal and free the sash",
        "diy_steps": ["Score the paint line where the sash meets the frame, stool, and stops with a sharp utility knife on every side", "Work a stiff putty knife along the scored seams to break the seal", "Place a wood block against the sash and tap gently with a hammer to loosen it", "Work the sash up and down in small movements until it moves freely", "Lightly sand the freed edges and rub paraffin wax on them so the paint never reseals"],
        "time": "30–60 min",
        "cost": "$3–$10",
        "difficulty": "Moderate",
        "tools": ["Utility knife", "Stiff putty knife", "Hammer", "Wood block", "Sandpaper"],
        "parts": ["Paraffin wax or candle stub", "Painter's tape"],
        "safety": "MEDIUM",
        "warnings": ["Always cut away from your body — scored paint can let the blade slip", "On homes built before 1978, test for lead paint before disturbing old paint layers"],
        "mall": "window paint zipper",
    },
    {
        "field": "Home Repair",
        "title": "Drafty window",
        "symptoms": ["Cold air felt around the window edges", "Curtains move when the window is closed", "Noticeably higher heating bills in winter"],
        "diagnosis": ["Hold a strip of tissue near the edges on a windy day to find the leaks", "Inspect the weatherstripping for gaps, flattening, or missing sections", "Check the exterior caulk where the frame meets the siding"],
        "diy_title": "Replace worn weatherstripping and seal the gaps",
        "diy_steps": ["Clean the sash and frame channels so new adhesive will stick", "Pull out the old weatherstripping and press in new V-strip or foam weatherstripping", "Re-caulk gaps between the window frame and the siding with exterior caulk", "For a winter-only boost, apply shrink-film window insulation over the whole frame", "Recheck with the tissue test and seal any spots you missed"],
        "time": "30–60 min",
        "cost": "$5–$20",
        "difficulty": "Easy",
        "tools": ["Utility knife", "Putty knife", "Caulk gun", "Scissors"],
        "parts": ["Adhesive V-strip or foam weatherstripping", "Exterior caulk", "Window insulation film kit (optional)"],
        "safety": "LOW",
        "warnings": ["Never use an open flame to find drafts near curtains — use a tissue strip instead"],
        "mall": "window weatherstripping",
    },
    {
        "field": "Home Repair",
        "title": "Scratched hardwood floor",
        "symptoms": ["Fine scratches visible in traffic areas", "Finish looks dull where the scratches are", "No deep gouges through the wood itself"],
        "diagnosis": ["Determine scratch depth — surface finish only, or into the wood", "Check whether the floor is solid wood or thin engineered veneer before any sanding", "Match the floor color in a hidden spot like a closet"],
        "diy_title": "Touch up surface scratches and blend the finish",
        "diy_steps": ["Clean the floor thoroughly with a microfiber mop so dirt does not grind in", "Color shallow scratches with a wood stain marker in a matching tone", "Fill slightly deeper scratches with a wax repair stick and level it with a plastic scraper", "Buff the repair with a soft cloth to blend the sheen", "Apply a matching hardwood floor polish over scuffed areas for an even finish"],
        "time": "30–90 min",
        "cost": "$5–$25",
        "difficulty": "Easy",
        "tools": ["Microfiber mop", "Soft cloth", "Fine sandpaper (220 grit)", "Plastic scraper"],
        "parts": ["Wood stain marker", "Wax repair stick", "Hardwood floor polish"],
        "safety": "LOW",
        "warnings": ["Test the stain color in a hidden spot first — it dries darker than it looks wet"],
        "mall": "hardwood floor scratch repair",
    },
    {
        "field": "Home Repair",
        "title": "Peeling interior paint",
        "symptoms": ["Paint bubbles and flakes off in sheets", "Large flexible sheets peel away cleanly", "Often worst in humid rooms like bathrooms"],
        "diagnosis": ["Check the peel pattern — flexible sheets mean latex over old oil paint without primer", "Look for moisture behind the paint (stains, soft plaster)", "Confirm no water source is still active before repainting"],
        "diy_title": "Scrape, prime, and repaint the affected area",
        "diy_steps": ["Scrape off all loose paint with a putty knife until you reach solidly bonded paint", "Sand the edges feather-smooth so the repair line disappears", "Fix any moisture source behind the wall first", "Wipe away all dust and apply a bonding primer (oil-based or shellac-based if covering old oil paint)", "Repaint with two finish coats, letting each dry fully"],
        "time": "1–3 hours plus drying",
        "cost": "$10–$40",
        "difficulty": "Moderate",
        "tools": ["Putty knife", "Sandpaper", "Paintbrush or roller", "Drop cloth"],
        "parts": ["Bonding primer", "Interior paint"],
        "safety": "LOW",
        "warnings": ["Wear a dust mask when scraping and sanding", "On homes built before 1978, test for lead paint before disturbing old layers"],
        "mall": "bonding primer",
    },
    {
        "field": "Home Repair",
        "title": "Cabinet door hanging loose",
        "symptoms": ["Cabinet door sags or sits crooked", "Hinge screws spin freely without biting", "Door scrapes the cabinet frame when closing"],
        "diagnosis": ["Open the door and test each hinge screw — spinning screws mean stripped holes", "Check whether the hinge arm itself is bent", "Confirm the door is not water-damaged at the screw holes"],
        "diy_title": "Re-seat the hinge screws in stripped holes",
        "diy_steps": ["Remove the hinge screws from the stripped holes", "Pack each hole with wood glue and wooden toothpicks or small dowel bits", "Let the glue dry fully, then trim the filler flush", "Re-drive the screws into the reinforced holes", "Use the hinge adjustment screws to square the door in the opening"],
        "time": "30–45 min",
        "cost": "$3–$10",
        "difficulty": "Easy",
        "tools": ["Screwdriver", "Utility knife"],
        "parts": ["Wooden toothpicks or dowels", "Wood glue"],
        "safety": "LOW",
        "warnings": ["Wipe excess glue off the finish before it dries — dried glue stains through paint"],
        "mall": "cabinet hinge repair",
    },
    {
        "field": "Home Repair",
        "title": "Wooden drawer sticking shut",
        "symptoms": ["Drawer jams halfway in or out", "Rubs hard on one side", "Worse in humid weather"],
        "diagnosis": ["Pull the drawer out and mark the shiny rub spots with chalk", "Check whether the drawer box is loose or the wood is swollen", "Look for a broken or bent metal slide if the drawer has them"],
        "diy_title": "Ease the drawer with wax and light sanding",
        "diy_steps": ["Remove the drawer completely", "Rub a candle or paraffin wax stick along the drawer runners and the drawer edges", "If it still sticks, lightly sand only the shiny rub spots", "Reinstall and check it glides level", "If the wood is badly swollen, shave a thin pass off the binding edge with a hand plane"],
        "time": "20–40 min",
        "cost": "$2–$8",
        "difficulty": "Easy",
        "tools": ["Sandpaper (120 grit)", "Screwdriver", "Hand plane (only if needed)"],
        "parts": ["Paraffin wax or candle stub"],
        "safety": "LOW",
        "warnings": ["Sand gradually — removing too much wood leaves a drawer that rattles loose"],
        "mall": "drawer slide lubricant",
    },
    {
        "field": "Home Repair",
        "title": "Clogged gutter",
        "symptoms": ["Water overflows over the gutter edge in rain", "A section of gutter visibly sags", "Plants or moss growing in the gutter"],
        "diagnosis": ["Inspect from the ground for sagging and overflow points", "From a ladder, check where debris piles up — usually at downspout outlets", "Check whether hangers are loose or the slope no longer drains toward the downspout"],
        "diy_title": "Clear debris and flush the gutter clean",
        "diy_steps": ["Set the ladder on firm, level ground and have a helper foot it", "Scoop out leaves and debris by hand into a bucket, working toward the downspout", "Clear the downspout by flushing water down from the top with a garden hose", "Use a plumber's snake on stubborn downspout clogs", "Reattach loose hangers and confirm water drains toward the downspout"],
        "time": "1–2 hours",
        "cost": "$5–$15",
        "difficulty": "Moderate",
        "tools": ["Sturdy ladder", "Work gloves", "Trowel", "Garden hose", "Bucket"],
        "parts": ["Replacement gutter hangers"],
        "safety": "HIGH",
        "warnings": ["Never lean a ladder against the gutter itself — it will bend or break", "Keep three points of contact on the ladder and never overreach sideways", "Do not work at height in wet or windy conditions"],
        "mall": "gutter cleaning tools",
    },
    {
        "field": "Home Repair",
        "title": "Loose deck board",
        "symptoms": ["Board rocks or creaks underfoot", "Nail or screw heads have popped up", "Visible movement when you step on it"],
        "diagnosis": ["Step on each board to find the loose one", "Check whether screws backed out, nails popped, or the board end is rotted at the joist", "Probe the joist wood with a screwdriver — soft spots mean rot"],
        "diy_title": "Re-fasten the board solidly to the joist",
        "diy_steps": ["Pull out the popped nails or stripped screws", "Reposition the board so its ends land on a joist", "Drive two 3-inch exterior deck screws per joist crossing", "If the joist itself is rotted, sister a new section of joist alongside it or call a pro", "Tap down any other raised fastener heads nearby"],
        "time": "30–45 min",
        "cost": "$5–$15",
        "difficulty": "Easy",
        "tools": ["Drill/driver", "Pry bar", "Hammer"],
        "parts": ["Exterior deck screws"],
        "safety": "MEDIUM",
        "warnings": ["Wear gloves — old deck nails and splinters are sharp", "Check the surrounding boards for rot while the tools are out"],
        "mall": "deck screws exterior",
    },
    {
        "field": "Home Repair",
        "title": "Leaning fence post",
        "symptoms": ["Post leans noticeably to one side", "Fence section wobbles when pushed", "Post rocks at ground level"],
        "diagnosis": ["Dig around the base to see if the wood is rotted or the footing shifted", "Check whether the concrete footing is cracked or undersized", "Check the rest of the fence line for posts going the same way"],
        "diy_title": "Reset the post with a new concrete footing",
        "diy_steps": ["Brace the fence panels with 2x4 stakes so they cannot fall while you work", "Dig out around the old post and pull it out", "If the post is rotted, replace it with a new pressure-treated post — do not reuse rotted wood", "Set the new post plumb in the hole, at least one third of the post height deep", "Pour fast-setting concrete mix and add water per the bag directions", "Leave the braces on for 24–48 hours while the concrete cures"],
        "time": "2–4 hours plus curing",
        "cost": "$10–$30",
        "difficulty": "Moderate",
        "tools": ["Shovel", "Post-hole digger", "Level", "Saw"],
        "parts": ["Pressure-treated fence post", "Fast-setting concrete mix"],
        "safety": "MEDIUM",
        "warnings": ["Call the utility locator (811 in the US) before any digging", "Lift concrete bags with your knees, not your back"],
        "mall": "fence post concrete",
    },
    {
        "field": "Home Repair",
        "title": "Torn window screen",
        "symptoms": ["Rip or hole in the screen mesh", "Insects getting inside through the screen", "Rubber spline pulling out of the frame groove"],
        "diagnosis": ["Measure the tear — holes under 3 inches can be patched, larger tears need rescreening", "Check whether the frame itself is bent or cracked", "Confirm you have the right spline diameter for the frame groove"],
        "diy_title": "Rescreen the frame with new mesh",
        "diy_steps": ["Pry out the old rubber spline with a flat screwdriver and discard the old mesh", "Lay new fiberglass screen mesh over the frame with a few inches of overlap", "Press new spline into the groove over the mesh using a spline roller tool", "Trim the excess mesh with a sharp utility knife", "Reinstall the screen and check the fit"],
        "time": "30–45 min per screen",
        "cost": "$5–$15",
        "difficulty": "Easy",
        "tools": ["Flat screwdriver", "Spline roller", "Utility knife"],
        "parts": ["Replacement screen mesh", "Screen spline"],
        "safety": "LOW",
        "warnings": ["Wear gloves — cut screen edges are sharp", "Cut the blade away from your body when trimming the mesh"],
        "mall": "window screen repair kit",
    },
    {
        "field": "Home Repair",
        "title": "Jammed deadbolt lock",
        "symptoms": ["Key will not turn or turns only partway", "Deadbolt sticks halfway out", "Thumb-turn jams from inside"],
        "diagnosis": ["Try the key while lifting or pressing the door — if it works, the bolt is misaligned with the strike", "Puff graphite in the keyway — if it frees up, the cylinder was dry", "Remove the interior side to inspect the tailpiece and bolt alignment"],
        "diy_title": "Clean, lubricate, and realign the deadbolt",
        "diy_steps": ["Puff dry graphite lubricant into the keyway and work the key in and out several times", "Unscrew the interior side and check the tailpiece for bending or wear", "File the strike plate opening slightly if the bolt visibly rubs on it", "Check the door edge and strike alignment — shift the strike plate if needed", "If the cylinder itself is worn or damaged, replace the whole deadbolt — usually just two screws"],
        "time": "20–40 min",
        "cost": "$5–$15 for lube, $20–$60 to replace",
        "difficulty": "Moderate",
        "tools": ["Screwdriver", "Metal file"],
        "parts": ["Dry graphite lubricant", "Replacement deadbolt (if needed)"],
        "safety": "LOW",
        "warnings": ["Never spray oil-based lubricant into a lock — it gums up over time; use dry graphite only"],
        "mall": "graphite lock lubricant",
    },
    {
        "field": "Home Repair",
        "title": "Set-in carpet stain",
        "symptoms": ["Discolored spot will not come out with soap and water", "Stain reappears after drying (wicking from the pad)", "Dull, matted fibers in the stained area"],
        "diagnosis": ["Identify the stain type if possible — dye stains (wine, coffee) vs grease vs protein", "Test any cleaner in a hidden corner first for colorfastness", "Check whether the stain has reached the backing or pad"],
        "diy_title": "Lift the stain with the blot-rinse-blot method",
        "diy_steps": ["Blot — never rub — with a clean white cloth to lift as much as possible", "Apply a mix of dish soap and warm water (or a white vinegar solution)", "Blot from the outside of the stain inward so it does not spread", "Rinse by blotting with clean water to remove soap residue", "Stack dry towels on the spot and weigh them down overnight so the pad cannot wick the stain back up"],
        "time": "30–60 min",
        "cost": "$3–$12",
        "difficulty": "Easy",
        "tools": ["White cloths or towels", "Spray bottle", "Heavy book (as a weight)"],
        "parts": ["Dish soap", "White vinegar", "Baking soda (for odor)"],
        "safety": "LOW",
        "warnings": ["Never use hot water on protein stains (blood, egg, milk) — heat sets them; use cold water"],
        "mall": "carpet stain remover",
    },
    {
        "field": "Home Repair",
        "title": "Cracked floor tile",
        "symptoms": ["Single tile cracked through", "Grout around it still intact", "Subfloor underneath feels solid"],
        "diagnosis": ["Check whether the crack continues into neighboring tiles — that means subfloor movement (call a pro)", "Confirm the crack is from impact, not a shifting slab", "Make sure you have a matching replacement tile"],
        "diy_title": "Replace the single cracked tile",
        "diy_steps": ["Tape off the surrounding tiles to protect them", "Chip out the cracked tile starting from the center with a cold chisel", "Scrape out the old mortar down to a clean subfloor", "Dry-fit the new tile to check the height", "Spread thinset mortar with a notched trowel and set the tile level with its neighbors", "Grout after 24 hours and seal the grout lines"],
        "time": "1–2 hours plus curing",
        "cost": "$8–$30",
        "difficulty": "Moderate",
        "tools": ["Cold chisel", "Hammer", "Notched trowel", "Grout float", "Sponge"],
        "parts": ["Replacement tile", "Thinset mortar", "Grout"],
        "safety": "MEDIUM",
        "warnings": ["Wear safety glasses and gloves — tile shards are sharp", "Cover nearby tiles with tape or cardboard to protect them from chips"],
        "mall": "tile repair kit",
    },
    {
        "field": "Home Repair",
        "title": "Wobbly ceiling fan",
        "symptoms": ["Fan wobbles noticeably on high speed", "Clicking or rattling noise while running", "Mounting hardware feels loose"],
        "diagnosis": ["TURN OFF power at the breaker — not just the wall switch", "Check the mounting bracket and downrod screws for looseness", "Measure blade heights — a bent blade holder throws the fan out of balance", "Decide: new wobble means loose screws; wobble from day one means installation issue"],
        "diy_title": "Tighten the mount and balance the blades",
        "diy_steps": ["Switch off the breaker and confirm power is off", "Tighten all mounting bracket and downrod screws", "Measure each blade's height from the ceiling and gently bend any misaligned blade holder", "Use a blade-balancing kit: clip the test weight on each blade in turn to find the worst one", "Stick the adhesive weight on that blade's center and retest until the wobble is gone"],
        "time": "45–90 min",
        "cost": "$5–$15",
        "difficulty": "Moderate",
        "tools": ["Screwdriver", "Step ladder", "Tape measure"],
        "parts": ["Ceiling fan balancing kit"],
        "safety": "MEDIUM",
        "warnings": ["Confirm power is off at the breaker and test with a non-contact voltage tester", "A fan must hang from a fan-rated electrical box — if yours is a standard light box, call an electrician"],
        "mall": "ceiling fan balancing kit",
    },
    {
        "field": "Home Repair",
        "title": "Caulking cracking in the bathroom",
        "symptoms": ["Caulk line pulling away at tub or shower edges", "Gaps letting water get behind the fixture", "Mildew growing in the caulk gap"],
        "diagnosis": ["Check whether the old caulk is silicone (rubbery) or latex (paintable)", "Probe behind the gap — soft, spongy wall means water damage (call a pro)", "Confirm the joint is dry before re-caulking"],
        "diy_title": "Cut out and replace the bathroom caulk",
        "diy_steps": ["Slice out ALL the old caulk with a utility knife — new caulk will not bond to old caulk", "Clean the joint with rubbing alcohol and let it dry completely", "Tape both sides of the joint for a clean line", "Apply 100% silicone bathroom caulk in one steady bead", "Tool the bead smooth with a wet finger and pull the tape immediately", "Let it cure 24 hours before the shower or tub gets wet"],
        "time": "1–2 hours plus curing",
        "cost": "$5–$12",
        "difficulty": "Easy",
        "tools": ["Utility knife", "Caulk gun", "Painter's tape"],
        "parts": ["100% silicone bathroom caulk", "Rubbing alcohol"],
        "safety": "LOW",
        "warnings": ["Ventilate the bathroom — silicone fumes are strong", "Wear gloves to keep uncured silicone off your skin"],
        "mall": "bathroom silicone caulk",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Chainsaw will not start",
        "symptoms": ["Pull cord feels normal but the engine will not fire", "Engine floods easily or smells strongly of fuel", "Sat unused for months with old fuel in the tank"],
        "diagnosis": ["Check the kill switch and chain brake position first", "Inspect the fuel — anything older than 30 days is stale", "Remove the spark plug: wet means flooded, dry means fuel starvation", "Check the air filter and fuel filter for clogging"],
        "diy_title": "Service the fuel and spark system",
        "diy_steps": ["Drain the stale fuel and mix fresh 2-stroke fuel at the manufacturer's ratio", "Remove the spark plug, dry it off, check the gap, or replace it", "Clean or replace the air filter", "Set the choke per the manual — full choke for a cold engine", "Place the saw on the ground, hold it firmly with the chain brake on, and pull briskly", "If it is flooded, hold the throttle open with the choke off and pull until it clears"],
        "time": "30–60 min",
        "cost": "$5–$20",
        "difficulty": "Moderate",
        "tools": ["Spark plug wrench", "Flat screwdriver", "Fuel container"],
        "parts": ["Fresh 2-stroke fuel mix", "Spark plug", "Air filter"],
        "safety": "HIGH",
        "warnings": ["Never start a chainsaw while holding it in the air — start it on the ground with the chain brake engaged", "Never refuel near an open flame or while the engine is hot"],
        "mall": "chainsaw tune up kit",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Cordless drill battery will not charge",
        "symptoms": ["Battery shows no charge after hours on the charger", "Charger light blinks red or stays off", "Drill runs weak even after a full charge cycle"],
        "diagnosis": ["Test the charger with a known-good battery to isolate charger vs pack", "Inspect the battery terminals for corrosion or dirt", "Note the battery age — 3–5 years is typical end of life", "Check whether it was stored in extreme heat or freezing cold"],
        "diy_title": "Clean the contacts and replace the pack if it is dead",
        "diy_steps": ["Unplug the charger", "Clean the battery and charger contacts with a dry cloth and rubbing alcohol", "Let everything dry, then charge again at room temperature", "If it still will not take a charge and the pack is over 3 years old, replace the battery pack", "Recycle the old battery at a battery drop-off — never put it in the trash"],
        "time": "15–30 min",
        "cost": "$0 for cleaning, $30–$60 to replace",
        "difficulty": "Easy",
        "tools": ["Cloth", "Rubbing alcohol"],
        "parts": ["Replacement battery pack (if needed)"],
        "safety": "LOW",
        "warnings": ["Never open a lithium battery pack — punctured cells can catch fire", "Do not dispose of batteries in household trash"],
        "mall": "cordless drill battery",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Circular saw blade wobbling",
        "symptoms": ["Blade visibly wobbles when spun by hand", "Cuts wander off the line", "Unusual vibration during cuts"],
        "diagnosis": ["UNPLUG the saw before touching anything", "Check whether the arbor nut is tight", "Inspect the blade plate for bends and the teeth for damage", "Spin the arbor without the blade to isolate a bent blade from a damaged arbor"],
        "diy_title": "Reseat or replace the damaged blade",
        "diy_steps": ["Unplug the saw", "Remove the blade and inspect the arbor, washers, and blade plate for bends", "Clean packed sawdust off the washers so the blade seats flat", "Reseat the blade with the teeth pointing in the rotation direction", "Tighten the arbor nut firmly using the blade lock", "Spin by hand to confirm it runs true — if the plate is bent, replace the blade"],
        "time": "20–30 min",
        "cost": "$0 to reseat, $10–$30 for a new blade",
        "difficulty": "Easy",
        "tools": ["Blade wrench (usually stored on the saw)", "Work gloves"],
        "parts": ["Replacement circular saw blade (if bent)"],
        "safety": "MEDIUM",
        "warnings": ["Always unplug the saw before touching the blade", "Never use a cracked or bent blade — replace it"],
        "mall": "circular saw blade",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Air compressor not building pressure",
        "symptoms": ["Motor runs but the tank gauge barely rises", "Audible hissing from a fitting or hose", "Tools run weak or stall"],
        "diagnosis": ["Switch off, unplug, and drain all pressure first", "Brush soapy water over every fitting and hose connection — bubbles mark the leak", "Check that the tank drain valve is fully closed", "Inspect the intake filter and the check valve between pump and tank"],
        "diy_title": "Find and seal the air leak",
        "diy_steps": ["Switch off and unplug the compressor, then drain the tank fully", "Spray soapy water over every fitting, hose, and quick-connect coupler", "Tighten any fitting that bubbles, using thread seal tape on pipe threads", "Replace cracked hoses and worn quick-connect couplers", "Clean or replace the intake filter", "If air leaks back into the pump, replace the check valve"],
        "time": "45–90 min",
        "cost": "$5–$25",
        "difficulty": "Moderate",
        "tools": ["Adjustable wrench", "Spray bottle with soapy water"],
        "parts": ["Thread seal tape", "Replacement hose or couplers", "Intake filter"],
        "safety": "MEDIUM",
        "warnings": ["Never open fittings on a pressurized tank — drain it first", "If the tank itself is rusted through, replace the whole compressor — a weak pressure vessel can burst"],
        "mall": "air compressor parts kit",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Pressure washer with low pressure",
        "symptoms": ["Weak, sputtering spray", "Pressure pulses instead of holding steady", "Nozzle dribbles instead of jetting"],
        "diagnosis": ["Check the water supply — kinked hose or low flow starves the pump", "Remove and inspect the nozzle for clogs or wear", "Check the inlet filter screen where the garden hose connects", "Look for air in the line making the pump cavitate"],
        "diy_title": "Clear the nozzle and restore full water flow",
        "diy_steps": ["Turn the machine off and release pressure by squeezing the trigger", "Unscrew the nozzle and clear it with a cleaning needle or fine wire", "Rinse the nozzle backward under a tap", "Clean the inlet filter screen at the garden hose connection", "Straighten the garden hose and confirm full water flow before restarting", "Purge air by running water through with the machine off until the stream runs steady"],
        "time": "20–40 min",
        "cost": "$0–$15",
        "difficulty": "Easy",
        "tools": ["Nozzle cleaning needle", "Pliers"],
        "parts": ["Replacement nozzle (if the old one is worn)"],
        "safety": "MEDIUM",
        "warnings": ["Never point the wand at people, pets, or yourself", "Never run the pump without water — it overheats in under a minute"],
        "mall": "pressure washer nozzle",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Portable generator will not start",
        "symptoms": ["Engine cranks but will not fire", "Generator sat unused for months", "Starts then dies under no load"],
        "diagnosis": ["Check the oil level — the low-oil shutdown kills the spark", "Check the fuel — stale gas is the number one cause", "Confirm the fuel valve is open and the choke is set for a cold engine", "Inspect the spark plug and air filter"],
        "diy_title": "Drain the stale fuel and service the basics",
        "diy_steps": ["Turn the fuel valve off and drain the old gasoline from the tank and carburetor bowl", "Refill with fresh fuel plus fuel stabilizer", "Check the oil level and top up to the full mark", "Clean or replace the air filter", "Pull the spark plug, clean and gap it, or replace it", "Open the fuel valve, set the choke for a cold engine, and pull the starter firmly"],
        "time": "45–90 min",
        "cost": "$8–$25",
        "difficulty": "Moderate",
        "tools": ["Spark plug wrench", "Screwdriver", "Fuel container", "Funnel"],
        "parts": ["Fresh gasoline", "Fuel stabilizer", "Spark plug", "Air filter"],
        "safety": "HIGH",
        "warnings": ["NEVER run a generator indoors or in a garage — carbon monoxide kills silently", "Keep it at least 20 feet from the house with the exhaust pointed away", "Let the engine cool before refueling"],
        "mall": "generator maintenance kit",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Shop vacuum lost suction",
        "symptoms": ["Weak suction at the hose", "Dust blowing out the exhaust port", "Motor sounds strained"],
        "diagnosis": ["Check the hose for clogs by running something long through it", "Inspect the filter — a clogged filter is the usual cause", "Check whether the drum is full or the bag is packed", "Inspect the lid seal and hose cuffs for cracks"],
        "diy_title": "Clean the filter and clear the hose",
        "diy_steps": ["Unplug the vacuum", "Empty the drum or replace the collection bag", "Remove the filter and shake out the dust — replace it if torn", "Check the float valve that blocks wet pickup and clean it", "Dislodge any hose clog with a long stick or broom handle", "Reseat the lid, latch it fully, and test suction"],
        "time": "20–30 min",
        "cost": "$5–$20",
        "difficulty": "Easy",
        "tools": ["Trash bag", "Stiff brush"],
        "parts": ["Replacement filter", "Collection bags"],
        "safety": "LOW",
        "warnings": ["Wear a dust mask when emptying fine dust", "Never vacuum flammable liquids or hot ash"],
        "mall": "shop vac filter",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Hedge trimmer blades jammed",
        "symptoms": ["Blades will not move at all", "Motor strains, buzzes, or trips off", "A twig visibly wedged between the teeth"],
        "diagnosis": ["DISCONNECT power completely — unplug or remove the battery", "Inspect the blade gap for wedged branches", "Check for bent or broken teeth", "Check whether the blade bolts were over-tightened"],
        "diy_title": "Clear the jam and free the blades",
        "diy_steps": ["Disconnect power completely", "Pull the wedged branch out of the teeth with pliers — never your fingers", "Inspect for bent or broken teeth; replace the blade bar if teeth are damaged", "Loosen the blade bolts slightly if they were pinching — snug enough to hold, loose enough to glide", "Spray the blades with light lubricant and wipe them clean"],
        "time": "20–40 min",
        "cost": "$0–$15",
        "difficulty": "Easy",
        "tools": ["Pliers", "Wrench", "Work gloves"],
        "parts": ["Blade lubricant spray", "Replacement blade bar (if damaged)"],
        "safety": "MEDIUM",
        "warnings": ["Trimmer blades are razor sharp even with the power off — wear cut-resistant gloves", "Keep fingers out of the tooth gap while clearing the jam"],
        "mall": "hedge trimmer blade",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Nail gun misfiring",
        "symptoms": ["Gun skips nails or double-fires", "Nails driven weakly or not fully sunk", "Nails jamming in the nose"],
        "diagnosis": ["DISCONNECT the air hose or remove the battery first", "Open the nose and look for jammed or bent nails", "Check the air pressure — too low means weak drive, too high means blowout", "Confirm you are using the correct nail angle and collation type for the gun"],
        "diy_title": "Clear the jam and set the correct pressure",
        "diy_steps": ["Disconnect the air supply or battery and engage the safety", "Open the nose latch and clear any jammed or bent nails", "Oil a pneumatic gun per the manual — a few drops in the air inlet", "Reload with the correct nails for the gun", "Reconnect and set the pressure to the manual's recommended range", "Test-fire into scrap wood; if the driver blade is chipped or it still double-fires, have it serviced"],
        "time": "20–40 min",
        "cost": "$3–$12",
        "difficulty": "Moderate",
        "tools": ["Hex keys", "Pliers", "Safety glasses"],
        "parts": ["Correct brad or finish nails", "Pneumatic tool oil"],
        "safety": "HIGH",
        "warnings": ["Treat every nail gun as loaded — keep it pointed away from yourself and others", "NEVER disable or bypass the contact safety tip", "Disconnect air or battery before clearing any jam"],
        "mall": "nail gun oil",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Random-orbit sander leaving swirl marks",
        "symptoms": ["Visible circular scratches in the wood", "Finish highlights the scratches instead of hiding them", "Disc edge leaving deeper rings"],
        "diagnosis": ["Check the grit sequence — skipping grits leaves swirls", "Inspect the pad for tears and the dust bag for clogging", "Review technique — pressing hard or tilting the sander causes gouges"],
        "diy_title": "Reset the grit sequence and sanding technique",
        "diy_steps": ["Fit the correct next grit — never skip more than one grit (for example 80, then 120, then 150)", "Center the disc on the pad — an overhanging disc edge gouges", "Keep the sander flat and let its own weight do the work — do not press down", "Keep the dust bag or port clear so grit does not get ground into the wood", "Finish with a slow final pass at 180–220 grit"],
        "time": "30–60 min",
        "cost": "$5–$12",
        "difficulty": "Easy",
        "tools": ["Sandpaper discs in a grit sequence", "Tack cloth", "Dust mask"],
        "parts": ["Assorted sanding discs"],
        "safety": "LOW",
        "warnings": ["Wear a dust mask — wood dust is a lung irritant"],
        "mall": "sanding discs assorted",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Miter saw cutting inaccurately",
        "symptoms": ["Cuts are not square", "Miter angles off by a degree or two", "Wood burns or tears out instead of cutting clean"],
        "diagnosis": ["UNPLUG the saw", "Check the blade for dullness and pitch buildup", "Check the fence for square against the blade with a speed square", "Check the miter detents for packed sawdust"],
        "diy_title": "Square the fence and calibrate the angles",
        "diy_steps": ["Unplug the saw", "Clean pitch off the blade with a blade cleaner", "Loosen the fence bolts, square the fence to the blade with a speed square, and re-tighten", "Set the miter to the 0-degree detent, verify against a square, and adjust the detent screws if it is off", "Clear packed sawdust from the detent plate", "Replace a dull blade — burning and tear-out mean it is done"],
        "time": "30–60 min",
        "cost": "$10–$40 with a new blade",
        "difficulty": "Moderate",
        "tools": ["Speed square", "Hex wrenches", "Blade cleaner"],
        "parts": ["Replacement miter saw blade (if dull)"],
        "safety": "MEDIUM",
        "warnings": ["Keep hands clear of the blade path and clamp small pieces", "Unplug the saw before adjusting anything near the blade"],
        "mall": "miter saw blade",
    },
    {
        "field": "Small Engines & Tools",
        "title": "Workbench wobbling",
        "symptoms": ["Bench rocks during sawing or hammering", "Legs visibly uneven", "Joints loose or racking side to side"],
        "diagnosis": ["Rock the bench to find which joint is loose", "Check for loose bolts, stripped screws, or failed glue joints", "Check whether the floor itself is uneven"],
        "diy_title": "Tighten the joints and brace the frame",
        "diy_steps": ["Tilt or flip the bench to reach the joints", "Tighten all bolts and screws — replace stripped ones with bolts plus washers", "Re-glue failed wood joints with wood glue and clamp them until set", "Add diagonal braces or a lower shelf to stiffen the frame", "If the floor is uneven, add adjustable leveling feet or shims under the short leg"],
        "time": "45–90 min",
        "cost": "$5–$20",
        "difficulty": "Easy",
        "tools": ["Wrench set", "Screwdriver", "Clamps", "Drill"],
        "parts": ["Wood glue", "Bolts with washers", "Diagonal brace lumber", "Leveling feet"],
        "safety": "LOW",
        "warnings": ["Support the bench so it cannot tip onto you while you work underneath it"],
        "mall": "workbench leveling feet",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Lawn mower will not start",
        "symptoms": ["Pull cord will not turn over or the engine sputters and dies", "Mower sat all winter with old gas in the tank", "No sign of spark or fuel reaching the engine"],
        "diagnosis": ["Check the fuel freshness — stale gas is the number one cause", "Check the oil level", "Remove the spark plug: wet means flooded, dry means no fuel", "Check the air filter and clear packed grass from under the deck"],
        "diy_title": "Drain the stale fuel and run the no-start checklist",
        "diy_steps": ["Drain the old gasoline from the tank and refill with fresh fuel", "Check the oil level and top up to the full mark", "Remove the spark plug, clean the gap, or replace it", "Clean the air filter — replace it if torn", "Disconnect the spark plug wire and clear packed grass from under the deck", "Reconnect, set the choke or prime per the manual, and pull the starter"],
        "time": "30–60 min",
        "cost": "$5–$20",
        "difficulty": "Easy",
        "tools": ["Spark plug wrench", "Screwdriver", "Fuel container"],
        "parts": ["Fresh gasoline", "Spark plug", "Air filter", "Engine oil"],
        "safety": "MEDIUM",
        "warnings": ["Disconnect the spark plug wire before reaching under the deck", "Let a hot engine cool before draining fuel"],
        "mall": "lawn mower tuneup kit",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Mower blade dull",
        "symptoms": ["Grass tips look torn and brown instead of cleanly cut", "Mower leaves strips of uncut grass", "Excessive vibration while mowing"],
        "diagnosis": ["Disconnect the spark plug wire", "Tilt the mower air-filter side up and inspect the blade edge", "A rounded or nicked edge means dull; deep nicks mean replace, not sharpen", "Plan to check blade balance after sharpening"],
        "diy_title": "Remove, sharpen, and balance the blade",
        "diy_steps": ["Disconnect the spark plug wire", "Tilt the mower with the air filter side up", "Brace the blade with a block of wood and remove the center bolt", "Sharpen the edge with a metal file at the factory angle, removing equal metal from both ends", "Hang the blade on a nail to check balance — file the heavy end until it hangs level", "Reinstall and torque the bolt to the manual's specification"],
        "time": "30–60 min",
        "cost": "$0 to sharpen, $15–$25 for a new blade",
        "difficulty": "Moderate",
        "tools": ["Wrench", "Metal file or bench grinder", "Wood block", "Work gloves"],
        "parts": ["Replacement mower blade (if too nicked to sharpen)"],
        "safety": "MEDIUM",
        "warnings": ["Wear heavy gloves — the blade edge is sharp", "Always disconnect the spark plug wire before working under the deck"],
        "mall": "lawn mower blade",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "String trimmer line will not feed",
        "symptoms": ["Line stays too short and will not advance when bumped", "Head jams or the line snaps off at the eyelet", "Freshly loaded line still will not feed"],
        "diagnosis": ["Remove the spool and check whether the line fused together from heat", "Check the winding direction against the arrows on the spool", "Confirm the line diameter matches the trimmer's spec", "Check the bump knob spring for damage"],
        "diy_title": "Rewind the spool with fresh line",
        "diy_steps": ["Disconnect power — unplug the trimmer or remove the battery", "Open the trimmer head and remove the spool", "Discard any fused or tangled line", "Wind new line tightly in the direction of the arrows, keeping it even and level", "Feed the ends through the eyelets and reassemble the head", "Bump-test on grass to confirm it feeds"],
        "time": "20–30 min",
        "cost": "$5–$12",
        "difficulty": "Easy",
        "tools": ["Work gloves", "Scissors"],
        "parts": ["Trimmer line (correct diameter for the trimmer)"],
        "safety": "LOW",
        "warnings": ["Wear eye protection when trimming — thrown debris is the main injury", "Keep the debris guard on the trimmer"],
        "mall": "string trimmer line",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Leaf blower has no power",
        "symptoms": ["Weak airflow even at full throttle", "Gas engine bogs down under load", "Electric blower runs slowly on a long extension cord"],
        "diagnosis": ["Gas: check fuel freshness, air filter, spark plug, and the exhaust spark arrestor screen", "Electric: check the extension cord — a long thin cord causes voltage drop", "Check the intake vents and collection bag for blockages"],
        "diy_title": "Clear the intake, exhaust, and power path",
        "diy_steps": ["For a gas blower: replace stale fuel and clean the air filter", "Clean the spark arrestor screen in the muffler with a wire brush — carbon buildup chokes the engine", "Check the spark plug and replace if fouled", "For an electric blower: switch to a shorter, heavier-gauge extension cord", "Clear the intake vents and empty any collection bag or filter"],
        "time": "30–45 min",
        "cost": "$5–$20",
        "difficulty": "Easy",
        "tools": ["Screwdriver", "Wire brush"],
        "parts": ["Fresh fuel mix", "Air filter", "Spark plug"],
        "safety": "LOW",
        "warnings": ["Let a hot engine cool before servicing", "Never operate a gas blower indoors"],
        "mall": "leaf blower parts",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Sprinkler head broken",
        "symptoms": ["Water geysers straight up from one spot", "Head will not pop up when the zone runs", "Dry brown spots near a head"],
        "diagnosis": ["Turn the zone on and watch each head", "Check whether the head is cracked, clogged with dirt, or just misaligned", "Check the riser height — heads buried below the grass cannot spray"],
        "diy_title": "Replace the broken sprinkler head",
        "diy_steps": ["Turn off the water to the zone", "Dig around the head to expose it without breaking the pipe", "Unscrew the old head from the riser", "Flush the line by briefly turning the water on to clear debris", "Screw on the new head of the same type (spray or rotor)", "Set the arc and spray distance per the instructions, backfill, and test"],
        "time": "30–60 min",
        "cost": "$5–$20",
        "difficulty": "Easy",
        "tools": ["Shovel", "Small towel or rag"],
        "parts": ["Replacement sprinkler head"],
        "safety": "LOW",
        "warnings": ["Call the utility locator before any deep digging", "Do not overtighten the new head — plastic threads crack easily"],
        "mall": "sprinkler head replacement",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Garden hose leaking at the coupling",
        "symptoms": ["Water sprays where the hose meets the spigot or nozzle", "Coupling wobbles or will not tighten", "Steady drip even when the connection looks tight"],
        "diagnosis": ["Turn off the spigot and unscrew the coupling", "Check the rubber washer — a flattened or missing washer is the number one cause", "Inspect the coupling for cracks and the threads for stripping"],
        "diy_title": "Replace the washer and reseat the coupling",
        "diy_steps": ["Turn off the spigot", "Unscrew the hose and pry out the old washer with a small screwdriver", "Press a new hose washer firmly into the coupling", "Check the threads — if stripped, replace the coupling with a hose repair coupling", "Hand-tighten, then snug a quarter turn with pliers", "Turn the water on and check for leaks"],
        "time": "10–20 min",
        "cost": "$2–$8",
        "difficulty": "Easy",
        "tools": ["Small flat screwdriver", "Pliers"],
        "parts": ["Hose washers", "Hose repair coupling (if needed)"],
        "safety": "LOW",
        "warnings": ["Do not overtighten — you will crush the new washer and cause the leak you just fixed"],
        "mall": "garden hose washer",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Gas grill will not light",
        "symptoms": ["Igniter clicks but no flame appears", "No click at all from the igniter", "Burners light then die out"],
        "diagnosis": ["Check the propane tank level and that the valve is open", "Check the igniter battery on push-button types", "Inspect the burner tubes for spider webs — extremely common in idle grills", "Suspect a tripped excess-flow valve if the grill worked before a tank swap"],
        "diy_title": "Clear the burners and reset the gas flow",
        "diy_steps": ["Turn all knobs OFF and close the tank valve", "Wait 5 minutes, then disconnect and reconnect the tank", "Open the tank valve SLOWLY, then open one burner knob and light it — this resets the excess-flow safety valve", "If there is still no flame, remove the burner tubes and clear spider webs with a bottle brush", "Replace the igniter battery if there is no spark", "If you ever smell gas with the knobs off, close the tank valve and call a pro — do not light"],
        "time": "30–60 min",
        "cost": "$3–$15",
        "difficulty": "Easy",
        "tools": ["Bottle brush or pipe cleaner", "Wrench"],
        "parts": ["Igniter battery", "Replacement burner tubes (if corroded through)"],
        "safety": "HIGH",
        "warnings": ["If you smell gas with the knobs off, close the tank valve and do NOT light it — call a professional", "Never light the grill with your face over the cooking surface", "Keep the lid open when lighting"],
        "mall": "grill burner tubes",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Fence gate sagging",
        "symptoms": ["Gate drags on the ground when swung", "Latch no longer catches", "Gap at the top is wider on the latch side"],
        "diagnosis": ["Check the hinge screws — stripped holes let the gate drop", "Check whether the hinge post itself leans", "Measure the gate's diagonals — a sagging gate has racked out of square"],
        "diy_title": "Square the gate and reinforce it",
        "diy_steps": ["Remove the gate from the hinges", "Check the hinge post for plumb — reset the post if it is leaning", "Repair stripped screw holes with wood glue and dowels, or drive longer screws into solid wood", "Install a diagonal brace or anti-sag gate kit from the bottom hinge corner to the top latch corner", "Rehang the gate, level it, and adjust the latch strike to meet"],
        "time": "1–2 hours",
        "cost": "$8–$25",
        "difficulty": "Moderate",
        "tools": ["Drill/driver", "Level", "Wrench"],
        "parts": ["Anti-sag gate kit or turnbuckle", "Longer hinge screws"],
        "safety": "MEDIUM",
        "warnings": ["Get help lifting a heavy gate — it can strain your back or pinch fingers", "Wear gloves when handling rough lumber"],
        "mall": "gate anti sag kit",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Uneven patio pavers",
        "symptoms": ["Pavers rock underfoot or sit higher than their neighbors", "Trip hazard at a raised edge", "Water pools on a sunken paver"],
        "diagnosis": ["Lift one paver and check the base — washed-out or uneven bedding sand is the usual cause", "Look for tree roots or settled soil underneath", "Check whether the edge restraint is still holding the border pavers"],
        "diy_title": "Lift, re-level, and reset the pavers",
        "diy_steps": ["Number the pavers with chalk so each goes back in its place", "Pry up the uneven pavers with a flat bar", "Remove or add bedding sand and tamp it level with a hand tamper", "Reset each paver, tapping it level with a rubber mallet", "Sweep polymeric joint sand into all the joints", "Mist lightly with water to set the sand per the bag directions"],
        "time": "1–3 hours",
        "cost": "$10–$30",
        "difficulty": "Moderate",
        "tools": ["Flat pry bar", "Hand tamper", "Rubber mallet", "Broom"],
        "parts": ["Bedding sand", "Polymeric joint sand"],
        "safety": "MEDIUM",
        "warnings": ["Lift with your legs — pavers are heavy", "Wear knee pads and gloves for the kneeling and lifting work"],
        "mall": "polymeric paver sand",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Outdoor GFCI outlet tripping",
        "symptoms": ["Outlet trips repeatedly and will not stay reset", "Trips only when something is plugged in", "Outlet will not reset at all"],
        "diagnosis": ["Unplug everything — if it resets, one device has the fault (plug them back one at a time)", "Open the weatherproof cover and check for moisture or insect nests", "Note the outlet's age — 15-plus years means it may simply be worn out"],
        "diy_title": "Dry it out, test it, or replace the GFCI",
        "diy_steps": ["Turn OFF the breaker for that circuit", "Unplug all loads from the outlet", "Open the weatherproof cover and check for moisture or nests — let it dry fully", "Turn the breaker back on, press TEST, then press RESET", "If it holds with no load but trips with a device, that device has a ground fault — repair or replace the device", "If the GFCI will not reset with nothing plugged in, replace it with an outdoor-rated GFCI"],
        "time": "30–60 min",
        "cost": "$0 to dry out, $15–$30 to replace",
        "difficulty": "Moderate",
        "tools": ["Non-contact voltage tester", "Screwdriver"],
        "parts": ["Outdoor-rated GFCI outlet (if replacing)"],
        "safety": "HIGH",
        "warnings": ["Always verify power is off with a tester before touching terminals — the breaker may be mislabeled", "If you are not comfortable working with 120V wiring, call an electrician", "Keep the in-use weatherproof cover closed when the outlet is in service"],
        "mall": "outdoor GFCI outlet",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Wheelbarrow flat tire",
        "symptoms": ["Tire will not hold air overnight", "Tube bulging out from under the tire bead", "Wheel wobbles on the axle"],
        "diagnosis": ["Inflate the tire and listen for where air escapes", "Check whether the tube is punctured or the tire itself is cut", "Check the wheel bearings while the wheel is off"],
        "diy_title": "Replace the tube or upgrade to a flat-free tire",
        "diy_steps": ["Flip the wheelbarrow and remove the axle bolts to take the wheel off", "Pry one side of the tire off the rim with tire levers", "Pull out the old tube and check the inside of the tire for thorns or nails", "Insert the new tube slightly inflated so it does not pinch", "Seat the tire bead evenly around the rim", "Inflate to the pressure printed on the sidewall and reinstall the wheel", "Or swap the whole wheel for a flat-free solid tire and never deal with flats again"],
        "time": "30–45 min",
        "cost": "$8–$25",
        "difficulty": "Easy",
        "tools": ["Wrench", "Tire levers or flat screwdrivers"],
        "parts": ["Replacement inner tube", "Flat-free wheelbarrow wheel (upgrade option)"],
        "safety": "LOW",
        "warnings": ["Do not overinflate — a tube can burst", "Keep fingers clear of the bead as it seats on the rim"],
        "mall": "wheelbarrow tire tube",
    },
    {
        "field": "Lawn & Outdoor",
        "title": "Pruning shears sticking",
        "symptoms": ["Blades stick or will not spring open", "Dried sap visible on the blades", "Action feels stiff and gritty"],
        "diagnosis": ["Check for dried sap caked on the blades", "Test the pivot bolt — too tight binds, too loose wobbles", "Inspect the spring for cracks or loss of tension"],
        "diy_title": "Clean, sharpen, and tune the pivot",
        "diy_steps": ["Wash the blades with warm soapy water and scrub off sap with a stiff brush", "Use rubbing alcohol for stubborn sap residue", "Dry the shears thoroughly", "Sharpen the beveled edge with a diamond file at the factory angle", "Adjust the pivot bolt so the blades glide without wobble", "Oil the pivot and spring lightly and store with the latch closed"],
        "time": "20–30 min",
        "cost": "$3–$10",
        "difficulty": "Easy",
        "tools": ["Stiff brush", "Diamond file", "Adjustable wrench"],
        "parts": ["Rubbing alcohol", "Light machine oil"],
        "safety": "LOW",
        "warnings": ["Cut away from your fingers when sharpening the blade", "Close the safety latch for storage"],
        "mall": "pruning shear sharpener",
    },
]
