# Seed data: Plumbing (16 records) — format reference for the archive.
PROBLEMS = [
    {
        "field": "Plumbing",
        "title": "Leaky faucet drips constantly",
        "symptoms": ["Drips even with the handle fully closed", "Drip speeds up over weeks", "Handle feels loose or gritty"],
        "diagnosis": ["Turn off the hot and cold shutoff valves under the sink", "Plug the drain so small parts cannot fall in", "Pry off the handle cap, remove the handle screw and handle", "Unscrew the packing nut and pull the stem or cartridge", "Inspect the rubber washer, O-ring, or cartridge for wear or cracks"],
        "diy_title": "Replace the washer, O-ring, or cartridge",
        "diy_steps": ["Take the old washer or cartridge to the hardware store to match it exactly", "Coat the new O-rings lightly with plumber's grease", "Install the new washer or cartridge and reassemble in reverse order", "Turn the water back on slowly and run the faucet to flush debris", "Check for leaks around the base and handle"],
        "time": "30–45 min",
        "cost": "$3–$20",
        "difficulty": "Easy",
        "tools": ["Adjustable wrench", "Screwdriver set", "Plumber's grease"],
        "parts": ["Matching washer, O-ring, or cartridge"],
        "safety": "LOW",
        "warnings": ["Confirm the water is off before disassembling — test by opening the faucet"],
        "mall": "faucet repair kit",
    },
    {
        "field": "Plumbing",
        "title": "Toilet runs constantly and won't stop filling",
        "symptoms": ["Water runs nonstop into the bowl or tank", "Tank never reaches the fill line", "Water bill climbing"],
        "diagnosis": ["Remove the tank lid and watch a full cycle", "Check whether water flows into the overflow tube nonstop", "Lift the float — if running stops, the fill valve is the issue", "Add food coloring to the tank; color in the bowl without flushing means the flapper leaks"],
        "diy_title": "Replace the flapper or the fill valve",
        "diy_steps": ["Turn off the toilet's shutoff valve and flush to empty the tank", "If the flapper is warped or slimy, unhook it and snap on a matching new one", "If the fill valve hisses constantly, unscrew it and install a universal replacement", "Set the water level about 2.5 cm below the top of the overflow tube", "Turn the water on, flush twice, and confirm the running stops"],
        "time": "20–40 min",
        "cost": "$5–$25",
        "difficulty": "Easy",
        "tools": ["Sponge and bucket", "Adjustable wrench"],
        "parts": ["Universal flapper or fill valve kit"],
        "safety": "LOW",
        "warnings": ["Tank water is clean supply water, but wash hands after"],
        "mall": "toilet repair kit",
    },
    {
        "field": "Plumbing",
        "title": "Clogged bathroom sink drains slowly",
        "symptoms": ["Water pools and drains slowly", "Gurgling sounds", "Bad odor from the drain"],
        "diagnosis": ["Pull out the pop-up stopper and clear visible hair", "Run hot water and watch the drain speed", "Check whether the tub or toilet on the same line is also slow (shared clog)"],
        "diy_title": "Clear the trap and snake the drain",
        "diy_steps": ["Remove the stopper and pull out hair with a drain claw tool", "Place a bucket under the sink and unscrew the P-trap by hand", "Empty the trap, scrub it clean, and reinstall with the washers seated", "If still slow, feed a 7-meter hand auger down the wall pipe until it breaks through", "Flush with very hot water for two minutes"],
        "time": "30–60 min",
        "cost": "$5–$30",
        "difficulty": "Easy",
        "tools": ["Drain claw tool", "Bucket", "Channel-lock pliers", "Hand auger"],
        "parts": ["Replacement P-trap washers (if cracked)"],
        "safety": "LOW",
        "warnings": ["Wear gloves — drain sludge is unpleasant", "Avoid chemical drain cleaners; they can damage pipes and burn skin"],
        "mall": "drain auger",
    },
    {
        "field": "Plumbing",
        "title": "Low water pressure at one faucet",
        "symptoms": ["Weak flow from a single faucet", "Other fixtures in the house are normal", "Sometimes sputtering"],
        "diagnosis": ["Check whether hot, cold, or both are weak", "Unscrew the aerator and run the faucet without it", "Inspect the aerator screen for grit and mineral buildup"],
        "diy_title": "Clean or replace the aerator and supply screens",
        "diy_steps": ["Unscrew the aerator from the spout tip (use a cloth to protect the finish)", "Rinse the screen and soak it in vinegar for 30 minutes to dissolve minerals", "Pick out debris with an old toothbrush and reassemble", "If flow is still weak, check the shutoff valve under the sink is fully open", "For single-handle faucets, the cartridge inlet screens may need cleaning too"],
        "time": "15–30 min",
        "cost": "$0–$10",
        "difficulty": "Easy",
        "tools": ["Cloth", "Small brush", "White vinegar"],
        "parts": ["Replacement aerator (if corroded)"],
        "safety": "LOW",
        "warnings": ["Do not overtighten the aerator — the threads strip easily"],
        "mall": "faucet aerator",
    },
    {
        "field": "Plumbing",
        "title": "Garbage disposal jammed and humming",
        "symptoms": ["Disposal hums but the blades don't spin", "Reset button may have popped", "Water sits in the sink"],
        "diagnosis": ["Turn the disposal switch OFF immediately", "Shine a light in and look for a lodged object (bone, bottle cap)", "Check the red reset button on the bottom of the unit"],
        "diy_title": "Free the flywheel with the hex wrench",
        "diy_steps": ["Switch the disposal OFF at the wall switch", "Insert the hex wrench into the socket on the bottom center and work it back and forth until the flywheel turns freely", "Reach in with tongs (never fingers) to pull out the lodged object", "Press the red reset button on the bottom", "Run cold water and switch on to test"],
        "time": "10–20 min",
        "cost": "$0",
        "difficulty": "Easy",
        "tools": ["Disposal hex wrench (usually taped to the unit)", "Tongs", "Flashlight"],
        "parts": [],
        "safety": "MEDIUM",
        "warnings": ["NEVER put your hand inside the disposal, even when it is off", "Always switch off at the wall before using the hex wrench"],
        "mall": "garbage disposal",
    },
    {
        "field": "Plumbing",
        "title": "No hot water from the water heater",
        "symptoms": ["All taps run cold", "Heater was working recently", "Pilot or breaker may be involved"],
        "diagnosis": ["For gas: check whether the pilot light is lit through the sight glass", "For electric: check the dedicated breaker in the panel", "Feel the hot outlet pipe — cold means the tank is not heating", "Check the thermostat setting (usually 50–60 °C)"],
        "diy_title": "Relight the pilot or reset the breaker and thermostat",
        "diy_steps": ["For gas: turn the gas control to PILOT, hold the button, and ignite per the label instructions", "For electric: flip the breaker fully off then on, then press the red reset button behind the upper access panel", "Set the thermostat to about 55 °C", "Wait one hour and test hot water at a tap", "If it trips again or the pilot will not stay lit, call a technician — the thermocouple or element has failed"],
        "time": "20–40 min",
        "cost": "$0–$30",
        "difficulty": "Moderate",
        "tools": ["Long lighter or match", "Screwdriver"],
        "parts": ["Thermocouple (if pilot won't stay lit)"],
        "safety": "HIGH",
        "warnings": ["If you smell gas, leave the house and call the gas company — do not relight anything", "Electric heaters carry 240 V — turn the breaker off before removing access panels", "Scalding risk: do not set the thermostat above 60 °C"],
        "mall": "water heater thermocouple",
    },
    {
        "field": "Plumbing",
        "title": "Pipe leaking under the kitchen sink",
        "symptoms": ["Puddle or dampness in the cabinet", "Musty smell", "Water stains on the cabinet floor"],
        "diagnosis": ["Dry everything and run the faucet to find the exact drip point", "Check the supply line connections first, then the drain slip nuts", "Look for green corrosion on copper or cracks in plastic traps"],
        "diy_title": "Tighten or replace the leaking connection",
        "diy_steps": ["Turn off the shutoff valves and place a bucket underneath", "For supply lines: tighten the compression nut a quarter turn, or replace a braided line if it is weeping", "For drain leaks: hand-tighten the slip nuts; replace cracked washers or the trap section", "Dry the cabinet, lay a paper towel down, and recheck after running water for a minute"],
        "time": "20–45 min",
        "cost": "$5–$25",
        "difficulty": "Easy",
        "tools": ["Adjustable wrench", "Bucket", "Towels"],
        "parts": ["Braided supply line or P-trap kit", "Slip-nut washers"],
        "safety": "LOW",
        "warnings": ["Do not overtighten plastic slip nuts — they crack"],
        "mall": "sink trap kit",
    },
    {
        "field": "Plumbing",
        "title": "Showerhead dripping or spraying sideways",
        "symptoms": ["Constant drip after the shower is off", "Sprays shoot sideways from clogged nozzles", "Weak overall flow"],
        "diagnosis": ["Check whether the drip stops after a few minutes (normal residual) or continues for hours", "Look for mineral crust on the nozzles", "Unscrew the showerhead and check the washer and pipe threads"],
        "diy_title": "Descale the showerhead and replace the washer",
        "diy_steps": ["Unscrew the showerhead by hand or with a cloth-wrapped wrench", "Soak it in white vinegar for one hour, then scrub the nozzles with a brush", "Replace the rubber washer inside the coupling nut", "Wrap the shower arm threads with 3–4 turns of PTFE tape clockwise", "Reinstall hand-tight plus a quarter turn and test"],
        "time": "20–30 min",
        "cost": "$2–$15",
        "difficulty": "Easy",
        "tools": ["Adjustable wrench", "Cloth", "PTFE tape"],
        "parts": ["Rubber washer", "PTFE thread tape"],
        "safety": "LOW",
        "warnings": ["Protect chrome finishes with a cloth before using a wrench"],
        "mall": "showerhead",
    },
    {
        "field": "Plumbing",
        "title": "Toilet leaking at the base onto the floor",
        "symptoms": ["Water pools around the toilet base after flushing", "Floor feels soft or stained nearby", "Sewer odor"],
        "diagnosis": ["Confirm the water comes from the base, not the tank or supply line", "Check whether the toilet rocks when you push it gently", "A rocking toilet almost always means a failed wax ring"],
        "diy_title": "Reset the toilet on a new wax ring",
        "diy_steps": ["Turn off the water, flush, and sponge out the tank and bowl", "Disconnect the supply line and unbolt the toilet from the flange", "Lift the toilet straight up and set it on old towels", "Scrape off the old wax ring and press a new one onto the flange", "Set the toilet straight down, tighten bolts evenly, reconnect water, and test flush twice"],
        "time": "1–2 hours",
        "cost": "$8–$25",
        "difficulty": "Moderate",
        "tools": ["Adjustable wrench", "Putty knife", "Gloves", "Old towels"],
        "parts": ["Wax ring with flange", "New closet bolts"],
        "safety": "MEDIUM",
        "warnings": ["Toilets are heavy and awkward — get help lifting", "Wear gloves; old wax rings are unsanitary", "Do not overtighten the bolts or the porcelain can crack"],
        "mall": "toilet wax ring",
    },
    {
        "field": "Plumbing",
        "title": "Bathtub drains very slowly",
        "symptoms": ["Standing water during showers", "Drain gurgles", "Hair visible around the drain"],
        "diagnosis": ["Remove the drain cover or stopper and clear surface hair", "Run water and time how fast it drains", "If a plunger doesn't help, the clog is deeper in the line"],
        "diy_title": "Clear the drain with a claw tool and plunger",
        "diy_steps": ["Pull the stopper assembly and remove all hair with a drain claw", "Fill the tub with 5 cm of water and plunge vigorously 15–20 times", "If still slow, feed a hand auger through the overflow opening", "Flush with very hot water for several minutes", "Install a mesh hair catcher to prevent repeats"],
        "time": "20–40 min",
        "cost": "$5–$25",
        "difficulty": "Easy",
        "tools": ["Drain claw", "Cup plunger", "Hand auger"],
        "parts": ["Mesh drain hair catcher"],
        "safety": "LOW",
        "warnings": ["Wear gloves when pulling hair from drains"],
        "mall": "tub drain hair catcher",
    },
    {
        "field": "Plumbing",
        "title": "Outdoor spigot leaks when turned on",
        "symptoms": ["Water sprays from around the handle", "Drips from the spout after shutoff", "Handle is hard to turn"],
        "diagnosis": ["Check whether the leak is at the handle packing or the spout", "Look for a cracked vacuum breaker cap on top", "Test whether the shutoff inside the house fully stops flow"],
        "diy_title": "Repack the stem or replace the vacuum breaker",
        "diy_steps": ["Turn off the interior shutoff valve for the spigot", "Unscrew the packing nut behind the handle and wrap the stem with packing string or replace the packing washer", "Tighten the packing nut snugly — firm, not crushed", "If the cap on top leaks, unscrew it and thread on a new vacuum breaker", "Turn the water back on and check both spots"],
        "time": "20–30 min",
        "cost": "$3–$12",
        "difficulty": "Easy",
        "tools": ["Adjustable wrench", "Screwdriver"],
        "parts": ["Packing string or washer", "Hose bibb vacuum breaker"],
        "safety": "LOW",
        "warnings": ["In freezing climates, shut off and drain outdoor spigots before winter"],
        "mall": "outdoor faucet repair kit",
    },
    {
        "field": "Plumbing",
        "title": "Dishwasher not draining — standing water inside",
        "symptoms": ["Pool of water in the tub bottom after a cycle", "Dishes still dirty", "Humming during drain cycle"],
        "diagnosis": ["Check the drain filter at the tub bottom for food debris", "Look at the air gap cap on the sink (if present) for clogs", "Inspect the drain hose under the sink for kinks"],
        "diy_title": "Clean the filter, air gap, and drain hose",
        "diy_steps": ["Twist out the lower filter assembly and scrub it clean", "Pop the air gap cap off and clear any debris inside", "Straighten any kink in the drain hose under the sink", "Run a hot empty cycle with a cup of vinegar on the top rack", "If it still won't drain, the drain pump may have failed — call for service"],
        "time": "25–45 min",
        "cost": "$0–$10",
        "difficulty": "Easy",
        "tools": ["Screwdriver", "Towels", "White vinegar"],
        "parts": [],
        "safety": "LOW",
        "warnings": ["Turn off the dishwasher breaker before reaching near the pump area"],
        "mall": "dishwasher cleaner",
    },
    {
        "field": "Plumbing",
        "title": "Washing machine leaking water on the floor",
        "symptoms": ["Water puddles during fill or drain", "Hoses look old or bulging", "Leak only on certain cycles"],
        "diagnosis": ["Pull the machine out and watch a full cycle", "Check the inlet hose connections at the wall first", "Inspect the drain hose — it must stand in the standpipe, not be sealed airtight", "Look under the machine for a cracked pump or tub seal drip"],
        "diy_title": "Replace hoses and reseat the drain hose",
        "diy_steps": ["Turn off both water valves and unplug the machine", "Replace old rubber inlet hoses with braided stainless lines, hand-tight plus a quarter turn", "Reseat the drain hose 15–20 cm into the standpipe and secure it loosely", "Level the machine with a spirit level to stop vibration leaks", "Run an empty cycle and watch every connection"],
        "time": "30–60 min",
        "cost": "$15–$40",
        "difficulty": "Easy",
        "tools": ["Adjustable wrench", "Pliers", "Spirit level", "Bucket and towels"],
        "parts": ["Braided stainless inlet hoses (pair)"],
        "safety": "LOW",
        "warnings": ["Replace rubber hoses every 5 years — burst hoses flood homes", "Machines are heavy; get help pulling it out"],
        "mall": "washing machine hoses",
    },
    {
        "field": "Plumbing",
        "title": "Sump pump not turning on during rain",
        "symptoms": ["Pit filling with water", "Pump silent when the float rises", "Basement dampness spreading"],
        "diagnosis": ["Check the pump is plugged into a live outlet", "Lift the float switch by hand — the pump should kick on", "Look for a stuck float tangled in debris or the discharge pipe"],
        "diy_title": "Free the float switch and verify the discharge",
        "diy_steps": ["Unplug the pump and clear debris from the pit", "Free the float so it moves up and down without catching", "Pour a bucket of water in and confirm the pump activates and empties the pit", "Check the outside discharge pipe is clear and draining away from the house", "If the motor hums but won't pump, the impeller is jammed or the pump is dead — replace it"],
        "time": "20–40 min",
        "cost": "$0–$180",
        "difficulty": "Moderate",
        "tools": ["Bucket", "Gloves", "Flashlight"],
        "parts": ["Replacement sump pump (if motor failed)"],
        "safety": "MEDIUM",
        "warnings": ["Keep the pump on a GFCI-protected outlet", "Never handle a pump standing in water while it is plugged in"],
        "mall": "sump pump",
    },
    {
        "field": "Plumbing",
        "title": "Frozen pipe — no water in winter",
        "symptoms": ["No water or a trickle from a faucet in freezing weather", "Pipe feels icy in an exterior wall or crawlspace", "Frost visible on the pipe"],
        "diagnosis": ["Open the faucet slightly to relieve pressure", "Find the frozen section by feeling along the pipe for the coldest spot", "Check for any bulging or cracks — a burst pipe needs a plumber immediately"],
        "diy_title": "Thaw the pipe slowly and safely",
        "diy_steps": ["Open the faucet a trickle so melting water has somewhere to go", "Apply gentle heat with a hair dryer, moving constantly along the frozen section", "Work from the faucet end back toward the coldest spot", "Once flowing, let it run for several minutes, then insulate the pipe", "If the pipe is burst or you cannot find the freeze, shut the main valve and call a plumber"],
        "time": "30–90 min",
        "cost": "$5–$25",
        "difficulty": "Moderate",
        "tools": ["Hair dryer", "Towels", "Pipe insulation sleeves"],
        "parts": ["Foam pipe insulation", "Heat tape (for repeat problem spots)"],
        "safety": "MEDIUM",
        "warnings": ["NEVER use an open flame or torch on a pipe", "If a pipe burst, shut the main water valve first, then call a plumber"],
        "mall": "pipe insulation",
    },
    {
        "field": "Plumbing",
        "title": "Toilet won't flush — handle feels loose",
        "symptoms": ["Handle flops with no resistance", "Nothing happens when pressed", "Tank full of water"],
        "diagnosis": ["Lift the tank lid and press the handle while watching", "The lift chain has usually slipped off the flapper or broken", "Check the handle arm itself for cracks"],
        "diy_title": "Reconnect or replace the flapper chain",
        "diy_steps": ["Hook the chain back onto the flush lever arm with 1–2 cm of slack", "If the chain is broken or rusted, clip on a universal replacement chain", "If the handle arm is cracked, unscrew the retaining nut (reverse thread) and install a new handle", "Flush three times to confirm a full strong flush"],
        "time": "10–20 min",
        "cost": "$3–$12",
        "difficulty": "Easy",
        "tools": [],
        "parts": ["Universal toilet chain or handle kit"],
        "safety": "LOW",
        "warnings": ["Wash hands after working inside the tank"],
        "mall": "toilet handle kit",
    },
]
