# The Signature Mr Fix-It — seed data (batch: Bee)
# Fields: Computers & Cyber, Phones & Tablets, Vintage Electronics, Chips & Circuit Boards

PROBLEMS = [
    {
        'field': 'Computers & Cyber',
        'title': "PC won't boot — no power at all",
        'symptoms': ['Pressing the power button does nothing', 'No lights, no fans, no beeps', 'Was working fine yesterday'],
        'diagnosis': ['Confirm the wall outlet works by plugging in another device', 'Check the power cable is firmly seated at both the wall and the PC', 'Flip the PSU rocker switch on the back of the PC to the ON position', 'Try a different power cable and a different wall outlet', 'Look for any motherboard LEDs or listen for beeps when you press power'],
        'diy_title': 'Isolate the power path and reseat connections',
        'diy_steps': ['Unplug the PC, then hold the power button for 15 seconds to drain residual power', 'Open the case and reseat the 24-pin and CPU power cables on the motherboard', 'Remove all USB devices except keyboard and mouse, then try booting again', 'If still dead, test with a known-good power supply or have the PSU tested at a shop', 'If the PSU is good but nothing powers on, the motherboard is suspect — take it to a repair shop'],
        'time': '30–60 min',
        'cost': '$0–$80',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Flashlight'],
        'parts': ['Replacement PSU (if testing confirms failure)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug from the wall before opening the case', 'Power supplies hold charge — never open the PSU box itself'],
        'mall': 'power supply tester',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Blue screen crashes during normal use',
        'symptoms': ['The screen turns blue with an error message and restarts', 'Crashes happen randomly or when doing one specific task', 'The PC worked fine until recently'],
        'diagnosis': ['Write down the stop code shown (for example MEMORY_MANAGEMENT or DRIVER_IRQL_NOT_LESS_OR_EQUAL)', 'Think about what changed before crashes started — new hardware, drivers, or updates', 'Open Event Viewer and look for critical errors stamped at the crash times', 'Run the built-in memory test (search for Windows Memory Diagnostic)', 'Boot into Safe Mode — if crashes stop there, a driver or startup program is the cause'],
        'diy_title': 'Fix the bad driver and test the memory',
        'diy_steps': ['Open Device Manager and look for devices with a yellow warning icon', "Update any flagged drivers from the hardware maker's own website, not random download sites", 'If a crash started after a driver update, right-click the device and choose Roll Back Driver', 'Uninstall any software added right before the crashes began', 'Run the full Windows Memory Diagnostic; if it finds bad RAM, reseat the memory sticks', 'As a last resort, reinstall the operating system after a full backup'],
        'time': '45–90 min',
        'cost': '$0–$60',
        'difficulty': 'Moderate',
        'tools': ['USB flash drive (for backup)', 'Phillips screwdriver (if reseating RAM)'],
        'parts': ['Replacement RAM stick (only if the memory test fails)'],
        'safety': 'MEDIUM',
        'warnings': ['Back up your files before reinstalling the operating system or swapping memory', "Only download drivers from the hardware maker's official site"],
        'mall': 'computer memory RAM',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Computer running very slowly',
        'symptoms': ['Programs take a long time to open', 'The hard drive light is on constantly', 'Boot-up takes several minutes'],
        'diagnosis': ['Open Task Manager and check which program is eating the CPU, memory, or disk', 'Check how many programs launch at startup', 'Check free disk space — less than 15–20 percent free hurts performance', 'Note whether slowness started after an update or a new program install'],
        'diy_title': 'Trim startup programs, free space, and scan for junk',
        'diy_steps': ["In Task Manager's Startup tab, disable programs you do not need at boot", 'Uninstall programs you never use from Settings > Apps', 'Delete large unused files and empty the Recycle Bin until at least 20 percent of the disk is free', 'Run a full scan with your built-in antivirus', 'If the disk is a spinning hard drive, upgrading to an SSD is the single biggest speedup'],
        'time': '45–90 min',
        'cost': '$0–$80',
        'difficulty': 'Easy',
        'tools': ['None required', 'External drive (for backup before big changes)'],
        'parts': ['SSD upgrade (optional, for a real speed boost)'],
        'safety': 'LOW',
        'warnings': ['Back up important files before uninstalling programs or changing the system'],
        'mall': 'laptop SSD drive',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'No WiFi connection on the computer',
        'symptoms': ['The WiFi icon shows no connection or limited access', 'Other devices may connect fine — the problem is this computer', 'It was connected before'],
        'diagnosis': ['Check whether the physical WiFi switch or function key is turned off', 'Check that Airplane Mode is off', 'Restart the router and the computer — this fixes it more often than not', 'See if the network appears at all, or appears but rejects the password', 'Check Device Manager for a warning icon on the wireless adapter'],
        'diy_title': 'Restart the network path, then rejoin and refresh the driver',
        'diy_steps': ['Unplug the router for 30 seconds, plug it back in, and wait two minutes', 'Toggle Airplane Mode on and back off on the computer', 'Forget the network (Settings > Network), then reconnect and retype the password carefully', "Update the wireless adapter driver from the computer maker's support site", 'If nothing works, reset network settings (Settings > Network > Network reset) and reconnect'],
        'time': '15–30 min',
        'cost': '$0–$25',
        'difficulty': 'Easy',
        'tools': ['Ethernet cable (for testing the wired connection)', 'Phone with mobile data (to look up steps if needed)'],
        'parts': ['USB WiFi adapter (if the built-in adapter is dead)'],
        'safety': 'LOW',
        'warnings': ["Only open the router's admin page via the address on its label — never a link from a search ad"],
        'mall': 'WiFi USB adapter',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Printer not printing anything',
        'symptoms': ['Print jobs sit in the queue and never come out', 'The printer shows an error light or message', 'Pages come out blank or badly faded'],
        'diagnosis': ['Confirm the printer is powered on and connected (cable or WiFi)', 'Check paper is loaded and ink or toner levels are not empty', 'Confirm the right printer is set as the default', 'Look at the print queue for a stuck job blocking everything', "Print a test page from the printer's own menu to separate printer faults from computer faults"],
        'diy_title': 'Clear the queue, check supplies, refresh the driver',
        'diy_steps': ['Turn the printer off for 30 seconds, then back on, and check the cable or WiFi connection', 'Open the print queue and cancel all stuck documents', "Refill or replace empty ink or toner; run the printer's head-cleaning cycle from its maintenance menu", 'Set the correct printer as default in Settings > Printers', "Print a test page from the printer's own panel — if that works, reinstall the printer driver on the computer"],
        'time': '20–40 min',
        'cost': '$0–$40',
        'difficulty': 'Easy',
        'tools': ['None required', 'Printer manual (for the maintenance menu)'],
        'parts': ['Ink or toner cartridge (if empty)'],
        'safety': 'LOW',
        'warnings': ['Unplug the printer before clearing a deep paper jam by hand'],
        'mall': 'printer ink cartridge',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Malware popups claiming the computer is infected',
        'symptoms': ['Popups warn the computer is infected and urge you to call a number', 'Ads appear even when the browser is closed', 'The browser homepage changed by itself'],
        'diagnosis': ['Do NOT call any phone number shown in a popup — legitimate warnings never include one', 'Disconnect the internet to stop further damage while you clean', 'Check the installed-programs list for entries you do not recognize', 'Check the browser for extensions you did not add'],
        'diy_title': 'Disconnect, scan in safe mode, and remove the junk',
        'diy_steps': ['Disconnect from WiFi or unplug the network cable', 'Restart into Safe Mode with Networking', 'Run a full scan with the built-in antivirus, then a second scan with a reputable on-demand scanner', 'Uninstall any programs you do not recognize from Settings > Apps', 'Remove unknown browser extensions and reset the browser to its default settings', 'From a clean device, change important passwords (email, banking) in case keystrokes were captured'],
        'time': '1–2 hr',
        'cost': '$0–$40',
        'difficulty': 'Moderate',
        'tools': ['USB flash drive (for backup)', 'A second clean device (for password changes)'],
        'parts': ['Reputable antivirus or malware scanner (many good free options exist)'],
        'safety': 'MEDIUM',
        'warnings': ["Never call the phone number in a scare popup and never pay for 'support' it offers", 'Do not enter card details into any popup security offer'],
        'mall': 'antivirus software',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Laptop running hot and shutting down',
        'symptoms': ['The fan runs loud constantly', 'The laptop feels very hot under the keyboard', 'It shuts off suddenly during heavy use'],
        'diagnosis': ['Check whether vents on the bottom or side are blocked by a bed, couch, or lap', 'Install a temperature monitor and note the CPU temperature at idle and under load', 'Listen for the fan — silence under load can mean a dead fan', 'Check whether the problem started after heavy dust buildup or a hot summer'],
        'diy_title': 'Clear the vents, improve airflow, refresh the thermal paste',
        'diy_steps': ['Shut down and unplug the laptop, and remove the battery if it is removable', 'Blow dust out of the vents with short bursts of compressed air, holding the can upright', 'Always use the laptop on a hard flat surface so the vents can breathe', 'Use a laptop cooling stand during heavy work', 'If it is still hot, have the thermal paste between the CPU and heatsink replaced — a shop can do this cheaply if you are not comfortable opening the laptop'],
        'time': '30–60 min',
        'cost': '$0–$50',
        'difficulty': 'Moderate',
        'tools': ['Compressed air can', 'Phillips screwdriver', 'Plastic pry tool'],
        'parts': ['Thermal paste', 'Laptop cooling stand'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug the laptop and remove the battery if possible before opening it', 'Compressed air cans spray freezing liquid if tilted — keep the can upright', 'Let the machine cool fully before touching the heatsink'],
        'mall': 'laptop cooling pad',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'No sound coming from the computer',
        'symptoms': ['No sound from speakers or headphones', 'The volume icon shows muted or has an error mark', 'Sound was working before'],
        'diagnosis': ['Check the volume slider and that nothing is muted', 'Check which output device is selected — the sound may be going to a monitor or TV', 'Plug headphones in — if they work, the speakers are the problem', 'Open Device Manager and check the audio device for a warning icon'],
        'diy_title': 'Unmute, pick the right output, and refresh the audio driver',
        'diy_steps': ['Unmute the volume and raise it above 50 percent', 'Right-click the volume icon, open Sound settings, and select the correct output device', 'Test with headphones to find out whether the speakers themselves are dead', 'Restart the Windows Audio service (services.msc) or simply restart the computer', 'Uninstall the audio driver in Device Manager and restart — it will reinstall automatically', 'If a test beep at startup is also silent, the speakers or sound hardware are faulty'],
        'time': '15–30 min',
        'cost': '$0–$30',
        'difficulty': 'Easy',
        'tools': ['Headphones (for testing)', 'Flashlight (to see rear audio jacks)'],
        'parts': ['USB sound adapter (if the built-in audio is dead)'],
        'safety': 'LOW',
        'warnings': ['Keep the volume moderate when testing speakers to avoid sudden loud blasts'],
        'mall': 'USB sound adapter',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Monitor shows no signal',
        'symptoms': ['The monitor says No Signal and then sleeps', 'The PC sounds like it powers on normally', 'It worked before with this same setup'],
        'diagnosis': ["Check the monitor's input source — it may be set to the wrong HDMI or DisplayPort input", 'Check the cable is firmly plugged in at both the monitor and the PC', 'Listen for the normal boot beeps to confirm the PC itself is fine', 'Try the monitor with another computer, or another monitor with this PC'],
        'diy_title': 'Check inputs and cables, then reseat the graphics hardware',
        'diy_steps': ["Press the monitor's input/source button and select the input your cable is plugged into", 'Unplug and firmly reseat the video cable at both ends; try a different cable if you have one', 'Shut down, unplug the PC, open the case, and reseat the graphics card and memory sticks', 'If the motherboard has onboard video, plug the monitor there to test whether the graphics card is dead', 'If the monitor is dark on a known-good computer, the monitor itself needs repair or replacement'],
        'time': '20–45 min',
        'cost': '$0–$60',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Spare video cable (for testing)'],
        'parts': ['Replacement HDMI or DisplayPort cable'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug the PC from the wall before opening the case', 'Ground yourself by touching the metal case before touching components'],
        'mall': 'HDMI cable',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Keyboard not responding at all',
        'symptoms': ['No keys register when typing', 'The Caps Lock light does not change when pressed', 'It may work in the startup menus but not in the operating system, or the reverse'],
        'diagnosis': ['Unplug and replug the keyboard, or try a different USB port', 'Test the keyboard on another computer to find out whether it is the keyboard or the PC', 'Restart and enter the BIOS or setup screen — if keys work there, the hardware is fine and it is a software problem', 'For a wireless keyboard, check the receiver is plugged in and the batteries are fresh'],
        'diy_title': 'Rule out the port and the connection, then refresh the driver',
        'diy_steps': ['Unplug the keyboard, wait 10 seconds, plug it into a different USB port, and wait for the driver to load', 'For a wireless keyboard, replace the batteries and reseat the USB receiver', 'Restart the computer and test the keyboard in the BIOS or startup menu', 'In Device Manager, uninstall the keyboard driver and restart — it reinstalls automatically', 'If some keys stick or repeat, turn the keyboard upside down and shake out debris, then blow it out with compressed air'],
        'time': '10–25 min',
        'cost': '$0–$30',
        'difficulty': 'Easy',
        'tools': ['Compressed air can', 'Small soft brush'],
        'parts': ['Replacement keyboard (if it fails on a second computer)'],
        'safety': 'LOW',
        'warnings': ['Do not pry keys off a laptop keyboard — the clips break easily'],
        'mall': 'wired USB keyboard',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Hard drive making clicking sounds',
        'symptoms': ['Clicking or ticking sounds come from the drive', 'Files take a very long time to open', 'The drive sometimes disappears from the computer'],
        'diagnosis': ['Identify which drive is clicking — the sound comes from a spinning hard drive, not an SSD', "Check the drive's health with a SMART monitoring tool", 'Note any error messages about bad sectors or drive failure', 'Accept that a clicking drive is failing — this is a rescue mission, not a repair'],
        'diy_title': 'Back up immediately, then clone and replace the drive',
        'diy_steps': ['Stop using the computer for anything except the backup — every minute of spinning risks more loss', 'Copy your most important files to an external drive right now, most important first', 'If the drive still reads, clone it to a new drive with a disk-cloning tool', 'Install the new drive as the replacement and restore from the clone or backup', 'If the drive will not read at all and the data is critical, stop and send it to a professional data recovery service'],
        'time': '2–6 hr',
        'cost': '$50–$150',
        'difficulty': 'Moderate',
        'tools': ['External hard drive (for the backup)', 'Phillips screwdriver', 'USB-to-SATA adapter (optional, for cloning)'],
        'parts': ['New hard drive or SSD'],
        'safety': 'MEDIUM',
        'warnings': ['This drive is dying — back up before doing any other step', 'Do not run disk-repair or defrag tools on it before the backup; they stress a failing drive', 'Never open the drive itself outside a clean room — dust kills it instantly'],
        'mall': 'external hard drive',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'USB device not recognized by the computer',
        'symptoms': ['Plugging in a USB device does nothing', 'An error says the USB device is not recognized', 'The device works on another computer'],
        'diagnosis': ['Try the device in a different USB port — front-panel ports fail more often than rear ones', 'Try a different cable if the device uses a detachable one', 'Try the device on another computer to find out whether the device or the PC is at fault', 'Check Device Manager for an Unknown USB Device entry with a warning icon'],
        'diy_title': 'Isolate the port, cable, and driver',
        'diy_steps': ['Unplug the device, restart the computer, then plug it into a rear USB port', 'Try a different cable — charging-only cables without data wires cause this exact symptom', 'In Device Manager, right-click the Unknown USB Device and choose Uninstall device, then unplug and replug', 'Turn off USB selective suspend in Power Options > Advanced settings', 'If the device fails on two computers, the device itself is faulty'],
        'time': '15–30 min',
        'cost': '$0–$15',
        'difficulty': 'Easy',
        'tools': ['None required', 'Second computer (for testing)'],
        'parts': ['Replacement USB cable (data-capable)'],
        'safety': 'LOW',
        'warnings': ['Do not force a USB plug — it only fits one way'],
        'mall': 'USB data cable',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Web browser hijacked by unwanted extensions',
        'symptoms': ['The homepage or search engine changed without permission', 'New toolbars or extensions appeared that you did not install', 'Searches redirect to strange websites'],
        'diagnosis': ['List the browser extensions and flag anything you did not install yourself', 'Check the installed-programs list for bundled junk added recently', "Check whether the browser's shortcut target was modified (right-click > Properties)", 'Run a malware scan — hijackers often arrive with adware'],
        'diy_title': 'Remove the extensions, reset the browser, clean the system',
        'diy_steps': ['Open the extensions page and remove everything you did not deliberately install', 'Reset the browser settings to default (this restores the homepage and search engine)', 'Uninstall suspicious recently-added programs from Settings > Apps', 'Run a full malware scan with your antivirus and a reputable on-demand scanner', 'If passwords were typed while the hijacker was active, change them from a clean device'],
        'time': '30–60 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['None required', 'A second clean device (for password changes)'],
        'parts': ['None required'],
        'safety': 'MEDIUM',
        'warnings': ["Do not click 'remove virus' ads or offers inside the hijacked browser", 'Change important passwords from a clean device if the hijacker was active for a while'],
        'mall': 'antivirus software',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Computer freezes randomly and needs a hard restart',
        'symptoms': ['The screen freezes and the mouse stops moving', 'It happens at random times, not with one program', 'Only holding the power button recovers it'],
        'diagnosis': ['Check Event Viewer for errors logged just before each freeze', 'Note whether freezes happen under heavy load (heat) or at idle (driver or memory)', 'Boot into Safe Mode — if it never freezes there, a driver or startup program is suspect', 'Run a memory test and check CPU temperatures'],
        'diy_title': 'Cool it down, test the memory, refresh drivers',
        'diy_steps': ['Shut down, unplug, and blow dust out of the fans and heatsinks with compressed air', 'Run the built-in memory diagnostic; if errors appear, reseat or replace the RAM', "Update the graphics and chipset drivers from the hardware maker's site", 'Run a disk check (chkdsk) to rule out file-system corruption', 'Undo any recent hardware or driver changes', 'If freezes continue with clean drivers and good RAM, a fresh operating-system install is the last resort after backup'],
        'time': '1–2 hr',
        'cost': '$0–$60',
        'difficulty': 'Moderate',
        'tools': ['Compressed air can', 'Phillips screwdriver'],
        'parts': ['Replacement RAM (only if the memory test fails)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug before opening the case', 'Back up your files before any operating-system reinstall'],
        'mall': 'compressed air duster',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Email account hacked and sending spam',
        'symptoms': ['Contacts received spam or scams from your address', 'You cannot log in because the password was changed', 'Login alerts arrive from places you have never been'],
        'diagnosis': ['Confirm it is your account, not a spoofed lookalike address', "Check whether you can still reach the provider's account-recovery page", 'List every place the account is used — banking, shopping, social media — for follow-up password changes', 'Check your own devices for malware that may have stolen the password'],
        'diy_title': 'Recover the account through the provider, then lock it down',
        'diy_steps': ["Go to your email provider's official account-recovery page (type the address yourself, do not click email links) and prove you are the owner", 'Set a new, unique password from a device you trust is clean', 'Turn on two-factor authentication immediately', "Check the account's forwarding rules, filters, and recovery email and phone number — attackers add their own", 'Scan your devices for malware, then change passwords on other sites that shared the old password', 'Warn your contacts not to open the spam messages'],
        'time': '30–90 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['A second device you trust (phone or another computer)', 'Pen and paper (to list every account tied to the email)'],
        'parts': ['None required'],
        'safety': 'MEDIUM',
        'warnings': ['Recover the account fast — the longer you wait, the more the attacker can lock you out', "Only use the provider's real recovery page; phishing copies of it are common", "Never pay anyone who offers to 'recover' the account for you"],
        'mall': 'security key token',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Forgotten login password and locked out of the computer',
        'symptoms': ['The login screen rejects the password', 'The password hint does not help', 'There is no other account to log in with'],
        'diagnosis': ['Check whether it is a Microsoft or Apple online account — those reset over the internet', 'Check whether you made a password reset disk or USB earlier', 'Check whether any other user account on the PC has administrator rights', 'Confirm this is your own computer — only ever reset your own account on your own machine'],
        'diy_title': 'Use the legitimate reset path for your account type',
        'diy_steps': ["For an online-linked account, go to the provider's password-reset page from another device and follow the verification steps", 'At the login screen, click the password hint and try every variation you might have used', 'If another administrator account exists on the PC, log in with it and reset your password in user settings', 'If you made a password reset disk, plug it in and follow the reset wizard', 'As a last resort, reinstall the operating system — this erases everything, so treat it as final'],
        'time': '20–60 min',
        'cost': '$0–$0',
        'difficulty': 'Moderate',
        'tools': ['Another device with internet (for online-account reset)', 'Password reset USB (if you made one)'],
        'parts': ['None required'],
        'safety': 'MEDIUM',
        'warnings': ['Reinstalling erases all files — try every other option first', 'Only reset your own account on your own computer', 'Write the new password down somewhere safe this time'],
        'mall': 'password manager',
    },
    {
        'field': 'Computers & Cyber',
        'title': "Programs won't open or crash on launch",
        'symptoms': ['Double-clicking a program does nothing or it closes instantly', 'An error message appears on launch', 'Other programs still work fine'],
        'diagnosis': ['Read the exact error message — it often names the missing file or cause', 'Check whether the program needs an update for your operating-system version', 'Try right-clicking and choosing Run as administrator', 'Check free disk space — some programs fail silently when the disk is full'],
        'diy_title': 'Repair, reinstall, or fix the system files underneath',
        'diy_steps': ['Restart the computer — a stuck background process is the most common cause', 'Right-click the program and choose Run as administrator', 'Check for updates to the program and install them', 'Uninstall the program completely, restart, then install a fresh copy from the official source', 'Run System File Checker: open a command prompt as administrator and type sfc /scannow', 'If only one user account is affected, create a new user profile — corrupted profiles break programs'],
        'time': '30–60 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['None required', 'USB flash drive (for backup)'],
        'parts': ['None required'],
        'safety': 'LOW',
        'warnings': ["Back up the program's data and settings before uninstalling it"],
        'mall': 'external hard drive',
    },
    {
        'field': 'Computers & Cyber',
        'title': 'Webcam not working in video calls',
        'symptoms': ['Video apps say no camera is found', 'The camera image is black or frozen', 'The camera light never turns on'],
        'diagnosis': ['Check for a physical privacy shutter or lens cover slid over the camera', "Check the app's permission to use the camera in system privacy settings", 'Test the camera in a different app to find out whether it is one app or the whole system', 'Check Device Manager for the camera with a warning icon'],
        'diy_title': 'Uncover the lens, fix permissions, refresh the driver',
        'diy_steps': ['Slide open any physical privacy shutter and remove any lens cover or sticker', 'Open system privacy settings and make sure camera access is allowed for the app', 'Close other programs that might be holding the camera (only one app can use it at a time)', "Test in a second app — if it works there, the first app's settings are the problem", 'In Device Manager, uninstall the camera driver and restart so it reinstalls', 'Check your antivirus — some block the camera and need an exception for your video app'],
        'time': '15–30 min',
        'cost': '$0–$40',
        'difficulty': 'Easy',
        'tools': ['Microfiber cloth (to clean the lens)', 'Small mirror (to check the shutter position)'],
        'parts': ['USB webcam (if the built-in camera is dead)'],
        'safety': 'LOW',
        'warnings': ['Cover the camera when not in use if you are concerned about privacy'],
        'mall': 'USB webcam',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Cracked phone screen',
        'symptoms': ['Spiderweb cracks across the glass', 'Touch still works in most areas, or is dead in spots', 'Small glass shards may be lifting at the edges'],
        'diagnosis': ['Test every part of the screen — dead touch zones mean the digitizer is broken, not just the glass', 'Check for discoloration, lines, or black spots, which mean the display panel itself is damaged', 'Decide whether the phone is worth a DIY screen replacement based on its age and value', 'Back up the phone before any repair — you will be opening it'],
        'diy_title': 'Stabilize the glass and replace the screen assembly',
        'diy_steps': ['Back up everything, power the phone off, and lay clear packing tape over the cracks to hold the glass and prevent cuts', 'Order a screen replacement kit made for your exact phone model, with tools included', 'Follow a model-specific teardown guide: remove the screws, heat the edges to soften the adhesive, and lift the old screen slowly', 'Disconnect the battery connector first, before touching any other ribbon cable', 'Transfer the earpiece, sensors, and home button to the new screen if the kit requires it', 'Connect the new screen and test it fully before sealing the phone shut'],
        'time': '1–2 hr',
        'cost': '$20–$80',
        'difficulty': 'Hard',
        'tools': ['Small precision screwdriver set', 'Plastic pry tools and spudger', 'Suction cup', 'Hair dryer or heat gun (low heat)', 'Tweezers'],
        'parts': ['Screen replacement kit for your exact model', 'Replacement adhesive strips'],
        'safety': 'MEDIUM',
        'warnings': ['Wear gloves — cracked glass cuts easily', 'Disconnect the battery before touching anything else inside', 'Puncturing the battery can cause fire — go slow around it'],
        'mall': 'phone screen repair kit',
    },
    {
        'field': 'Phones & Tablets',
        'title': "Phone won't charge when plugged in",
        'symptoms': ['The charging icon never appears', 'It only charges when the cable is held at an angle', 'The battery percentage keeps dropping while plugged in'],
        'diagnosis': ['Try a different charger, a different cable, and a different wall outlet', 'Shine a light into the charging port and look for packed-in lint', 'Try wireless charging if the phone supports it — success points at the port, failure points at the battery or board', 'Check the battery health reading in settings'],
        'diy_title': 'Clean the port and isolate the charger, cable, and battery',
        'diy_steps': ['Power the phone off completely', 'Gently dig lint out of the charging port with a wooden or plastic toothpick — never metal', 'Test with a known-good charger and cable that you know work on another device', 'Restart the phone and watch whether it charges while powered off', 'If wireless charging works but the cable never does, the port is damaged and needs professional replacement', 'If the battery is swollen or dies in minutes, stop using it and have the battery replaced'],
        'time': '15–30 min',
        'cost': '$0–$25',
        'difficulty': 'Easy',
        'tools': ['Wooden toothpick', 'Flashlight', 'Soft brush'],
        'parts': ['Quality charging cable', 'Wall charger with correct wattage'],
        'safety': 'MEDIUM',
        'warnings': ['Never use metal tools inside the charging port — you can short it', 'Do not charge a swollen battery — fire risk', 'Do not use frayed or melted cables'],
        'mall': 'USB charging cable',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone battery drains too fast',
        'symptoms': ['The battery dies in a few hours of normal use', 'It drains noticeably overnight on standby', 'The phone feels warm while sitting in a pocket'],
        'diagnosis': ['Open the battery usage screen and find which apps used the most power', 'Check the battery health or maximum capacity percentage in settings', 'Note your screen brightness, screen-on time, and whether location services run constantly', 'Check for poor signal areas — the phone burns power hunting for a tower'],
        'diy_title': 'Tame the hungry apps and services, then judge the battery itself',
        'diy_steps': ['Lower screen brightness and shorten the screen timeout', 'Turn on battery saver mode', 'Restrict background activity for the top power-hungry apps in settings', 'Turn off always-on location for apps that do not need it', 'Update the operating system and apps — updates often fix power bugs', 'If battery health is below about 80 percent, have the battery replaced'],
        'time': '20–40 min',
        'cost': '$0–$50',
        'difficulty': 'Easy',
        'tools': ['None required', 'Charger (to test charging behavior)'],
        'parts': ['Replacement battery (if health is low; usually a shop job)'],
        'safety': 'MEDIUM',
        'warnings': ['Do not try to remove a glued-in battery yourself — puncture risk', 'Stop using a swollen battery immediately'],
        'mall': 'portable phone charger',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone overheating during normal use',
        'symptoms': ['The phone feels uncomfortably hot to hold', 'A temperature warning appears on screen', 'Apps slow down or the phone shuts itself off'],
        'diagnosis': ['Note what you were doing — gaming, video, and navigation heat any phone', 'Check whether it was in direct sunlight or a hot car', 'Check the battery usage screen for an app burning CPU in the background', 'Remove the case and feel whether heat drops quickly'],
        'diy_title': 'Cool it down and stop the heat sources',
        'diy_steps': ['Move the phone out of sunlight and into the shade; never leave it on a hot dashboard', 'Close heavy apps and stop charging while gaming or recording video', 'Take off a thick case so heat can escape', 'Turn on airplane mode for a few minutes to let it cool quickly', 'Update the operating system — runaway background processes are often fixed by updates', 'If it overheats at idle with a normal battery reading, have the battery and charging circuit checked'],
        'time': '10–20 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['None required', 'Battery usage screen (built into settings)'],
        'parts': ['None required'],
        'safety': 'MEDIUM',
        'warnings': ['Never put an overheating phone in the freezer — condensation damages it', 'If the phone is swelling or smells sweet and chemical, power it off and keep it away from flammables'],
        'mall': 'phone cooling fan',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'No cellular signal on the phone',
        'symptoms': ['The status bar shows No Service or SOS only', 'Signal bars are empty where others have bars', 'A SIM error message appears'],
        'diagnosis': ['Check whether Airplane Mode is on', 'Ask whether other phones on the same carrier have signal in the same spot — a tower outage affects everyone', "Check the carrier's outage page or social feed from WiFi", 'Note whether the problem started after travel, a drop, or an update'],
        'diy_title': 'Toggle the radios, reseat the SIM, rule out the carrier',
        'diy_steps': ['Toggle Airplane Mode on for 30 seconds, then off', 'Restart the phone', 'Power off, remove the SIM tray, wipe the SIM gently with a dry cloth, and reseat it', 'Check for a carrier outage online — if the tower is down, only waiting fixes it', 'Reset network settings (this erases saved WiFi passwords too)', 'If a second SIM also fails, or your SIM works in another phone, contact the carrier for a replacement SIM or a repair'],
        'time': '15–30 min',
        'cost': '$0–$10',
        'difficulty': 'Easy',
        'tools': ['SIM ejector tool or a paperclip', 'Second phone (to test the SIM)'],
        'parts': ['Replacement SIM card (free from most carriers)'],
        'safety': 'LOW',
        'warnings': ['Power the phone off before removing the SIM tray'],
        'mall': 'cell signal booster',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Touchscreen not responding to taps',
        'symptoms': ['Taps and swipes do not register', 'One strip or corner of the screen is dead', 'It works after a restart, then stops again'],
        'diagnosis': ['Remove the screen protector — cheap ones cause exactly this', 'Dry the screen and your hands — moisture confuses capacitive touch', 'Check whether the dead area lines up with a crack', 'Boot into safe mode — if touch works there, an app is interfering'],
        'diy_title': 'Remove interference, restart cleanly, test the digitizer',
        'diy_steps': ['Peel off the screen protector and clean the screen with a dry microfiber cloth', 'Force-restart the phone', 'Boot into safe mode and test touch — if it works, uninstall recently added apps one by one', 'Back up your data', 'As a last resort, do a factory reset to rule out software', 'If a dead zone remains after a reset, the digitizer is faulty and the screen assembly needs replacement'],
        'time': '20–45 min',
        'cost': '$0–$80',
        'difficulty': 'Moderate',
        'tools': ['Microfiber cloth', 'Stylus (for testing touch areas)'],
        'parts': ['Screen assembly (if the digitizer is dead)'],
        'safety': 'LOW',
        'warnings': ['Back up before any factory reset — it erases everything'],
        'mall': 'phone screen protector',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone speaker producing no sound',
        'symptoms': ['No sound from the speaker, but headphones work', 'The ringtone is silent', 'Sound crackles or cuts out at high volume'],
        'diagnosis': ['Check the volume and that Do Not Disturb or a mute switch is not on', 'Test with headphones — sound there means the speaker or its path is the problem', 'Inspect the speaker grille for pocket lint and debris', 'Test in safe mode to rule out an app muting audio'],
        'diy_title': 'Clear the mute states, clean the grille, test the hardware',
        'diy_steps': ['Turn off Do Not Disturb and any silent or mute switch, and raise the volume', 'Restart the phone', 'Gently brush the speaker grille clean with a soft dry brush', 'Test sound in safe mode — if it works there, an app is the culprit', 'Update the operating system', 'If the speaker stays silent everywhere, it needs professional replacement'],
        'time': '15–25 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['Soft brush', 'Headphones (for comparison testing)'],
        'parts': ['None required'],
        'safety': 'LOW',
        'warnings': ['Do not poke sharp objects into the speaker grille'],
        'mall': 'bluetooth speaker',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone camera taking blurry photos',
        'symptoms': ['Photos come out soft or out of focus', 'A haze or spots appear in every photo', 'The focus hunts back and forth and never locks'],
        'diagnosis': ['Look at the lens for fingerprints, smudges, or scratches', 'Check whether the case or a screen protector covers part of the lens', 'Test the front and rear cameras separately', 'Test in a different camera app to rule out a software bug'],
        'diy_title': 'Clean the lens properly and rule out software',
        'diy_steps': ['Wipe the lens gently with a clean microfiber cloth in a circular motion', 'Remove the case and check nothing hangs over the lens', 'Open the camera app, tap the subject on screen to force focus, and take a test shot', "Clear the camera app's cache, or update the app and the operating system", 'Test with a different camera app', 'If one lens stays blurry while the other is sharp, that camera module needs professional replacement'],
        'time': '10–20 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['Microfiber cloth', 'Second camera app (for testing)'],
        'parts': ['None required'],
        'safety': 'LOW',
        'warnings': ['Do not use paper towels or clothing on the lens — they scratch the coating'],
        'mall': 'phone camera lens kit',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone stuck in a boot loop',
        'symptoms': ['The phone restarts to the logo over and over', 'It never reaches the home screen', 'It started after an update or a new app'],
        'diagnosis': ['Recall what changed just before — a system update, a new app, or full storage', 'Try booting into safe mode — success points at a third-party app', 'Try recovery mode — if you can reach it, the hardware is likely fine', 'Check whether the phone is recognized by a computer when plugged in'],
        'diy_title': 'Break the loop with safe mode, then update or reset',
        'diy_steps': ['Force-restart the phone with its button combination', 'Boot into safe mode and uninstall the most recently added apps', 'If storage was full, delete large files from safe mode or recovery file access', 'Boot into recovery mode and clear the cache partition', 'Reinstall or update the operating system from a computer', 'As a last resort, do a factory reset from recovery mode'],
        'time': '30–90 min',
        'cost': '$0–$0',
        'difficulty': 'Moderate',
        'tools': ["Computer with the manufacturer's companion software", 'USB cable'],
        'parts': ['None required'],
        'safety': 'MEDIUM',
        'warnings': ['A factory reset erases everything — back up first if the phone stays on long enough', 'Do not interrupt an operating-system reinstall once it starts'],
        'mall': 'USB data cable',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone storage completely full',
        'symptoms': ['Storage full warnings appear', 'You cannot take photos or update apps', 'The phone runs slowly'],
        'diagnosis': ['Open the storage breakdown screen to see what is eating space — photos, videos, apps, or system', 'Check the Downloads folder and messaging apps for large attachments', 'Look for offline maps, downloaded music, and podcast episodes'],
        'diy_title': 'Clear the big hitters and move media off the phone',
        'diy_steps': ['Delete apps you have not opened in months', 'Move photos and videos to cloud storage or a computer, then delete the local copies', 'Clear cached data for the biggest apps in settings', 'Delete downloaded files, old podcasts, and offline content you have finished', 'Empty the trash or recently-deleted folders — deleted files still take space until purged', 'Turn on automatic cloud backup for photos so this does not happen again'],
        'time': '30–60 min',
        'cost': '$0–$30',
        'difficulty': 'Easy',
        'tools': ['Computer or cloud storage account', 'USB cable'],
        'parts': ['Memory card (if the phone has a slot)'],
        'safety': 'LOW',
        'warnings': ['Confirm photos are actually backed up before deleting them from the phone'],
        'mall': 'microSD memory card',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Apps crashing on the phone',
        'symptoms': ['An app closes by itself immediately', 'It crashes on one particular screen', 'Only one app is affected'],
        'diagnosis': ['Check whether the app has an update waiting in the app store', 'Check whether the operating system was recently updated — old apps break on new systems', 'Note whether the crash happens on WiFi, mobile data, or both', 'Check free storage — very full storage crashes apps'],
        'diy_title': 'Force-stop, refresh, and reinstall the app',
        'diy_steps': ['Force-stop the app and reopen it', 'Check the app store and install any update for the app', "Clear the app's cache in settings (do not clear data unless you know your login)", 'Uninstall the app completely, restart the phone, and reinstall it from the official store', "Update the phone's operating system", 'If many apps crash at once, back up and do a factory reset'],
        'time': '15–30 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['None required', 'App store access (for updates)'],
        'parts': ['None required'],
        'safety': 'LOW',
        'warnings': ['Make sure you know your login before clearing app data or reinstalling'],
        'mall': 'phone stand holder',
    },
    {
        'field': 'Phones & Tablets',
        'title': 'Phone dropped in water',
        'symptoms': ['The phone went into water or another liquid', 'It will not turn on, or the screen flickers', 'Speakers sound muffled afterward'],
        'diagnosis': ['Power it off immediately if it is still on — electricity plus water destroys circuits', 'Check the water-damage indicator stickers in the SIM tray if your model has them', 'Note what liquid it was — salt water and sugary drinks corrode far worse than clean water', "Do not trust that a 'water-resistant' rating saved it — seals wear out"],
        'diy_title': 'Power off, dry out, and wait — never charge it wet',
        'diy_steps': ['Power the phone off immediately and do NOT try to turn it back on', 'Remove the case, the SIM tray, and anything plugged into the ports', 'Gently shake out water and pat the phone dry with a soft cloth — do not use heat', 'Stand it upright in a sealed bag or container with silica gel packets for at least 48 hours', 'Do not charge it until it is fully dry inside and out', 'After 48 hours, try powering on — if anything misbehaves, take it to a repair shop for internal cleaning before corrosion spreads'],
        'time': '48–72 hr drying',
        'cost': '$0–$80',
        'difficulty': 'Easy',
        'tools': ['Silica gel packets', 'Soft cloth'],
        'parts': ['None required'],
        'safety': 'HIGH',
        'warnings': ['Never charge a wet phone — short-circuit and fire risk', 'Do not use rice — the dust and starch get into ports and make things worse', 'Do not use a hair dryer — heat warps seals and drives water deeper', 'If the battery is swollen, do not charge or use the phone at all'],
        'mall': 'waterproof phone pouch',
    },
    {
        'field': 'Phones & Tablets',
        'title': "Phone won't turn on at all",
        'symptoms': ['The screen stays black no matter what', 'No vibration, no lights, no sounds', 'It may have died after the battery hit zero'],
        'diagnosis': ['Charge it for at least 30 minutes with a charger you know works', 'Try the force-restart button combination for your model', 'Check for a swollen battery or a cracked screen hiding the display', 'Plug it into a computer — if the computer detects it, the phone is alive and the screen is the problem'],
        'diy_title': 'Charge, force-restart, and find out what is actually dead',
        'diy_steps': ['Plug it into a known-good charger and leave it for 30 minutes without touching it', 'Hold the force-restart button combination for 15–20 seconds', 'Try a different cable and charger in case the first set is dead', 'Plug it into a computer and see whether it is detected — detection means a dead screen, not a dead phone', 'Let it cool down if it is hot, then try again', 'If nothing responds after real charging time, take it to a repair shop — do not keep trying random button combos'],
        'time': '30–60 min',
        'cost': '$0–$60',
        'difficulty': 'Easy',
        'tools': ['Known-good charger and cable', 'Computer (for the detection test)'],
        'parts': ['Replacement battery or screen (diagnosed by a shop)'],
        'safety': 'MEDIUM',
        'warnings': ['If the phone or battery is swollen, do not charge it — fire risk', 'Do not open a phone with a swollen battery yourself'],
        'mall': 'fast phone charger',
    },
    {
        'field': 'Phones & Tablets',
        'title': "Bluetooth won't pair with an accessory",
        'symptoms': ['The accessory never appears in the scan list', 'It pairs and then immediately disconnects', 'It connects but no sound comes through'],
        'diagnosis': ['Confirm the accessory is actually in pairing mode — most need a long button press with a flashing light', 'Check the distance — stay within a few feet with no big metal between them', 'Check whether the accessory is still paired to another phone nearby and stealing the connection', 'Test the accessory with a second phone to find out which side is at fault'],
        'diy_title': 'Reset the pairing on both sides and start fresh',
        'diy_steps': ['Put the accessory into pairing mode exactly as its manual describes', 'On the phone, turn Bluetooth off and back on', 'In Bluetooth settings, choose Forget for the accessory, then scan and pair again', 'Restart both the phone and the accessory', 'Reset network settings on the phone if pairing still fails', "If the accessory pairs fine with a second phone, the first phone's Bluetooth needs a software update or repair"],
        'time': '10–20 min',
        'cost': '$0–$0',
        'difficulty': 'Easy',
        'tools': ['None required', 'Second phone (for testing the accessory)'],
        'parts': ['None required'],
        'safety': 'LOW',
        'warnings': ["Keep the accessory's manual handy for its exact pairing steps"],
        'mall': 'bluetooth earbuds',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'VCR eating and tangling tapes',
        'symptoms': ['Tape comes out tangled or crinkled at the edge', 'The machine makes a straining sound during play', 'Tapes get damaged a little more each time'],
        'diagnosis': ['Unplug the machine and look at the tape path for debris or a loose loop of tape', 'Inspect the pinch roller — a shiny, glazed, or rock-hard roller cannot grip the tape', 'Check the take-up reel — if it does not turn freely, slack tape piles up and tangles', 'Never force the eject — a tangled tape snaps easily'],
        'diy_title': 'Free the tape gently, clean the path, replace the worn roller',
        'diy_steps': ['Unplug the VCR and remove the top cover', 'Gently work the tangled tape free by turning the supply reel by hand — never yank', 'Clean the full tape path (guides, capstan, heads) with 99 percent isopropyl alcohol and chamois swabs', 'Inspect the pinch roller: if it is shiny or hardened, replace it along with the idler tire', 'Check that the take-up reel spins freely and the reel brake releases during play', 'Test with a sacrificial tape before playing anything you care about'],
        'time': '45–90 min',
        'cost': '$5–$25',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Chamois swabs', 'Tweezers', 'Flashlight'],
        'parts': ['Replacement pinch roller', 'Idler tire', '99 percent isopropyl alcohol'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug the VCR before opening it', 'Watch for sharp metal edges inside the mechanism', 'Never pull hard on a tangled tape — it will snap'],
        'mall': 'VCR pinch roller',
    },
    {
        'field': 'Vintage Electronics',
        'title': "VCR won't eject the tape",
        'symptoms': ['Pressing eject does nothing', 'The motor strains or clicks but the tape stays in', 'The tape is stuck halfway out'],
        'diagnosis': ['Unplug for five minutes, plug back in, and try eject once more — logic lockups clear this way', 'Listen: a straining motor with no movement points at a broken or stretched loading belt', 'A tape tangled inside the mechanism jams the whole loading path', 'Do not keep hammering the eject button — it grinds the gears'],
        'diy_title': 'Release the mechanism by hand and fix the loading drive',
        'diy_steps': ['Unplug the VCR, wait five minutes, plug it back in, and try eject once', 'Remove the top cover with the power unplugged', 'Find the loading motor and turn its worm gear by hand to walk the mechanism through the eject cycle', 'If the tape is tangled, free it gently by hand before continuing', 'Inspect the loading belt — if it is stretched, melted, or missing, replace it with the correct size', 'Reassemble and test eject several times with a sacrificial tape'],
        'time': '30–60 min',
        'cost': '$3–$15',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Tweezers', 'Flashlight'],
        'parts': ['Loading belt (correct size for the model)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug before opening the case', 'Do not force the gears — stripped loading gears are hard to replace', 'Keep fingers clear of the mechanism while testing'],
        'mall': 'VCR belt kit',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'CRT television with no picture',
        'symptoms': ['The screen stays completely black', 'Sound may still work', 'The faint high-pitched whine of the flyback is missing'],
        'diagnosis': ['Confirm the set actually powers on — pilot light, static on the screen, speaker hum', 'Turn the brightness up and switch inputs to rule out a source problem', 'Look at the tube neck in a dark room for the faint orange heater glow', 'Check the mains fuse — but a blown fuse usually means a deeper fault'],
        'diy_title': 'Check everything outside, leave the high voltage to a technician',
        'diy_steps': ['Verify power: try a different outlet and confirm the power switch and remote are working', 'Turn up brightness and try every input and the built-in tuner', 'Check the antenna or cable connection', 'In a dark room, look for the heater glow at the tube neck — no glow with power present means a heater or power-supply fault', 'Stop here and take it to a qualified CRT technician — the inside of a CRT set is genuinely dangerous'],
        'time': '20–30 min',
        'cost': '$0–$50',
        'difficulty': 'Hard',
        'tools': ['Flashlight', "Owner's manual (for input and brightness controls)"],
        'parts': ['None — internal parts only through a technician'],
        'safety': 'HIGH',
        'warnings': ["The tube's anode cap holds tens of thousands of volts even when unplugged — never touch it", 'CRT tubes can implode — wear eye protection and never strike the glass', 'Do not open a CRT set unless you are trained to discharge the high voltage safely'],
        'mall': 'CRT discharge probe',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Turntable skipping across records',
        'symptoms': ['The needle skips grooves or jumps', 'It always skips in the same spot on one record', 'There is distortion even when it does not skip'],
        'diagnosis': ['Check the tracking force with a gauge — too light causes skipping', 'Check the anti-skate setting matches the tracking force', 'Inspect the stylus under magnification for dust buildup or a bent cantilever', 'Test with a known-good clean record — a scratched record always skips in the same place', 'Check the turntable is level'],
        'diy_title': 'Clean the stylus, set the tracking force, and level the deck',
        'diy_steps': ['Clean the stylus by brushing gently from back to front with a stylus brush — never front to back', "Set the tracking force to the cartridge maker's specification using a tracking force gauge", 'Set the anti-skate dial to match the tracking force', 'Level the turntable with a bubble level, adjusting the feet', 'Clean the record with a proper record brush before playing', 'If the stylus is visibly bent or worn flat, replace the stylus or cartridge'],
        'time': '20–40 min',
        'cost': '$0–$40',
        'difficulty': 'Easy',
        'tools': ['Tracking force gauge', 'Stylus brush', 'Record cleaning brush', 'Bubble level'],
        'parts': ['Replacement stylus (if worn or bent)'],
        'safety': 'LOW',
        'warnings': ['Never touch the stylus tip with your fingers — skin oil damages it'],
        'mall': 'turntable stylus replacement',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Cassette deck with wow and flutter',
        'symptoms': ['Music pitch wobbles up and down', 'Sustained notes sound warbly', 'It is worse on some tapes than others'],
        'diagnosis': ['Listen on several tapes — if all wobble, the deck is at fault, not the tapes', 'Inspect the belt: a stretched or glazed belt slips and causes speed wobble', 'Check the pinch roller and capstan for grime — dirt lets the tape slip', 'Feel whether the capstan spins smoothly by hand (power off)'],
        'diy_title': 'Clean the tape path and replace the tired belt',
        'diy_steps': ['Unplug the deck and remove the cover', 'Clean the capstan shaft and pinch roller with 99 percent isopropyl alcohol and swabs until no black residue comes off', 'Inspect the belt — if it is stretched, sticky, or has flat spots, replace it with the correct size', 'Clean the tape heads while you are in there', 'Demagnetize the heads with a head demagnetizer if you have one', 'Test with a known-good tape and listen for steady pitch'],
        'time': '45–75 min',
        'cost': '$5–$20',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Cotton swabs', 'Tweezers'],
        'parts': ['Replacement belt set', '99 percent isopropyl alcohol', 'Head demagnetizer (optional)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug the deck before opening it', 'Keep magnetic tools away from the tape heads'],
        'mall': 'cassette deck belt',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Radio plays only static on every band',
        'symptoms': ['No stations come in, just noise', 'Every band is dead, not just one', 'It worked before'],
        'diagnosis': ['Extend the antenna fully and check it is connected — a broken antenna kills reception', 'Try moving the radio near a window or outdoors to rule out local interference', 'Work the band switch back and forth — dirty contacts mute whole bands', 'Check whether the speaker itself works by turning the volume up on the static'],
        'diy_title': 'Fix the antenna path and clean the band switch',
        'diy_steps': ['Extend the telescopic antenna fully and check for a broken or loose connection at its base', 'For AM, rotate the radio — the internal ferrite antenna is directional', 'With the power off, spray electronic contact cleaner into the band switch and work it back and forth dozens of times, then let it dry', 'Clean the volume and tuning controls the same way if they are scratchy', 'Check the speaker wires are connected', 'If bands stay dead after cleaning, the set needs professional alignment or component repair'],
        'time': '20–40 min',
        'cost': '$5–$15',
        'difficulty': 'Easy',
        'tools': ['Phillips screwdriver', 'Soft brush (for cleaning)'],
        'parts': ['Electronic contact cleaner', 'Replacement telescopic antenna (if broken)'],
        'safety': 'LOW',
        'warnings': ['Let contact cleaner dry fully before powering the radio back on'],
        'mall': 'radio antenna replacement',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'VCR tracking lines across playback',
        'symptoms': ['Horizontal noise bars roll through the picture', 'The picture tears or rolls at the top', 'Auto-tracking does not fix it'],
        'diagnosis': ['Try the manual tracking buttons first — some tapes were recorded on misaligned decks', 'Test several tapes — lines on all of them point at dirty or worn video heads', 'Check whether SP tapes play better than EP/SLP — head wear shows up on slow speeds first', 'Look at the video heads under magnification for clogged gaps'],
        'diy_title': 'Adjust tracking, then clean the video heads properly',
        'diy_steps': ['Play the tape and adjust tracking up and down manually to find the cleanest point', 'Unplug the VCR and remove the cover', 'Clean the video heads with a chamois-tip swab barely damp with isopropyl alcohol, rotating the drum by hand — never use cotton, which snags', 'Clean the full tape path and the audio/control head while you are in there', 'Let everything dry, reassemble, and test', 'If noise bars remain on every tape after cleaning, the heads are worn and the drum assembly needs replacement'],
        'time': '30–60 min',
        'cost': '$5–$40',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Chamois-tip swabs', 'Magnifier'],
        'parts': ['99 percent isopropyl alcohol', 'Replacement upper drum (if heads are worn)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug before opening', 'Video heads are fragile — light pressure only, and never use cotton swabs on them'],
        'mall': 'VCR head cleaner',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Retro game console with no power',
        'symptoms': ['The power LED never lights', 'No picture or sound at all', 'It worked the last time it was used'],
        'diagnosis': ["Verify the AC adapter's output voltage with a multimeter — dead adapters are the most common cause", 'Wiggle the power plug gently — a loose DC jack cuts power intermittently', 'Check whether the adapter gets warm — a stone-cold adapter under load is suspect', "Smell the console's vents for a burnt-electronics odor"],
        'diy_title': 'Test the adapter, then check the jack and internal fuse',
        'diy_steps': ['Unplug everything and inspect the adapter and cable for damage', "Measure the adapter's output with a multimeter and compare it to the rating printed on the label", 'If the adapter is good, open the console (power unplugged) and inspect the DC power jack for cracked solder or looseness', 'Check the internal fuse with a multimeter — replace only with the exact same rating', 'Look for bulging capacitors near the power input and replace any that are swollen', 'Reassemble and test with the verified adapter'],
        'time': '30–60 min',
        'cost': '$0–$25',
        'difficulty': 'Moderate',
        'tools': ['Multimeter', 'Phillips or game-bit screwdriver', 'Soldering iron (if resoldering the jack)'],
        'parts': ['Replacement AC adapter (correct voltage and polarity)', 'Fuse of the exact original rating'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug the console before opening it', 'Use an adapter with the exact voltage and plug polarity the console requires — wrong ones kill consoles', 'Replace fuses with the identical rating only'],
        'mall': 'retro console power adapter',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Infrared remote not controlling the device',
        'symptoms': ['No button does anything', 'It only works from very close range', 'Some buttons work and others do not'],
        'diagnosis': ['Put in fresh batteries — weak batteries are the cause most of the time', 'Point the remote at a phone camera and press buttons — a working IR LED shows as a purple-white glow on the camera', 'Check the battery contacts for corrosion', 'Test whether a stuck button is jamming the signal'],
        'diy_title': 'Verify the IR LED, fix the power path, replace if dead',
        'diy_steps': ['Install fresh batteries, checking the polarity markings', "Test the IR LED with a phone camera — no glow means the LED or the remote's circuit is dead", 'Clean corroded battery contacts with a pencil eraser or fine sandpaper', 'Open the remote and clean the rubber keypad contacts and circuit board with isopropyl alcohol', 'Check for a stuck button and free it', 'If the LED never glows, replace the remote with a universal model and program it for your device'],
        'time': '10–25 min',
        'cost': '$0–$20',
        'difficulty': 'Easy',
        'tools': ['Phillips screwdriver', 'Pencil eraser', 'Cotton swabs'],
        'parts': ['Fresh batteries', 'Universal remote control (if the original is dead)'],
        'safety': 'LOW',
        'warnings': ['Dispose of old batteries at a recycling point, not in the trash'],
        'mall': 'universal remote control',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Speakers crackling during playback',
        'symptoms': ['Crackle and static, worse on bass notes', 'Crackling when you turn the volume knob', 'One speaker crackles and the other is clean'],
        'diagnosis': ['Crackle that tracks the volume knob means a dirty potentiometer', 'Swap the left and right speakers — if the crackle moves, the speaker is at fault; if it stays, the amplifier channel is', 'Inspect the speaker cone for tears and the surround for rot', 'Check the speaker wire connections for looseness or stray strands'],
        'diy_title': 'Clean the controls and inspect the drivers',
        'diy_steps': ['With the power off, spray electronic contact cleaner into the volume potentiometer and rotate the knob fully dozens of times, then let it dry', 'Tighten all speaker wire connections and trim any stray strands that could short', 'Inspect each cone for tears — small tears can be patched with flexible speaker repair glue', 'Press the cone gently and evenly — a scraping feel means the voice coil is damaged and the driver must be replaced', 'Swap channels to confirm whether the fault is the speaker or the amplifier before buying parts'],
        'time': '30–60 min',
        'cost': '$5–$60',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Flashlight'],
        'parts': ['Electronic contact cleaner', 'Speaker repair glue', 'Replacement driver (if the voice coil is damaged)'],
        'safety': 'LOW',
        'warnings': ['Power the amplifier off before spraying contact cleaner, and let it dry fully before powering on'],
        'mall': 'speaker repair kit',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'VCR clock flashing 12:00',
        'symptoms': ['The clock display blinks 12:00 constantly', 'Timer recordings are lost after any power cut', 'The clock resets every time the machine is unplugged'],
        'diagnosis': ['A recent power outage explains a one-time reset', 'If it happens after every unplug, the backup battery or memory capacitor inside is dead', 'Check whether the VCR holds any other settings — total amnesia confirms the backup power is gone'],
        'diy_title': 'Set the clock and replace the dead backup battery',
        'diy_steps': ['Set the clock using the on-screen menu — on many decks you just need the correct time entered once', 'Unplug the VCR and open the case', 'Find the small backup battery or large memory capacitor near the main microprocessor', 'Replace it with the same type and rating, observing polarity', 'Reassemble, set the clock, unplug for a minute, and confirm the time survives'],
        'time': '10–20 min',
        'cost': '$2–$10',
        'difficulty': 'Easy',
        'tools': ['Phillips screwdriver', 'Soldering iron (if the battery is soldered in)'],
        'parts': ['Backup battery or memory capacitor (same type and rating)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug the VCR before opening it', 'Observe battery polarity — reversed batteries can leak or burst'],
        'mall': 'VCR backup battery',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Tube amplifier humming loudly',
        'symptoms': ['A loud low hum comes from the speakers', 'The hum is there with no input connected', 'It gets worse as the amp warms up'],
        'diagnosis': ['Disconnect all inputs — if the hum stops, it is a ground loop from another device, not the amp', 'Try a different wall outlet on a different circuit', 'Note whether the hum is 50 or 60 hertz mains hum or a higher buzz — mains hum points at the power supply', 'Aging filter capacitors are the classic cause in old tube amps'],
        'diy_title': 'Rule out ground loops, then let a tech service the power supply',
        'diy_steps': ['Unplug all input cables and power the amp on alone — silence means a ground loop in your setup, not a broken amp', 'Plug the amp and source devices into the same power strip to kill ground loops', 'Check that all tubes are fully seated in their sockets (power off and cooled down first)', 'If the hum persists with no inputs, the filter capacitors are likely dried out', 'Take it to a qualified tube-amp technician for a capacitor replacement — this is not a beginner job'],
        'time': '20–40 min',
        'cost': '$0–$120',
        'difficulty': 'Hard',
        'tools': ['None required', 'Same power strip (for the ground-loop test)'],
        'parts': ['None — filter capacitor service by a technician'],
        'safety': 'HIGH',
        'warnings': ['Tube amplifiers store lethal voltage in their filter capacitors even when unplugged', 'Never probe inside a tube amp unless you know how to discharge the capacitors safely', 'Let tubes cool fully before touching them — they burn'],
        'mall': 'tube amplifier service',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'CD player skipping on clean discs',
        'symptoms': ['It skips even on scratch-free discs', 'It struggles to read the disc or shows a disc error', 'Skipping is worse near the end of the disc'],
        'diagnosis': ['Test several clean discs — skipping on all of them means the player, not the discs', 'Skipping near the end of discs points at a tired laser or a dragging sled mechanism', 'Listen for the sled motor straining as it moves the laser outward', 'Check whether the disc spins up smoothly or wobbles'],
        'diy_title': 'Clean the laser lens and free the sled mechanism',
        'diy_steps': ['Unplug the player and open the case', 'Gently clean the small laser lens with a foam swab barely damp with isopropyl alcohol — light pressure only', 'Inspect the sled rails and gear for old hardened grease; clean and apply a tiny amount of proper lubricant', 'Check the disc clamp and spindle for wobble', 'Reassemble and test with a clean, known-good disc', 'If it still skips everywhere, the laser is worn out and the pickup assembly needs replacement'],
        'time': '30–60 min',
        'cost': '$3–$40',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Foam swabs'],
        'parts': ['99 percent isopropyl alcohol', 'Replacement laser pickup (if the laser is worn)'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug before opening the case', 'Never look directly at the laser lens while the player is powered', 'Do not touch the lens with your fingers'],
        'mall': 'CD laser lens cleaner',
    },
    {
        'field': 'Vintage Electronics',
        'title': 'Reel-to-reel tape playing too slowly',
        'symptoms': ['Music plays slow and the pitch is low', 'The take-up reel turns sluggishly', 'Speed drifts during playback'],
        'diagnosis': ['Confirm the speed selector is set correctly — some decks have multiple speeds', 'Inspect the drive belt for stretch or glazing — slipping belts slow everything down', 'Check the pinch roller and capstan for grime that lets the tape slip', 'Feel whether the supply reel brake is dragging'],
        'diy_title': 'Clean the drive path and replace the slipping belt',
        'diy_steps': ['Unplug the deck and remove the cover', 'Clean the capstan shaft and pinch roller with isopropyl alcohol until no residue comes off', 'Inspect the belt — replace it if it is stretched, shiny, or has flat spots', 'Check that the reel brakes release fully in play mode and adjust if they drag', 'Lubricate the motor and reel bearings with one drop of proper machine oil each — never general-purpose spray oil on the tape path', 'Verify speed with a test tape or a known recording and adjust the speed control if provided'],
        'time': '45–90 min',
        'cost': '$5–$25',
        'difficulty': 'Moderate',
        'tools': ['Phillips screwdriver', 'Cotton swabs', 'Tweezers'],
        'parts': ['Replacement belt', '99 percent isopropyl alcohol', 'Precision machine oil'],
        'safety': 'MEDIUM',
        'warnings': ['Unplug before opening', 'Keep oil off the tape path, heads, and pinch roller — oil ruins tape contact'],
        'mall': 'reel to reel belt',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Bulging or leaking capacitor on a board',
        'symptoms': ['Capacitor tops are bulging, split, or pushed up', "Brown crust or dried residue sits at the capacitor's base", 'The device reboots randomly or will not power on'],
        'diagnosis': ['Inspect every electrolytic capacitor visually — bulging tops and leakage are definitive', 'Note the capacitance, voltage rating, temperature rating, and size printed on each bad cap', 'Check whether the board flexes or the caps sit near a heat source, which shortens their life', 'Test the replacements are the right physical size to fit the board'],
        'diy_title': 'Desolder the failed caps and fit exact-value replacements',
        'diy_steps': ['Unplug the device and let it sit so capacitors discharge', 'Heat one lead at a time with the soldering iron and lift the bad capacitor out with tweezers', 'Clean the pads with desoldering braid and a little flux', 'Fit the new capacitor with the same capacitance and an equal or higher voltage rating', 'Observe polarity — the stripe marks the negative lead, and the board marks the positive hole', 'Solder both leads, trim the excess, and test the device'],
        'time': '30–60 min',
        'cost': '$2–$15',
        'difficulty': 'Moderate',
        'tools': ['Soldering iron', 'Desoldering braid or pump', 'Tweezers', 'Flux', 'Magnifier'],
        'parts': ['Replacement electrolytic capacitors (same capacitance, equal or higher voltage)'],
        'safety': 'MEDIUM',
        'warnings': ['Electrolytic capacitors are polarized — installing one backwards can make it vent or burst', 'The soldering iron tip is hot enough to burn instantly — rest it in its stand', 'Work in a ventilated area'],
        'mall': 'capacitor assortment kit',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Cold solder joint causing intermittent faults',
        'symptoms': ['The device works when tapped or flexed, then fails again', 'Suspicious joints look dull, grainy, or cracked instead of shiny', 'One function cuts in and out'],
        'diagnosis': ['Inspect suspect joints under magnification — a good joint is smooth and shiny with a concave fillet', 'Gently tap components with an insulated tool while the device runs to find the flaky joint', 'Check connectors and heavy components first — they crack joints with mechanical stress', 'Confirm it is the joint and not a cracked trace by watching the fault follow the tap'],
        'diy_title': 'Reflow the bad joint with fresh solder and flux',
        'diy_steps': ['Power the device off and unplug it', 'Add a tiny amount of flux to the suspect joint', 'Heat the joint with the soldering iron until the old solder melts and flows', 'Feed in a small amount of fresh solder and let it form a shiny concave fillet', 'Remove the iron and hold the board perfectly still until the joint cools', 'Inspect under magnification and test the device'],
        'time': '15–30 min',
        'cost': '$0–$10',
        'difficulty': 'Easy',
        'tools': ['Soldering iron', 'Flux', 'Magnifier', 'Solder'],
        'parts': ['None required'],
        'safety': 'MEDIUM',
        'warnings': ['The iron tip is around 350 degrees — work on a heat-safe surface and rest the iron in its stand', 'Do not overheat the joint — lifted pads are harder to fix than cold joints'],
        'mall': 'soldering iron kit',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Board dead with a short circuit on the power rail',
        'symptoms': ['The power supply shuts down or current-limits as soon as the board is connected', 'One component gets very hot very fast', 'There is a smell of hot plastic or a visible scorch mark'],
        'diagnosis': ['Unplug power and visually inspect for burnt parts, solder bridges, and damaged traces', 'Measure resistance across the power rails with a multimeter — near zero ohms confirms a hard short', 'Feel carefully for the hot component after a brief power pulse — that is usually the failed part', 'Suspect tantalum capacitors and voltage regulators first — they fail short most often'],
        'diy_title': 'Find the short with limited current, then remove the failed part',
        'diy_steps': ['Disconnect all power and remove the board from its enclosure', 'Measure rail-to-ground resistance to confirm the short and note which rail is affected', 'Power the board from a current-limited bench supply set to the correct voltage and a low current limit', 'Find the component getting hot — an infrared thermometer or careful fingertip check works', 'Desolder the suspect and re-check the rail resistance', 'Replace the failed component with the correct part and verify the short is gone before full power'],
        'time': '1–2 hr',
        'cost': '$5–$40',
        'difficulty': 'Hard',
        'tools': ['Multimeter', 'Current-limited bench power supply', 'Soldering iron', 'Desoldering braid', 'Infrared thermometer'],
        'parts': ['Replacement for the failed component (capacitor, regulator, or IC)'],
        'safety': 'HIGH',
        'warnings': ['Never power a shorted board from an unlimited supply — fire risk', 'Always use a current-limited supply when hunting shorts', 'Let hot components cool before touching them'],
        'mall': 'bench power supply',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Lifted copper pad on a circuit board',
        'symptoms': ['The copper pad came off with the component during desoldering', 'There is bare board where a solder pad should be', 'The lead has nothing to solder to'],
        'diagnosis': ['Inspect under magnification to see where the trace ran from the missing pad', 'Check whether the trace is intact under the solder mask on either side', 'Decide whether the trace carries a signal you can bridge with a wire', 'Note nearby pads so the repair wire does not short to them'],
        'diy_title': 'Bridge the broken trace with a jumper wire',
        'diy_steps': ['Power off and secure the board so it cannot move', 'Gently scrape the solder mask off the trace on both sides of the missing pad to expose clean copper', 'Tin the exposed trace sections with a little solder', 'Solder a thin jumper wire from the component lead to the exposed trace', 'Route the wire flat along the board and tack it down with a drop of epoxy for strain relief', 'Verify continuity with a multimeter and check for shorts to neighboring traces'],
        'time': '30–60 min',
        'cost': '$0–$10',
        'difficulty': 'Hard',
        'tools': ['Soldering iron', 'Fiberglass scratch brush or scalpel', 'Tweezers', 'Multimeter', 'Magnifier'],
        'parts': ['Thin jumper wire', 'Epoxy or UV solder mask'],
        'safety': 'MEDIUM',
        'warnings': ['Scrape gently — cutting through the trace makes the repair much harder', 'Keep the iron heat brief to avoid lifting neighboring pads too'],
        'mall': 'jumper wire kit',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Dead voltage regulator on a board',
        'symptoms': ['The output rail reads zero volts or the wrong voltage', 'Input voltage is present but nothing downstream powers up', 'The regulator is stone cold — or scorching hot'],
        'diagnosis': ["Measure the input voltage at the regulator's input pin — it must be present and in range", "Measure the output pin against the regulator's rated voltage", 'Check the datasheet pinout — input, ground, and output vary by package', 'Check the enable or shutdown pin if the regulator has one'],
        'diy_title': 'Confirm the failure, then swap in the identical regulator',
        'diy_steps': ['With power on, measure input voltage at the regulator — confirm it is present', 'Measure the output — zero or wrong voltage with good input means a dead regulator', 'Power off and desolder the failed regulator', 'Solder in the exact replacement part number, matching the pinout', 'Reattach or replace the heatsink if the original had one', 'Power up and verify every output rail before reconnecting the load'],
        'time': '30–60 min',
        'cost': '$2–$15',
        'difficulty': 'Moderate',
        'tools': ['Multimeter', 'Soldering iron', 'Desoldering braid', 'Tweezers'],
        'parts': ['Exact replacement voltage regulator'],
        'safety': 'MEDIUM',
        'warnings': ["Confirm the replacement's pinout matches — same package does not always mean same pinout", 'Never power the board with the regulator removed if downstream parts need its rail sequenced'],
        'mall': 'voltage regulator kit',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Blown fuse on a circuit board',
        'symptoms': ['The device is completely dead', 'The fuse tests open with a multimeter', 'The fuse glass is blackened or the wire inside is broken'],
        'diagnosis': ['Test the fuse for continuity — no beep means it is blown', "Read the fuse's rating and type (fast or slow blow) from its markings", 'Find out WHY it blew before replacing it — fuses die protecting something', 'Check for shorts downstream with the multimeter before fitting the new fuse'],
        'diy_title': 'Find the cause, then fit the identical fuse',
        'diy_steps': ['Unplug the device completely', 'Remove the fuse and confirm it is open with a continuity test', 'Inspect downstream for the fault that blew it — shorts, failed capacitors, wrong adapter', 'Fix the underlying fault first', 'Fit a new fuse of the exact same current rating, voltage rating, and blow characteristic', 'Power up and watch closely — if it blows again immediately, stop and keep diagnosing'],
        'time': '20–40 min',
        'cost': '$1–$10',
        'difficulty': 'Easy',
        'tools': ['Multimeter', 'Tweezers or fuse puller'],
        'parts': ['Replacement fuse (identical rating and type)'],
        'safety': 'HIGH',
        'warnings': ['Replace with the exact same rating — never a higher one, which defeats the protection', 'A fuse that blows again means an unresolved fault — do not keep feeding it fuses', 'Unplug the device before touching the fuse'],
        'mall': 'assorted glass fuses',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Corroded battery contacts in a device',
        'symptoms': ['The device is dead even with fresh batteries', 'White or green crust coats the battery contacts', 'Wiggling the batteries makes it work briefly'],
        'diagnosis': ['Remove the batteries and inspect the contacts and springs', 'Identify the crust — alkaline leaks leave white or green powdery corrosion', 'Check whether corrosion has spread to nearby circuit board traces', 'Check that the springs still have tension'],
        'diy_title': 'Neutralize the corrosion and restore clean contact',
        'diy_steps': ['Remove the batteries and dispose of any that leaked', 'Dab white vinegar on a cotton swab and gently dissolve the crusty corrosion', 'Scrub the contacts lightly until bright metal shows', 'Wipe with a dry swab, then a barely damp water swab, then dry completely', 'For stubborn spots, lightly sand with fine sandpaper or a fiberglass brush', 'Fit fresh batteries and test — if the springs are eaten through, replace the battery holder'],
        'time': '15–30 min',
        'cost': '$0–$10',
        'difficulty': 'Easy',
        'tools': ['Cotton swabs', 'Fine sandpaper or fiberglass brush', 'Tweezers'],
        'parts': ['White vinegar', 'Fresh batteries', 'Replacement battery holder (if springs are destroyed)'],
        'safety': 'MEDIUM',
        'warnings': ['Wear gloves — leaked battery chemicals irritate skin and eyes', "Do not let liquid drip into the device's electronics", 'Dispose of leaked batteries at a battery recycling point, not in the trash'],
        'mall': 'battery contact cleaner',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Broken copper trace on a PCB',
        'symptoms': ['A signal is dead between two points on the board', 'A visible scratch or cut crosses a trace', 'The fault comes and goes when the board flexes'],
        'diagnosis': ['Inspect the board under good light and magnification for the break', 'Test continuity across the suspect trace with a multimeter', 'Check whether the break is on the surface or under the solder mask', 'Map which two points the trace should connect'],
        'diy_title': 'Expose the copper and bridge the break',
        'diy_steps': ['Power off and remove the board', 'Gently scrape the solder mask off the trace on both sides of the break to expose clean copper', 'Tin both exposed sections with a little solder', 'Bridge the gap with a thin wire or a careful solder blob for very short breaks', 'Cover the repair with epoxy or UV solder mask to protect and insulate it', 'Verify continuity across the repair and check for shorts to adjacent traces'],
        'time': '20–40 min',
        'cost': '$0–$10',
        'difficulty': 'Moderate',
        'tools': ['Soldering iron', 'Fiberglass scratch brush or scalpel', 'Multimeter', 'Magnifier'],
        'parts': ['Thin jumper wire', 'Epoxy or UV solder mask'],
        'safety': 'MEDIUM',
        'warnings': ['Scrape only the solder mask — cutting the trace deeper widens the repair', 'Confirm no solder bridges to neighboring traces before powering up'],
        'mall': 'PCB repair kit',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Chip running dangerously hot',
        'symptoms': ['The chip is too hot to touch', 'The device shuts down from thermal protection', 'There is a smell of hot plastic near the chip'],
        'diagnosis': ['Check whether the heatsink is loose, missing, or clogged with dust', "Verify the supply voltage matches the chip's rating — overvoltage cooks chips", "Check the chip's load — a shorted output forces it to dissipate excess power", "Compare against the datasheet's expected temperature rise"],
        'diy_title': 'Restore cooling, then find what is overloading it',
        'diy_steps': ['Power off and let the chip cool completely', 'Reseat or replace the heatsink with fresh thermal paste or a thermal pad', 'Clean any dust from heatsinks and fans', "Measure the supply voltage and confirm it matches the chip's rating", "Check the chip's outputs for shorts that would force excess current", 'If it still overheats with correct voltage, good cooling, and no output short, the chip itself is failing internally and must be replaced'],
        'time': '30–60 min',
        'cost': '$2–$25',
        'difficulty': 'Moderate',
        'tools': ['Multimeter', 'Phillips screwdriver', 'Isopropyl alcohol and cloth (for old thermal paste)'],
        'parts': ['Thermal paste or thermal pad', 'Replacement heatsink or fan (if missing)', 'Replacement chip (if internally failed)'],
        'safety': 'MEDIUM',
        'warnings': ['Let the chip cool fully before touching it — burns happen fast', 'Overheating can signal an internal short — investigate the cause, do not just add cooling', 'Unplug before removing heatsinks'],
        'mall': 'heatsink thermal paste',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'Dead crystal oscillator stopping a microcontroller',
        'symptoms': ['The microcontroller will not start and there is no clock signal', 'Serial communication runs at wrong baud rates', 'Power rails are fine but the board is lifeless'],
        'diagnosis': ['Confirm power reaches the microcontroller first — no power looks like no clock', 'Probe the oscillator output with an oscilloscope or frequency counter', "Inspect the crystal's solder joints and its two load capacitors", "Check the crystal's marked frequency against what the firmware expects"],
        'diy_title': 'Verify the clock, then replace the crystal and load caps',
        'diy_steps': ['Power the board and probe the clock output — a flat line means the oscillator is not running', 'Power off and inspect the crystal and load capacitor solder joints under magnification, reflowing any suspect ones', 'Desolder the crystal and its load capacitors', 'Fit a new crystal of the exact frequency with load capacitors matched to its specification', 'Power up and confirm a clean clock signal on the scope', 'Verify the microcontroller boots and peripherals run at correct rates'],
        'time': '30–60 min',
        'cost': '$1–$10',
        'difficulty': 'Moderate',
        'tools': ['Oscilloscope or frequency counter', 'Soldering iron', 'Desoldering braid', 'Magnifier'],
        'parts': ['Replacement crystal (exact frequency)', 'Matching load capacitors'],
        'safety': 'MEDIUM',
        'warnings': ["Match the load capacitance to the crystal's specification — wrong values stop oscillation", 'Use a grounded iron tip practice around static-sensitive parts'],
        'mall': 'crystal oscillator kit',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': 'LED strip with a dead section',
        'symptoms': ['One section of the strip stays dark while the rest lights', 'A section flickers or shows the wrong color', 'The dead section starts right at a cut line or solder joint'],
        'diagnosis': ['Find exactly where the lit section ends — the fault is at that boundary', 'Inspect the solder joints at the cut lines for cracks', 'Check the voltage along the strip — a big drop points at a bad connection', 'Test the first dark LED — one failed LED kills everything downstream of it'],
        'diy_title': 'Cut out the failed segment and bridge the gap',
        'diy_steps': ["Unplug the strip's power supply completely", 'Locate the failed segment at the boundary between lit and dark', 'Cut the strip only at the marked cut lines on either side of the bad segment', 'Strip and tin the copper pads at the cut lines, observing the polarity markings', 'Solder a bridge wire or a replacement segment between the good sections', 'Insulate the joints, restore power, and check the full strip lights evenly'],
        'time': '20–40 min',
        'cost': '$3–$20',
        'difficulty': 'Moderate',
        'tools': ['Soldering iron', 'Wire strippers', 'Scissors', 'Multimeter'],
        'parts': ['Replacement LED strip segment', 'Thin hookup wire', 'Heat-shrink tubing'],
        'safety': 'MEDIUM',
        'warnings': ['Only repair low-voltage 12V or 24V strips yourself', 'If the strip runs directly on mains voltage, do not open it — replace the whole unit', 'Observe polarity — reversed power damages LED strips'],
        'mall': 'LED strip connector',
    },
    {
        'field': 'Chips & Circuit Boards',
        'title': "Microcontroller that won't accept programming",
        'symptoms': ['The programmer reports no device found', 'Uploads fail partway through', 'It programmed fine before and suddenly stopped'],
        'diagnosis': ['Check every programmer-to-target wire against the pinout — swapped transmit and receive lines are the classic mistake', 'Confirm the target board is powered during programming', 'Check the reset and bootloader-mode pins are in the right state', "Verify the programmer's drivers installed correctly on the computer"],
        'diy_title': 'Fix the wiring, force bootloader mode, and retry',
        'diy_steps': ['Power everything off and rewire strictly by the pinout diagram — double-check transmit goes to receive and back', 'Power the target board from its own supply so the programmer is not straining to power it', 'Put the microcontroller into bootloader or programming mode using its specified button or pin sequence', "Update or reinstall the programmer's drivers on the computer", 'Lower the programming baud rate and try again', "If the chip was locked or read-protected by a previous session, run the manufacturer's unlock or mass-erase procedure"],
        'time': '20–45 min',
        'cost': '$0–$20',
        'difficulty': 'Moderate',
        'tools': ['Multimeter', 'Jumper wires', 'Computer with programming software'],
        'parts': ['Replacement programmer (if the current one is proven dead)'],
        'safety': 'LOW',
        'warnings': ['Never connect or disconnect programming wires while either side is powered'],
        'mall': 'USB programmer adapter',
    },
]
